---
title: "Chapter 7 - LME Analysis of Utterance mean f0"
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE)

# Load Functions.
source("../../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "stringr",
    "broomExtra",
    "janitor",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

p_color <- all_models_tidy ~ style(color =
                                     if_else(as.double(all_models_tidy) < 0.05,
                                             "green",
                                             "red"))

# Load Corpus
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  select(speaker,
         gender,
         mode,
         prompt,
         phr_phon,
         utt_mean_f0) %>%
  mutate(starts_with_H =
           if_else(
             !is.na((str_extract(phr_phon, "%H|\\^\\[%H|% H\\*"))),
             TRUE,
             FALSE),
         starts_with_H = factor(starts_with_H, levels = unique(starts_with_H))
  )

```


### LME model analysis using initial model
```{r}
# set current equation
cur_equation  <-
  "utt_mean_f0 ~ mode + gender + starts_with_H + (1 + mode | speaker) + (1 | prompt)"

```
### ``r cur_equation``

Prompt is used as an intercepts only random effect since the model does not converge when intercept and slope effect are both included.

```{r fig.height=3, fig.width=9, message = FALSE, tidy = TRUE}
temp_mdl = lmer(
  formula(cur_equation),
  data = m_corpus,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)
```

```{r fig.height=3, fig.width=9, warning = FALSE, message = FALSE, tidy = TRUE}


summarise_lme(temp_mdl , run_step = TRUE)
```


```{r fig.height=3, fig.width=9, warning = FALSE, message = FALSE, tidy = TRUE}

# set current equation
cur_equation  <-
  "utt_mean_f0 ~ mode + (1|gender) + (1 + mode | speaker)"

temp_mdl = lmer(
  formula(cur_equation),
  data = m_corpus,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)
summarise_lme(temp_mdl , run_step = TRUE)
```

### Final model: ``r cur_equation``

#### Analysis of model

```{r fig.height=3, fig.width=9, warning = FALSE, message = FALSE, tidy = TRUE}
utt_lh_slope.tidy <- printTidyModel(
  temp_mdl,
  bf_adj = 4,
  exclude_terms = "genderM",
  write_r2 = "slope"
)
utt_lh_slope.tidy$table
utt_lh_slope.tidy$r2
```


```{r fig.height=3, fig.width=9, warning = FALSE, message = FALSE, tidy = TRUE}
# Get number of levels in target treatment variable.

charts <- getLMEFixedFX(
  my_equation = cur_equation,
  my_data = m_corpus,
  exclude_terms = c("gender"),
  bf_adj = 4,
  write = "slope"
)
charts$intercepts
charts$pairwise
```
