---
title: "Chapter 7 - LME Analysis of Utterance Slope"
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE)

# Load Functions.
source("../../functions/myFunctions.R")
```


```{r load packages etc., message=FALSE, warning=FALSE, include=FALSE}
# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "janitor",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

p_color <- all_models_tidy ~ style(color =
                                     if_else(as.double(all_models_tidy) < 0.05,
                                             "green",
                                             "red"))
```


```{r load corpus,  message=FALSE, warning=FALSE, include=FALSE}
# Load Corpus
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  select(speaker,
         gender,
         mode,
         phr_phon,
         utt_slope) %>%
  mutate(starts_with_H =
           if_else(
             !is.na((str_extract(phr_phon, "%H|\\^\\[%H|% H\\*"))),
             TRUE,
             FALSE)
)

```

Include initial %H or % H* in model to mitigate against skewing effect of initial phonologically high f0
```{r fig.height=3, fig.width=9, message = FALSE, tidy = TRUE}
# set recommended equation
utt_slope_mdl  <-  lmer(utt_slope ~ mode  + (1 + mode | speaker),
  data = m_corpus,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)


# model needs trimming
m_corpus.trimmed <- m_corpus %>% filter(abs(scale(resid(utt_slope_mdl))) <= 3)


utt_slope_mdl.trimmed  <-  lmer(utt_slope ~ mode  + (1 + mode | speaker),
  data = m_corpus.trimmed,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

summarise_lme(utt_slope_mdl.trimmed , run_step = TRUE)
```


#### Analysis of model

```{r fig.height=3, fig.width=9, warning = FALSE, message = FALSE, tidy = TRUE}
utt_utt_slope.tidy <- printTidyModel(
  utt_slope_mdl.trimmed,
  bf_adj = 4,
  exclude_terms = c("fin_phonL%",
                    "genderM",
                    "starts_with_HTRUE"),
                                write_r2="../output/slope"
                                )
utt_utt_slope.tidy$table
utt_utt_slope.tidy$r2
```

```{r fig.height=3, fig.width=9, warning = FALSE, message = FALSE, tidy = TRUE}
# Get number of levels in target treatment variable.

charts <- getModelFixedFX(
  my_equation = utt_slope ~ mode  + (1 + mode | speaker),
  my_data = m_corpus.trimmed,
  exclude_terms = c("fin_phon",
                    "gender",
                    "starts_with_H"),
  bf_adj = 4,
  write="../output/slope"
)
charts$intercepts
charts$pairwise

```
