---
title: "Chapter 7 - Analysis of Nuclear PA L_f0 H_f0, and slope"
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}

# Load Functions.
source("../../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    "plotly",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

mode_colours <- c("MWH" = "#e41a1c",
                  "MDC" = "#377eb8",
                  "MYN" = "#4daf4a",
                  "MDQ" = "#984ea3")

pitch_accent_colours <- c("H*"     = brewer.pal(6, "Spectral")[4],
                          "L*H"    = brewer.pal(6, "Spectral")[6],
                          ">H*"    = brewer.pal(6, "Spectral")[5],
                          "^[L*]H" = brewer.pal(6, "Spectral")[3],
                          "L*^[H]" = brewer.pal(6, "Spectral")[2],
                          "^[L*H]" = brewer.pal(6, "Spectral")[1])

p_color <- all_models_tidy ~ style(color =
                                     if_else(as.double(all_models_tidy) < 0.05,
                                             "green",
                                             "red")
                                   )


```

```{r}
# Load Corpus
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  # Consolidate nuc_contour based on observation and types of register shift.
  mutate(
    nuc_contour =
      if_else(
        nuc_contour == "^[L*H %]" | nuc_contour == "^[L*H L%]",
        "^[L*H] %",
        if_else(nuc_contour == "L*^[H L%]", "L*^[H] %", nuc_contour)
      ),
    acc_phon =
      factor(
        str_replace(nuc_contour,
                    "\\s%$|\\sL%$",
                    ""),
        levels = c("H*", "L*H", ">H*", "^[L*]H", "L*^[H]", "^[L*H]")
      ),
    fin_phon = str_replace_all(fin_phon, "L%]|%]", "%")
  ) %>%
  # Select only columns for analysis
  select(
    speaker,
    stim,
    acc_phon,
    lh_slope,
    l_f0_z,
    h_f0_z,
    lh_mean_f0_z,
    lh_slope_z

  )

```


```{r}
# Get mean slope and f0_z per speaker per stimulus.
m_corpus_summary <- m_corpus %>%
  group_by(speaker, stim, acc_phon) %>%
  summarise(
    mean_slope_z = round(mean(lh_slope_z), 3),
    mean_l_f0_z = round(mean(l_f0_z), 3),
    mean_h_f0_z = round(mean(h_f0_z), 3),
    .groups = "keep"
  ) 

  # exclude outlier speakers
  # filter(speaker %notin% c("F16", "F15", "M8"))
```

3D plot of L_f0_z, H_f0_z, and Slope
```{r, fig.width=7, fig.height=5}

# If colors aren't  explicitly linked to levels, plot_ly appears to adjust the
# RGB settings on the fly, which is very irritating! The following two lines
# prevent this from happening
pal <- brewer.pal(4, "Dark2")
pal <- setNames(pal, c("L*H", "^[L*]H", "L*^[H]", "^[L*H]"))

plot_ly(
  m_corpus_summary %>% filter(acc_phon %in% c("L*H", "^[L*]H", "L*^[H]", "^[L*H]")),
  #m_corpus %>% filter(acc_phon %in% c("L*H")),
  x = ~ mean_slope_z,
  y = ~ mean_l_f0_z,
  z = ~ mean_h_f0_z,
  type = "scatter3d",
  mode = "markers",
  color = ~acc_phon,
  colors = pal,
  opacity = 0.5,
  # Marker characteristics must be stated explicitly inside the 'marker =' 
  # parameter setting. However, as marker is a struct (?list?), we need to
  # use the 'list()' function to set the values inside the marker struct.
  # This process is iterated for the line parameters with the marker struct.
  marker = list(size = 6, line = list(width = 0.5, color = "#333333", opacity = 0.75))
)

```

