---
title: 'Chapter 07: Analysis of Function: Sentence Modes and Phonology (Register Tier)'
mainfont: Times New Roman
output:
  html_document: default
font-family: Times New Roman
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)


# Load Functions.
source("../../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    "broom",
    "broomExtra",
    "formattable",
    "janitor",
    "kableExtra",
    "knitr",
    "lmerTest",
    "MuMIn",
    "optimx",
    "performance",
    "sjPlot",
    "tidyverse",
    "ggeffects"

  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 10))

# Change this as required
options("speakr.praat.path" = "C:/Program Files/Praat/Praat.exe")


```

```{r load and process corpus, include=FALSE}
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  # Consolidate nuc_contour based on observation and types of register shift.

  mutate(
    # remove non-accentuation from phr_phon
    mode =  factor(mode, levels=c("MDC", "MWH", "MYN", "MDQ")),
    phr_phon = str_replace_all(phr_phon, "\\(\\*\\)\\s", ""),
    phr_phon = str_replace_all(phr_phon, "\\s\\s", "\\s"),
    phr_phon = factor(phr_phon, levels=unique(phr_phon)),
    one_pa = str_count(phr_phon, "\\*")==1,
    one_pa = factor(one_pa, levels=unique(one_pa)),
    h_reg = str_detect(phr_phon, "\\^"),
    h_reg =  factor(h_reg, levels=unique(h_reg)),
    one_pa_or_h_reg = factor((h_reg == T | one_pa ==T), levels = c(F, T))
    ) %>%

  # Select only columns for analysis
  select(speaker,
         mode,
         phr_phon,
         one_pa,
         h_reg,
         one_pa_or_h_reg)


```


```{r one_pa_or_h_reg model test}
one_pa_or_h_reg_model <- glmer(
   one_pa_or_h_reg ~ mode + (1 | speaker),
  data = m_corpus,
  family = binomial(link = "logit"),
  # change optimizer to avoid convergence errors
  control = glmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

one_pa_or_h_reg_null = 
  cur_model <- glmer(
   one_pa_or_h_reg ~ 1 + (1 | speaker),
  data = m_corpus,
  family = binomial(link = "logit"),
  # change optimizer to avoid convergence errors
  control = glmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

summary(one_pa_or_h_reg_model)
```


```{r one_pa_or_h_reg model results, fig.width = 4.2, fig.height = 2.5, results="asis"}
cat(
  "isSingular(one_pa_or_h_reg_model, tol=1e-5) -->",
  isSingular(one_pa_or_h_reg_model, tol = 1e-5),
  "\n"
)

anova(one_pa_or_h_reg_model, one_pa_or_h_reg_null, test="Chisq") %>%
  formattable(
  caption="ANOVA of model and null model, assuming presence of register tier"
  )

x <- printTidyModel(one_pa_or_h_reg_model,
                    write_r2="Utt_one_pa_or_h_reg_GLMM",
                    is_GLM = TRUE,
                    transform="exp",
                    show.intercept=TRUE
                    )

x$r2
x$table

one_pa_or_h_reg_charts <- getModelFixedFX(
  my_equation = one_pa_or_h_reg ~ mode + (1 | speaker),
  my_data = m_corpus,
  write = "Utt_one_pa_or_h_reg_GLMM",
  is_GLM = TRUE
)


one_pa_or_h_reg_charts$intercepts

one_pa_or_h_reg_charts$pairwise

```

```{r one_pa_model test}
one_pa_model <- glmer(
  one_pa ~ mode + (1 | speaker),
  data = m_corpus,
  family = binomial(link = "logit"),
  # change optimizer to avoid convergence errors
  control = glmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

one_pa_model_null = 
  cur_model <- glmer(
  one_pa ~ 1 + (1 | speaker),
  data = m_corpus,
  family = binomial(link = "logit"),
  # change optimizer to avoid convergence errors
  control = glmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

summary(one_pa_model)
```


```{r one_pa_model test results, fig.width = 4.2, fig.height = 2.5, results="asis"}
cat(
  "\nisSingular(one_pa_model, tol=1e-5) -->",
  isSingular(one_pa_model, tol = 1e-5),
  "\n"
)

anova(one_pa_model, one_pa_model_null, test="Chisq") %>%
  formattable(
  caption="ANOVA of model and null model, assuming presence of register tier"
  )

x <- printTidyModel(one_pa_model,
                    write_r2="Utt_one_pa_GLMM",
                    is_GLM = TRUE,
                    transform="exp",
                    show.intercept=TRUE
                    )


x$r2
x$table
```


```{r test one_pa pairwise}
one_pa_charts <- getModelFixedFX(
  my_equation = one_pa ~ mode + (1 | speaker),
  my_data = m_corpus,
  write = "Utt_one_pa_GLMM",
  is_GLM = TRUE
)


one_pa_charts$intercepts %>% mutate(estimate = exp(estimate))
one_pa_charts$pairwise %>% mutate(estimate = exp(estimate))
```


```{r h_reg_model test}
h_reg_model <- glmer(
  h_reg ~ mode + (1 | speaker),
  data = m_corpus,
  family = binomial(link = "logit"),
  # change optimizer to avoid convergence errors
  control = glmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

h_reg_model_null = 
  cur_model <- glmer(
  h_reg ~ 1 + (1 | speaker),
  data = m_corpus,
  family = binomial(link = "logit"),
  # change optimizer to avoid convergence errors
  control = glmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

summary(h_reg_model)
```


```{r h_reg_model test resaults, fig.width = 4.2, fig.height = 2.5, results="asis"}
cat(
  "\nisSingular(h_reg_model, tol=1e-5) -->",
  isSingular(h_reg_model, tol = 1e-5),
  "\n"
)

anova(h_reg_model, h_reg_model_null, test="Chisq") %>%
  formattable(
  caption="ANOVA of model and null model, assuming presence of register tier"
  )

x <- printTidyModel(h_reg_model,
                    write_r2="Utt_h_reg_GLMM",
                    is_GLM = TRUE,
                    transform="exp",
                    show.intercept=TRUE
                    )

x$r2
x$table

```


```{r test h_reg pairwise}
h_reg_charts <- getModelFixedFX(
  my_equation = h_reg ~ mode + (1 | speaker),
  my_data = m_corpus,
  write = "Utt_h_reg_GLMM",
  is_GLM = TRUE
)

h_reg_charts$intercepts %>% mutate(estimate = exp(estimate))
h_reg_charts$pairwise %>% mutate(estimate = exp(estimate))

```

