---
title: "Chapter 7 - LME analysis of l_t ~ Mode and Nuclear pitch accents: "
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = F,
                      warning = F,
                      message = F)

# Load Functions.
source("../../2_R_Functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)
```


```{r load corpus}
# Load Corpus
m_corpus <- get_m_corpus("../../4_data/m_corpus.csv")  %>%

  # Select only columns for analysis
  select(
    speaker,
    gender,
    mode,
    prompt,
    acc_phon,
    fin_phon,
    l_t
  ) %>%
  filter(acc_phon %notin% c("H*", ">H*")) %>% 
  mutate(acc_phon = factor(acc_phon,
                           levels = c("L*H", "^[L*]H", "L*^[H]", "^[L*H]"))
         )
```

```{r set equation}
my_equation = formula(
  l_t ~ mode * acc_phon
  + (1 + mode + acc_phon | speaker)
  + (1 | gender)
  + (1 | fin_phon)
  + (1 | prompt)
)

# model works with random acc_phon slope removed
# but keep with random intercepts only for parity with h_t

my_equation = formula(
  l_t ~ mode * acc_phon
  + (1 | speaker)
# + (1 | gender)
  + (1 | fin_phon)
  + (1 | prompt)
)
```


```{r run initial model,  fig.height=3, fig.width=9, include=F}
l_t_model <-
  lmer(my_equation,
       data = m_corpus,
        control = lmerControl(
          optimizer = "optimx",
          calc.derivs = F,
          optCtrl = list(
            method = "nlminb",
            starttests = F,
            kkt = F
          )
        )
      )

summariseLME(l_t_model, run_step=TRUE)

```

-   Model works.
-   Trimming mode to remove residuals from model with standard deviation > 3.25

```{r run intercepts only model,  fig.height=3, fig.width=9}

m_corpus.trimmed <- m_corpus %>% filter(abs(scale(resid(l_t_model))) <= 3.25)

l_t_model.trimmed <- lmer(my_equation,
       data = m_corpus.trimmed,
        control = lmerControl(
          optimizer = "optimx",
          calc.derivs = F,
          optCtrl = list(
            method = "nlminb",
            starttests = F,
            kkt = F
          )
        )
      )

summariseLME(l_t_model.trimmed, run_step=TRUE,
              write="../output_model_anovas/Mode_PA_l_t_anova.csv")

```
```{r random effect of prompt, fig.height=2, fig.width=5}
plot_model(l_t_model,
           type="re",
           axis.title = c("semitones", "prompt"),
           title="random effect: prompt",
           show.values = T)[2:3]
```

```{r make tidy model, fig.height=5, fig.width=7, results="asis"}

l_t_model.tidy <- analyseModel(l_t_model.trimmed,
                                write="../output/Mode_PA_l_t"
                                )
l_t_model.tidy$table

```

```{r do pairwise analysis}

charts <- getModelFixedFX(
  my_equation,
  my_data = m_corpus.trimmed,
  write="../output/Mode_PA_l_t"
)
charts$intercepts
charts$slopes %>% tidyStatNumbers()


```
