---
title: "LME Analysis of PN and Foot size"
author: "Antoin Rodgers"
date: "18.05.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

# Get personal functions and install / load necessary packages.
source("../functions/myFunctions.R")

installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "ggeffects",
    "optimx",
    "MuMIn",
    "dfoptim",

    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",

    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

# Get  data for analysis

source("6_0_get_AH.R")

h_star_type <-  c("L*H", ">H*", "H*")
l_star_type <-  c("L*H", "L*")

pn_foot <- select(pn_foot,
                 # human factors
                 speaker, gender,
                 # phonological factors
                 acc_phon, foot_syls, 
                 # phonetic factors
                 wrd_end_t, speech_rate,
                 # responses
                 l_t, l_f0, h_t, h_f0, f0_exc, lh_slope) %>% 
  mutate(
    wrd_end_t_n = normalize(wrd_end_t),
    speech_rate_n = normalize(speech_rate),
    log_lh_slope = log(lh_slope)
    )


pn_foot_lh_data <- pn_foot %>%
  filter(acc_phon %in% l_star_type) %>%
  mutate(acc_phon = factor(acc_phon, levels = l_star_type))

pn_foot_h_data <- pn_foot %>%
  filter(acc_phon %in% h_star_type) %>%
  mutate(acc_phon = factor(acc_phon, levels = h_star_type)) %>%
  select(-c(l_t, l_f0))

# Separate set with only L*H for slope and excursion size.
pn_foot_l_star_h_data <- pn_foot_lh_data %>% filter(acc_phon == "L*H") %>% 
  select(-acc_phon)



```

```{r check levels in factors, results="asis", eval=FALSE}

cat("Tibble factors for pn_foot_lh_data\n")
for (i in colnames(pn_foot_lh_data)) {
  if (is.factor(pn_foot_lh_data[[eval(i)]])) {
    cat("\n", i, "  \tlevels = ", levels(pn_foot_lh_data[[i]]))
  }
  else {
    cat("\n", i)
    }
}
cat("\n\nacc_phon counts\n")
summary(pn_foot_lh_data$acc_phon)

cat("\n\nTibble factors for pn_foot_h_data\n")
for (i in colnames(pn_foot_h_data)) {
  if (is.factor(pn_foot_h_data[[eval(i)]])) {
    cat("\n", i, "  \tlevels = ", levels(pn_foot_h_data[[i]]))
  }
    else {
    cat("\n", i)
    }
}
cat("\n\nacc_phon counts\n")
summary(pn_foot_h_data$acc_phon)


```

```{r Remove unwanted objects from environment}
rm(pn, nuc, nuc_foot,pn_foot, pn_lex, pn_ana, corpus, nuc_pre)
rm(stress, l_star_type, h_star_type)

```

### l\_t

```{r pn_foot_l_t Get best model, fig.height=3, fig.width=9}
pn_foot_l_t_formula = formula(
  l_t ~ foot_syls + acc_phon + gender
  + (1 + foot_syls + acc_phon | speaker)
  + (1 | wrd_end_t_n)
  + (1 | speech_rate_n)
  )                         

pn_foot_l_t_mdl = lmer(
  pn_foot_l_t_formula,
  pn_foot_lh_data,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

# Check optimization and update model to most optimal
# pn_foot_l_t_mdl <- optLme4Mdl(pn_foot_l_t_mdl, reject_nl = T)

if(!modelIsOK(pn_foot_l_t_mdl)){
  step_result <- step(pn_foot_l_t_mdl)
  cat("Model found by step():", getModelFormula(get_model(step_result)), "\n")
}

cat("Updating formula.\n", sep ="")
pn_foot_l_t_formula = formula(
  l_t ~ foot_syls + acc_phon + gender
  + (1 + acc_phon | speaker)
  #+ (1 | wrd_end_t_n)
  #+ (1 | speech_rate_n)
  )

pn_foot_l_t_mdl <- update(pn_foot_l_t_mdl, formula = pn_foot_l_t_formula)
# Check optimization and update model to most optimal
pn_foot_l_t_mdl <- optLme4Mdl(pn_foot_l_t_mdl)
pn_foot_l_t_mdl <- update(pn_foot_l_t_mdl,
                          formula = pn_foot_l_t_formula,
                          control = lmerControl(
                            optimizer = "nloptwrap",
                            optCtrl = list(algorithm = "NLOPT_LN_COBYLA",
                                           maxfun = 1e9,
                                           maxeval = 1e7,
                                           xtol_abs = 1e-9,
                                           ftol_abs = 1e-9))
                          )

first <- summariseLME(pn_foot_l_t_mdl, print_summary = F)

# model needs trimming
sd_threshold = 3
cat("\nTrimming data with residual sd > ", sd_threshold, ".\n", sep ="")
pn_foot_l_t_data.trimmed <-
  pn_foot_lh_data %>% filter(abs(scale(resid(pn_foot_l_t_mdl))) <= sd_threshold)

pn_foot_l_t_mdl.trimmed <- update(pn_foot_l_t_mdl, data = pn_foot_l_t_data.trimmed)
pn_foot_l_t_mdl.trimmed <- optLme4Mdl(pn_foot_l_t_mdl.trimmed)


tibble(`Summary of model` = getModelFormula(pn_foot_l_t_mdl.trimmed)) %>%
        formattable(align = "l")

anova <- summariseLME(pn_foot_l_t_mdl.trimmed, 
                      write = "6_4_pn_subs_output/pn_foot_l_t_anova.csv")

adjustP_posthoc("6_4_pn_subs_output/",
                p.value,
                suffix_id = "_anova")

read_csv("6_4_pn_subs_output/pn_foot_l_t_anova.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_foot_l_t_mdl.trimmed)))


```
```{r pn_foot_l_t analyse model, fig.height=2.5, fig.width=3.01, results='asis'}
pn_foot_l_t_mdl.tidy <- analyseModel(
  pn_foot_l_t_mdl.trimmed
  , write="6_4_pn_subs_output/pn_foot_h_t"
  , type = "pred"
  , factor_matrix = TRUE
  )
```
```{r pn_foot_l_t pairwise comparison, fig.height=2.5, fig.width=3.01}
charts <- getModelFixedFX(
  pn_foot_l_t_mdl.trimmed,
  write="6_4_pn_subs_output/pn_foot_l_t",
)

adjustP_posthoc("6_4_pn_subs_output/",
                p.value,
                suffix_id = "_b0", marginal = T)
adjustP_posthoc("6_4_pn_subs_output/",
                p.value,
                suffix_id = "_b1", marginal = T)

read_csv("6_4_pn_subs_output/pn_foot_l_t_b0.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Intercepts of model:",
                            getModelFormula(pn_foot_l_t_mdl.trimmed)))

read_csv("6_4_pn_subs_output/pn_foot_l_t_b1.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Slopes of model:",
                            getModelFormula(pn_foot_l_t_mdl.trimmed)))

```

### l\_f0

```{r pn_foot_l_f0 Get best model, fig.height=3, fig.width=9}
pn_foot_l_f0_formula = formula(
  l_f0 ~ foot_syls + acc_phon + gender
  + (1 + foot_syls + acc_phon | speaker)
  + (1 | wrd_end_t_n)
  + (1 | speech_rate_n)
  )                      

pn_foot_l_f0_mdl = lmer(
  pn_foot_l_f0_formula,
  pn_foot_lh_data,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

# pn_foot_l_f0_mdl <- optLme4Mdl(pn_foot_l_f0_mdl)

if(!modelIsOK(pn_foot_l_f0_mdl)){
  step_result <- step(pn_foot_l_f0_mdl)
  cat("Model found by step():", getModelFormula(get_model(step_result)), "\n")
}


cat("Updating formula.\n", sep ="")
pn_foot_l_f0_formula = formula(
  l_f0 ~ foot_syls + acc_phon + gender
  + (1 + foot_syls | speaker)
  #+ (1 | wrd_end_t_n)
  #+ (1 | speech_rate_n)
  ) 

pn_foot_l_f0_mdl <- update(pn_foot_l_f0_mdl,
                           formula = pn_foot_l_f0_formula)

pn_foot_l_f0_mdl <- optLme4Mdl(pn_foot_l_f0_mdl)

first <- summariseLME(pn_foot_l_f0_mdl, run_step = F, print_summary = F)

# model needs trimming
sd_threshold = 4.25
cat("\nTrimming data with residual sd > ", sd_threshold, ".\n", sep ="")
pn_foot_l_f0_data.trimmed <-
  pn_foot_lh_data %>% filter(abs(scale(resid(pn_foot_l_f0_mdl))) <= sd_threshold)

pn_foot_l_f0_mdl.trimmed <- update(pn_foot_l_f0_mdl,
                                   data = pn_foot_l_f0_data.trimmed)

pn_foot_l_f0_mdl.trimmed <- optLme4Mdl(pn_foot_l_f0_mdl.trimmed)


cat("Updating formula.\n", sep ="")
pn_foot_l_f0_formula = formula(
  l_f0 ~ foot_syls + acc_phon + gender
  + (1 | speaker)
  #+ (1 | wrd_end_t_n)
  #+ (1 | speech_rate_n)
  ) 

pn_foot_l_f0_mdl.trimmed <- update(pn_foot_l_f0_mdl,
                                   formula = pn_foot_l_f0_formula)

pn_foot_l_f0_mdl.trimmed <- optLme4Mdl(pn_foot_l_f0_mdl.trimmed)

tibble(`Summary of model` = getModelFormula(pn_foot_l_f0_mdl.trimmed)) %>%
        formattable(align = "l")

anova <- summariseLME(
  pn_foot_l_f0_mdl.trimmed
 , write = "6_4_pn_subs_output/pn_foot_l_f0_anova.csv"
  )

adjustP_posthoc("6_4_pn_subs_output/",
                p.value,
                suffix_id = "_anova")

read_csv("6_4_pn_subs_output/pn_foot_l_f0_anova.csv") %>%
  tidyStatNumbers() %>%
  formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_foot_l_f0_mdl.trimmed)))


```
```{r pn_foot_l_f0 analyse model, fig.height=2.5, fig.width=3.01, results='asis'}
pn_foot_l_f0_mdl.tidy <- analyseModel(
  pn_foot_l_f0_mdl.trimmed
  , write="6_4_pn_subs_output/pn_foot_l_f0"
  , type = "pred"
  , factor_matrix = TRUE
  )
```
```{r pn_foot_l_f0 pairwise comparison, fig.height=2.5, fig.width=3.01}
charts <- getModelFixedFX(pn_foot_l_f0_mdl.trimmed, write="6_4_pn_subs_output/pn_foot_l_f0")

adjustP_posthoc("6_4_pn_subs_output/", p.value, suffix_id = "_b0", marginal = T)
adjustP_posthoc("6_4_pn_subs_output/", p.value, suffix_id = "_b1", marginal = T)

read_csv("6_4_pn_subs_output/pn_foot_l_f0_b0.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Intercepts of model:",
                            getModelFormula(pn_foot_l_f0_mdl.trimmed)))

read_csv("6_4_pn_subs_output/pn_foot_l_f0_b1.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Slopes of model:",
                            getModelFormula(pn_foot_l_f0_mdl.trimmed)))
```

### h\_t

```{r pn_foot_h_t Get best model, fig.height=3, fig.width=9}
pn_foot_h_t_formula = formula(
  h_t ~ foot_syls + acc_phon + gender
  + (1 + foot_syls + acc_phon | speaker)
  + (1 | wrd_end_t_n)
  + (1 | speech_rate_n)
  )                         

pn_foot_h_t_mdl = lmer(
  pn_foot_h_t_formula,
  pn_foot_h_data,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

# Check optimization and update model to most optimal
# pn_foot_h_t_mdl <- optLme4Mdl(pn_foot_h_t_mdl, reject_nl = T)

if(!modelIsOK(pn_foot_h_t_mdl)){
  step_result <- step(pn_foot_h_t_mdl)
  cat("Model found by step():", getModelFormula(get_model(step_result)), "\n")
}

cat("Updating formula.\n", sep ="")
pn_foot_h_t_formula = formula(
  h_t ~ foot_syls + acc_phon + gender
  + (1 + foot_syls | speaker)
 # + (1 | wrd_end_t_n)
  #+ (1 | speech_rate_n)
  )

pn_foot_h_t_mdl <- update(pn_foot_h_t_mdl, formula = pn_foot_h_t_formula)
# Check optimization and update model to most optimal
pn_foot_h_t_mdl <- optLme4Mdl(pn_foot_h_t_mdl)
pn_foot_h_t_mdl <- update(pn_foot_h_t_mdl, control = lmerControl(
  optimizer = "nloptwrap",
  optCtrl = list(algorithm = "NLOPT_LN_COBYLA",
                 maxfun = 1e9,
                 maxeval = 1e7,
                 xtol_abs = 1e-9,
                 ftol_abs = 1e-9)
  ))


first <- summariseLME(pn_foot_h_t_mdl, print_summary = F)

# model needs trimming
sd_threshold = 3
cat("\nTrimming data with residual sd > ", sd_threshold, ".\n", sep ="")
pn_foot_h_t_data.trimmed <-
  pn_foot_h_data %>% filter(abs(scale(resid(pn_foot_h_t_mdl))) <= sd_threshold)

pn_foot_h_t_mdl.trimmed <- update(pn_foot_h_t_mdl, data = pn_foot_h_t_data.trimmed)
pn_foot_h_t_mdl.trimmed <- optLme4Mdl(pn_foot_h_t_mdl.trimmed)

tibble(`Summary of model` = getModelFormula(pn_foot_h_t_mdl.trimmed)) %>%
        formattable(align = "l")

anova <- summariseLME(
  pn_foot_h_t_mdl.trimmed
 , write = "6_4_pn_subs_output/pn_foot_h_t_anova.csv"
  )

adjustP_posthoc("6_4_pn_subs_output/",
                p.value,
                suffix_id = "_anova")

read_csv("6_4_pn_subs_output/pn_foot_h_t_anova.csv") %>%
  tidyStatNumbers() %>%
  formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_foot_h_t_mdl.trimmed)))


```
```{r pn_foot_h_t analyse model, fig.height=2.5, fig.width=3.01, results = "asis"}
pn_foot_h_t_mdl.tidy <- analyseModel(
  pn_foot_h_t_mdl.trimmed
  , write="6_4_pn_subs_output/pn_foot_h_t"
  , type = "pred"
  , factor_matrix = TRUE
  )
```
```{r pn_foot_h_t pairwise comparison, fig.height=2.5, fig.width=3.01}
charts <- getModelFixedFX(pn_foot_h_t_mdl.trimmed, write="6_4_pn_subs_output/pn_foot_h_t")

adjustP_posthoc("6_4_pn_subs_output/", p.value, suffix_id = "_b0", marginal = T)
adjustP_posthoc("6_4_pn_subs_output/", p.value, suffix_id = "_b1", marginal = T)

read_csv("6_4_pn_subs_output/pn_foot_h_t_b0.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Intercepts of model:",
                            getModelFormula(pn_foot_h_t_mdl.trimmed)))

read_csv("6_4_pn_subs_output/pn_foot_h_t_b1.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Slopes of model:",
                            getModelFormula(pn_foot_h_t_mdl.trimmed)))



```

### h\_f0

```{r pn_foot_h_f0 Get best model, fig.height=3, fig.width=9}
pn_foot_h_f0_formula = formula(
  h_f0 ~ foot_syls + acc_phon + gender
  + (1 + foot_syls + acc_phon | speaker)
  + (1 | wrd_end_t_n)
  + (1 | speech_rate_n)
  )                         

pn_foot_h_f0_mdl = lmer(
  pn_foot_h_f0_formula,
  pn_foot_lh_data,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

# Check optimization and update model to most optimal
pn_foot_h_f0_mdl <- optLme4Mdl(pn_foot_h_f0_mdl, reject_nl = T)
pn_foot_h_f0_mdl <- update(pn_foot_h_f0_mdl,
                          control = lmerControl(
                            optimizer = "nloptwrap",
                            optCtrl = list(
                              algorithm = "NLOPT_LN_NEWUOA",
                              maxfun = 1e9,
                              maxeval = 1e7,
                              xtol_abs = 1e-9,
                              ftol_abs = 1e-9
                            )
                          ))

if(!modelIsOK(pn_foot_h_f0_mdl)){
  step_result <- step(pn_foot_h_f0_mdl)
  cat("Model found by step():", getModelFormula(get_model(step_result)), "\n")
}

#first <- summariseLME(pn_foot_h_f0_mdl, print_summary = F)

anova <- summariseLME(
  pn_foot_h_f0_mdl
 , write = "6_4_pn_subs_output/pn_foot_h_f0_anova.csv"
  )

adjustP_posthoc("6_4_pn_subs_output/",
                p.value,
                suffix_id = "_anova")

read_csv("6_4_pn_subs_output/pn_foot_h_f0_anova.csv") %>%
  tidyStatNumbers() %>%
  formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_foot_h_f0_mdl)))


```
```{r pn_foot_h_f0 analyse model, fig.height=2.5, fig.width=3.01, results = "asis"}
pn_foot_h_f0_mdl.tidy <- analyseModel(
  pn_foot_h_f0_mdl
  , write="6_4_pn_subs_output/pn_foot_h_f0"
  , type = "pred"
  , factor_matrix = TRUE
  )
```
```{r pn_foot_h_f0 pairwise comparison, fig.height=2.5, fig.width=3.01}
charts <- getModelFixedFX(pn_foot_h_f0_mdl, write="6_4_pn_subs_output/pn_foot_h_f0")

adjustP_posthoc("6_4_pn_subs_output/", p.value, suffix_id = "_b0", marginal = T)
adjustP_posthoc("6_4_pn_subs_output/", p.value, suffix_id = "_b1", marginal = T)

read_csv("6_4_pn_subs_output/pn_foot_h_f0_b0.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Intercepts of model:",
                            getModelFormula(pn_foot_h_f0_mdl)))

read_csv("6_4_pn_subs_output/pn_foot_h_f0_b1.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Slopes of model:",
                            getModelFormula(pn_foot_h_f0_mdl)))

```

### f0\_exc

```{r pn_foot_f0_exc Get best model, fig.height=3, fig.width=9}
pn_foot_f0_exc_formula = formula(
  f0_exc ~ foot_syls + gender
  + (1 + foot_syls | speaker)
  + (1 | wrd_end_t_n)
  + (1 | speech_rate_n)
  )                         

pn_foot_f0_exc_mdl = lmer(
  pn_foot_f0_exc_formula,
  pn_foot_l_star_h_data,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

# Check optimization and update model to most optimal
# pn_foot_f0_exc_mdl <- optLme4Mdl(pn_foot_f0_exc_mdl, reject_nl = T)

if(!modelIsOK(pn_foot_f0_exc_mdl)){
  step_result <- step(pn_foot_f0_exc_mdl)
  cat("Model found by step():", getModelFormula(get_model(step_result)), "\n")
}

pn_foot_f0_exc_formula = formula(
  f0_exc ~ foot_syls + gender
  + (1 + foot_syls | speaker)
  #+ (1 | wrd_end_t_n)
  #+ (1 | speech_rate_n)
  )
pn_foot_f0_exc_mdl <- update(pn_foot_f0_exc_mdl,
                             formula = pn_foot_f0_exc_formula)
pn_foot_f0_exc_mdl <- optLme4Mdl(pn_foot_f0_exc_mdl, reject_nl = T)
pn_foot_f0_exc_mdl <- update(pn_foot_f0_exc_mdl,
                             control = lmerControl(
                               optimizer = "nloptwrap",
                               optCtrl = list(
                                 algorithm = "NLOPT_LN_COBYLA",
                                 maxfun = 1e9,
                                 maxeval = 1e7,
                                 xtol_abs = 1e-9,
                                 ftol_abs = 1e-9
                               )
                             ))

tibble(`Summary of model` = getModelFormula(pn_foot_f0_exc_mdl)) %>%
        formattable(align = "l")

anova <- summariseLME(
  pn_foot_f0_exc_mdl,
  run_step = F
  , write = "6_4_pn_subs_output/pn_foot_f0_exc_anova.csv"
  )

adjustP_posthoc("6_4_pn_subs_output/",
                p.value,
                suffix_id = "_anova")

read_csv("6_4_pn_subs_output/pn_foot_f0_exc_anova.csv") %>%
  tidyStatNumbers() %>%
  formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_foot_f0_exc_mdl)))


```
```{r pn_foot_f0_exc analyse model, fig.height=2.5, fig.width=3.01, results = "asis"}
pn_foot_f0_exc_mdl.tidy <- analyseModel(
  pn_foot_f0_exc_mdl
  , write="6_4_pn_subs_output/pn_foot_f0_exc"
  , type = "pred"
  , factor_matrix = TRUE
  )
```
```{r pn_foot_f0_exc pairwise comparison, fig.height=2.5, fig.width=3.01}
charts <- getModelFixedFX(pn_foot_f0_exc_mdl, write="6_4_pn_subs_output/pn_foot_f0_exc")
```


```{r}
adjustP_posthoc("6_4_pn_subs_output/", p.value, suffix_id = "_b0", marginal = T)
```


```{r}
adjustP_posthoc("6_4_pn_subs_output/", p.value, suffix_id = "_b1", marginal = T)
```


```{r}
read_csv("6_4_pn_subs_output/pn_foot_f0_exc_b0.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Intercepts of model:",
                            getModelFormula(pn_foot_f0_exc_mdl)))
```


```{r}
read_csv("6_4_pn_subs_output/pn_foot_f0_exc_b1.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Slopes of model:",
                            getModelFormula(pn_foot_f0_exc_mdl)))



```

### lh\_slope

```{r pn_foot_lh_slope Get best model, fig.height=3, fig.width=9}
pn_foot_lh_slope_formula = formula(
  lh_slope ~ foot_syls + gender
  + (1 + foot_syls | speaker)
  + (1 | wrd_end_t_n)
  + (1 | speech_rate_n)
  )                         

pn_foot_lh_slope_mdl = lmer(
  pn_foot_lh_slope_formula,
  pn_foot_l_star_h_data,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

# Check optimization and update model to most optimal
pn_foot_lh_slope_mdl <- optLme4Mdl(pn_foot_lh_slope_mdl, reject_nl = T)

step_result <- step(pn_foot_lh_slope_mdl)
cat("Model found by step():", getModelFormula(get_model(step_result)), "\n")

first <- summariseLME(pn_foot_lh_slope_mdl, print_summary = F)

# model needs trimming
sd_threshold = 3
cat("\nTrimming data with residual sd > ", sd_threshold, ".\n", sep ="")
pn_foot_lh_slope_data.trimmed <-
  pn_foot_l_star_h_data %>%
  filter(abs(scale(resid(pn_foot_lh_slope_mdl))) <= sd_threshold)

# update has deformed model too much --> running from scratch with trimmed data
pn_foot_lh_slope_mdl.trimmed <- lmer(
  pn_foot_lh_slope_formula,
  pn_foot_lh_slope_data.trimmed,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

pn_foot_lh_slope_mdl.trimmed <- optLme4Mdl(pn_foot_lh_slope_mdl.trimmed)

cat("Updating formula.\n", sep ="")
pn_foot_lh_slope_formula = formula(
  lh_slope ~ foot_syls + gender
  + (1 + foot_syls | speaker)
  #+ (1 | wrd_end_t_n)
  #+ (1 | speech_rate_n)
  ) 

pn_foot_lh_slope_mdl.trimmed <- update(pn_foot_lh_slope_mdl.trimmed,
                               formula = pn_foot_lh_slope_formula)
pn_foot_lh_slope_mdl.trimmed <- optLme4Mdl(pn_foot_lh_slope_mdl.trimmed, reject_nl = T)

tibble(`Summary of model` = getModelFormula(pn_foot_lh_slope_mdl.trimmed)) %>%
        formattable(align = "l")

anova <- summariseLME(pn_foot_lh_slope_mdl.trimmed,
                      write ="6_4_pn_subs_output/pn_foot_lh_slope_anova.csv")

adjustP_posthoc("6_4_pn_subs_output/",
                p.value,
                suffix_id = "_anova")

read_csv("6_4_pn_subs_output/pn_foot_lh_slope_anova.csv") %>%
  tidyStatNumbers() %>%
  formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_foot_lh_slope_mdl.trimmed)))


```
```{r pn_foot_lh_slope analyse model, fig.height=2.5, fig.width=3.01, results = "asis"}
pn_foot_lh_slope_mdl.tidy <- analyseModel(
  pn_foot_lh_slope_mdl.trimmed
  , write="6_4_pn_subs_output/pn_foot_lh_slope"
  , type = "pred"
  , factor_matrix = TRUE
  )
```
```{r pn_foot_lh_slope pairwise comparison, fig.height=2.5, fig.width=3.01}
charts <- getModelFixedFX(pn_foot_lh_slope_mdl.trimmed, write="6_4_pn_subs_output/pn_foot_lh_slope")


adjustP_posthoc("6_4_pn_subs_output/", p.value, suffix_id = "_b0", marginal = T)
adjustP_posthoc("6_4_pn_subs_output/", p.value, suffix_id = "_b1", marginal = T)

read_csv("6_4_pn_subs_output/pn_foot_lh_slope_b0.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Intercepts of model:",
                            getModelFormula(pn_foot_lh_slope_mdl.trimmed)))

read_csv("6_4_pn_subs_output/pn_foot_lh_slope_b1.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Slopes of model:",
                            getModelFormula(pn_foot_lh_slope_mdl.trimmed)))


```

