---
title: "Chapter 7 - LME analysis of h_t|h_f0 ~ Mode and Nuclear pitch accents M8 H*-like models"
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

# Load Functions.
source("../../../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)
```


```{r load corpus}
h_star_likes <- c("H*", ">H*", "^[L*]H")
# Load Corpus
m_corpus <- get_m_corpus("../../data/m_corpus.csv")  %>%
  # Select only columns for analysis
  select(
    speaker,
    mode,
    prompt,
    acc_phon,
    h_t,
    h_f0
  ) %>% 
  filter(speaker=="M8") %>% 
  # keep only explicitly LH pitch accents.
  filter(acc_phon %in% h_star_likes) %>%
  mutate(acc_phon = factor(acc_phon,
                           levels = h_star_likes),
         mode = factor(mode, levels=c("MDC", "MYN", "MDQ")),
         prompt = factor(prompt, levels = unique(prompt))) %>% 
  filter(prompt=="valuables") %>% 
  select(-speaker, -prompt)

m_corpus %>%
  mutate(acc_phon = str_replace_all(acc_phon, "([\\*\\[\\^\\>])", "\\\\\\1")) %>% 
                  formattable(caption="H\\*-like H targets for M8")
```

### **H Time**

```{r run h_t model,  fig.height=3, fig.width=9}
h_t_equation = formula(
  h_t ~ mode * acc_phon
)

# run model
h_t_model <-
  lm(h_t_equation,
       data = m_corpus
      )

summary(h_t_model)

anova(h_t_model) %>% formattable()

tidy(h_t_model) %>%
  mutate(term = str_replace_all(term,
                                     "([\\*\\[\\^\\>])",
                                     "\\\\\\1")) %>%
  formattable()


plot_model(h_t_model)

```

### **H f0**

```{r run h_f0model,  fig.height=3, fig.width=9}
h_f0_equation = formula(
  h_f0 ~ mode * acc_phon
)

# run model
h_f0_model <-
  lm(h_f0_equation,
       data = m_corpus
      )

summary(h_f0_model)

anova(h_f0_model) %>% formattable()

tidy(h_f0_model) %>%
    mutate(term = str_replace_all(term,
                                     "([\\*\\[\\^\\>])",
                                     "\\\\\\1")) %>%
  formattable()

plot_model(h_f0_model)

```

