---
title: "Chapter 7 - LME analysis of Mode and Nuclear Contours"
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}

# Load Functions.
source("../../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

mode_colours <- c("WHQ" = "#a6dba0",
                  "MDC" = "#7b32942",
                  "MYN" = "#008837",
                  "MDQ" = "#c2a5cf")

pitch_accent_colours <- c("H*"     = brewer.pal(6, "Spectral")[4],
                          "L*H"    = brewer.pal(6, "Spectral")[6],
                          ">H*"    = brewer.pal(6, "Spectral")[5],
                          "^[L*]H" = brewer.pal(6, "Spectral")[3],
                          "L*^[H]" = brewer.pal(6, "Spectral")[2],
                          "^[L*H]" = brewer.pal(6, "Spectral")[1])

p_color <- all_models_tidy ~ style(color =
                                     if_else(as.double(all_models_tidy) < 0.05,
                                             "green",
                                             "red")
                                   )


```

```{r}
# Load Corpus
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  # Consolidate nuc_contour based on observation and types of register shift.
  mutate(
    nuc_contour =
      if_else(
        nuc_contour == "^[L*H %]" | nuc_contour == "^[L*H L%]",
        "^[L*H] %",
        if_else(nuc_contour == "L*^[H L%]", "L*^[H] %", nuc_contour)
      ),
    acc_phon =
      factor(
        str_replace(nuc_contour,
                    "\\s%$|\\sL%$",
                    ""),
        levels = c("H*", "L*H", ">H*", "^[L*]H", "L*^[H]", "^[L*H]")
      ),
    fin_phon = str_replace_all(fin_phon, "L%]|%]", "%")
  ) %>%
  # Select only columns for analysis
  select(
    speaker,
    gender,
    mode,
    prompt,
    foot_syls,
    acc_phon,
    phr_phon,
    fin_phon,
    l_t,
    l_f0,
    h_f0,
    f0_exc,
    lh_slope
  )

```

```{r}
response_vars <- c("l_t", "l_f0", "h_f0", "f0_exc", "lh_slope")
model_equation = NULL
model_equation = c(model_equation, paste(response_vars, " ~ mode + gender + (1 + mode | speaker)", sep = ""))



```

```{r fig.height=3, fig.width=9, warning = FALSE, message = FALSE, tidy = TRUE}
for (cur_equation in model_equation) {
  temp_mdl = lmer(
    formula(cur_equation),
    data = m_corpus,
    control = lmerControl(
      optimizer = "optimx",
      calc.derivs = FALSE,
      optCtrl = list(
        method = "nlminb",
        starttests = FALSE,
        kkt = FALSE
      )
    )
  )
  
  print(summary(temp_mdl))
  cat(c(
    "\nperformance::check_singularity(temp_mdl) = ",
    check_singularity(temp_mdl, tolerance = 1e-05),
    "\n"
  ))
  
  drawResiduals(temp_mdl)
  
  anova(temp_mdl) %>% formattable(caption = "Anova of model")
  
  tidy(temp_mdl) %>%
    filter(effect == "fixed") %>%
    select(-c(group, effect)) %>%
    bonferroniAdjust(7, exclude_terms="fin_phonL%") %>%
    rename(`p.adj. (bf=7)` = p.adj) %>%
    mutate(
      estimate = round(estimate, 3),
      std.error = round(std.error, 3),
      statistic = round(statistic, 3)
      ) %>%
    rename(t.value = statistic) %>%
    formattable(caption = "Intercept and lh_slopes of fixed effects",
                list(`p.adj. (bf=7)` = formatter("span", style = p_color))) %>%
    mutate(
      p.value = if_else(
        p.value < 0.001,
        as.character(scientific(p.value), digits=2),
        as.character(round(p.value, 4), digits=2)
      ),
      `p.adj. (bf=7)` = if_else(
        `p.adj. (bf=7)` < 0.001,
        as.character(scientific(`p.adj. (bf=7)`, digits=2)),
        as.character(round(`p.adj. (bf=7)`, 4))
      )
    )
  
  print(
    kable(
      r2_nakagawa(temp_mdl),
      caption = "Conditional and marginal R^2^ of model",
      digits = 2,
      align = "l"
    )
  )
  
  
  print(
    plot_model(
      temp_mdl,
      title = cur_equation,
      show.intercept = FALSE,
      show.values = TRUE,
      vline.color = "red",
      colors = "Black"
    )
  )
  
  # Get intercepts and pairwise comparisons for each foot size condition.
  
  # Get number of levels in target treatment variable.
  cur_levels <- levels(m_corpus$mode)
  orig_levels <- cur_levels
  num_levels <- length(cur_levels)
  all_models_tidy = tibble()
  
  for (i in 1:(num_levels)) {
    # Test GLMM model on data.
    cur_model <- lmer(
      l_t ~ mode + gender + (1 + mode | speaker),
      data = m_corpus,
      control = lmerControl(
        optimizer = "optimx",
        calc.derivs = FALSE,
        optCtrl = list(
          method = "nlminb",
          starttests = FALSE,
          kkt = FALSE
        )
      )
    )
    # Convert the model output into a more readable format.
    cur_model_tidy <- tidy(cur_model) %>%
      filter(effect != "ran_pars") %>%
      select(-group) %>%
      bonferroniAdjust("", 5) %>%
      mutate(
        estimate = round(estimate, 3),
        std.error = round(std.error, 3),
        statistic = round(statistic, 3),
        p.value = round(p.value, 8),
        `p.adj. (bf=7)` = round(`p.adj. (bf=7)`, 8)
      )
    
    # Prepare current model for pasting to all models output.
    # Make 'pairwise' column = intercept.
    cur_model_tidy <- cur_model_tidy %>%
      mutate(
        pairwise =
          if_else(
            term == "(Intercept)",
            "intercept",
            if_else(
              term %notin% c("modeMDC",
                             "modeMWH",
                             "modeMYN",
                             "modeMDQ"),
              "N/A",
              paste("mode", cur_levels[1], sep = "") #???
            )
          ),
        # change 'term' so "intercept" states the target condition name.
        term =
          if_else(
            term == "(Intercept)",
            paste("mode", cur_levels[1], sep = ""),
            term
          )
      ) %>%
      # remove random effects detail
      filter(term != "sd__(Intercept)") %>%
      select(-effect) %>%
      # rename statistic column to "t.value"
      rename(t.value = statistic)
    
    
    # make list of pairwise comparisons to keeps
    keep = NULL
    for (j in i:4) {
      keep <- c(keep, paste("mode", orig_levels[j], sep = ""))
    }
    
    # remove pairwise comparisons which have already been done
    cur_model_tidy <- filter(cur_model_tidy, term %in% keep)
    
    # add remaining pairwise comparisons to main tibble.
    all_models_tidy <- bind_rows(all_models_tidy, cur_model_tidy)
    
    # restructure the order of levels for next LME cur_model.
    cur_levels <- c(cur_levels[2:num_levels], cur_levels[1])
    m_corpus <- m_corpus %>%
      mutate(mode = factor(mode,
                           levels = cur_levels))
  }
  
  # arrange tibble according to pairwise move it to first column position
  all_models_tidy  <- arrange(all_models_tidy, pairwise) %>%
    relocate(pairwise) %>%
    sigCodesTidy(`p.adj. (bf=7)`)
  
  # print b0 table
  filter(all_models_tidy, pairwise == "intercept") %>%
    select(-pairwise) %>%
    rename(intercept = term) %>%
    sigCodesTidy(`p.adj. (bf=7)`) %>% mutate(
        p.value = if_else(
          p.value < 0.001,
          as.character(scientific(p.value), digits=2),
          as.character(round(p.value, 4), digits=2)
        ),
        `p.adj. (bf=7)` = if_else(
          `p.adj. (bf=7)` < 0.001,
          as.character(scientific(`p.adj. (bf=7)`, digits=2)),
          as.character(round(`p.adj. (bf=7)`, 4))
        )
      )  %>%
      kable() %>% print()
    
  
    # print pairwise comparisons of (B1 table)
    filter(all_models_tidy, pairwise %notin% c("intercept", "N/A")) %>%
    select(pairwise,
           term,
           estimate,
           std.error,
           t.value,
           p.value,
           `p.adj. (bf=7)`) %>%
    rename(intercept = pairwise, slope = term) %>%
    sigCodesTidy(`p.adj. (bf=7)`) %>% mutate(
        p.value = if_else(
          p.value < 0.001,
          as.character(scientific(p.value), digits=2),
          as.character(round(p.value, 4), digits=2)
        ),
        `p.adj. (bf=7)` = if_else(
          `p.adj. (bf=7)` < 0.001,
          as.character(scientific(`p.adj. (bf=7)`, digits=2)),
          as.character(round(`p.adj. (bf=7)`, 4))
        )
      )  %>%
      kable() %>% print()
  
  
  
}



```





