---
title: "Chapter 7 - LME analysis of l_f0 ~ Mode"
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = F,
                      warning = F,
                      message = F)

# Load Functions.
source("../../2_R_Functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

```


```{r load corpus, include=F}
l_star_h_types = c("^[L*]H", "L*H", "L*^[H]", "^[L*H]")

# Load Corpus
m_corpus <- get_m_corpus("../../4_data/m_corpus.csv")  %>%
  # Select only columns for analysis
  select(
    speaker,
    gender,
    mode,
    prompt,
    acc_phon,
    fin_phon,
    l_f0) %>% 
  filter(acc_phon %in% l_star_h_types)  %>% 
  mutate(acc_phon = factor(acc_phon,
                           levels = l_star_h_types)
         )
```

- Using intercepts only model for parity with mode + acc_phon model 

```{r set equation and optimizer}
my_equation = formula(
  l_f0 ~ mode
  + (1 | speaker)
# + (1 | gender)
  + (1 | fin_phon)
# + (1 | prompt)
  )
optimizer = "optimx"
```


```{r run initial model,  fig.height=3, include=F, fig.width=9, tidy = TRUE}
l_f0_model <-
  lmer(
    my_equation,
    data = m_corpus,
    control = lmerControl(
      optimizer = optimizer,
      calc.derivs = F,
      optCtrl = list(
        method = "nlminb",
        starttests = F,
        kkt = F
      )
    )
  )

summariseLME(l_f0_model, run_step = TRUE)
```


```{r run trimmed models,  fig.height=3, fig.width=9, tidy = TRUE,}
l_f0_model <-
  lmer(
    my_equation,
    data = m_corpus,
    control = lmerControl(
      optimizer = optimizer,
      calc.derivs = F,
      optCtrl = list(
        method = "nlminb",
        starttests = F,
        kkt = F
      )
    )
  )

m_corpus.trimmed <- m_corpus %>% filter(abs(scale(resid(l_f0_model))) <= 3)

l_f0_model.trimmed <-
  lmer(
    my_equation,
    data = m_corpus.trimmed,
    control = lmerControl(
      optimizer = optimizer,
      calc.derivs = F,
      optCtrl = list(
        method = "nlminb",
        starttests = F,
        kkt = F
      )
    )
  )

    
summariseLME(l_f0_model.trimmed, run_step = TRUE
             , write="../output_model_anovas/Mode_l_f0_anova.csv"
             )
```


```{r make tidy model, fig.height=3.5, fig.width=7, results="asis"}

l_f0_model_trimmed.tidy <- analyseModel(l_f0_model.trimmed
                                        , write="../output/Mode_l_f0"
                                )
l_f0_model_trimmed.tidy$table
```

```{r do pairwise analysis}
# Get number of levels in target treatment variable.

charts <- getModelFixedFX(
  my_equation,
  my_data = m_corpus.trimmed,
  optimizer = optimizer
  , write="../output/Mode_l_f0"
)
charts$intercepts
charts$slopes %>% tidyStatNumbers()
```
