---
title: "Chapter 7 - LME Analysis of Utterance Slope"
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r message=FALSE, warning=TRUE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

# Load Functions.
source("../../functions/myFunctions.R")
```


```{r load packages etc., message=FALSE, warning=TRUE, include=FALSE}
# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "janitor",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

p_color <- all_models_tidy ~ style(color =
                                     if_else(as.double(all_models_tidy) < 0.05,
                                             "green",
                                             "red"))
```


```{r load corpus,  message=FALSE, warning=TRUE, include=FALSE}
# Load Corpus
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  select(speaker,
         gender,
         mode,
         acc_phon,
         phr_phon,
         fin_phon,
         utt_slope,
         prompt) %>%
  mutate(h_start =
           if_else(
             !is.na((str_extract(phr_phon, "%H|\\^\\[%H|% H\\*"))),
             T,
             F),
         h_start = factor(h_start, levels = unique(h_start)),
         # Remove register tier identifier from fin_phon.
         fin_phon = str_replace_all(fin_phon, "\\]", ""),
         fin_phon = factor(fin_phon, levels = unique(fin_phon))
)

```

- Include initial %H or % H* in model to mitigate against skewing effect of initial phonologically high f0
- Initial model has singularity issues
- Removing prompt gender from model
- Model word, but needs trimmed ()

```{r}
# set current equation
cur_equation  <-
  "utt_slope ~ mode + h_start +
   (1 | acc_phon) + (1 + mode | speaker) + (1 | fin_phon) + (1 | prompt)"

```

```{r fig.height=3, fig.width=9, tidy = TRUE}
# set recommended equation
utt_slope_mdl  <-  lmer(cur_equation,
  data = m_corpus,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

# model needs trimming
m_corpus.trimmed <- m_corpus %>% filter(abs(scale(resid(utt_slope_mdl))) <= 2.5)


utt_slope_mdl.trimmed  <-  lmer(cur_equation,
  data = m_corpus.trimmed,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

summariseLME(utt_slope_mdl.trimmed, run_step = TRUE,
              write="../output_model_anovas/utt_slope_anova.csv")
```

```{r fig.height=2.5, fig.width=5, results="asis"}
utt_utt_slope.tidy <- analyseModel(
  utt_slope_mdl.trimmed,
  write="../output/utt_slope"
  )
utt_utt_slope.tidy$table
```
```{r random effect of prompt, fig.height=2, fig.width=5}
plot_model(utt_slope_mdl.trimmed,
           type="re",
           axis.title = c("semitones", "prompt"),
           title="random effect",
           show.values = T)[2:4]
```


```{r slopes}
# Get number of levels in target treatment variable.

charts <- getModelFixedFX(
  my_equation = cur_equation,
  my_data = m_corpus.trimmed,
  write="../output/utt_slope"
)
charts$intercepts
charts$slopes

```
