---
title: "Can foot size be used as a predictory of boundary tone? A Generalised Linear Mixed Effects Model Analysis of Footsize effect on final boundaries"
author: "AERodgers"
date: "2/18/2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r message=FALSE, warning=FALSE, include=FALSE}
# Get personal functions and install / load necessary packages.
source("../functions/myFunctions.R")

installMissingPackages(
  c(
    # Include statistical packages.
    "lmerTest",
    "optimx",
    "MuMIn",
    
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",

    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)



# Get data frames for AH analysis
source("get_AH_corpora.R")

# trim nuc_foot tbls
nuc_foot <- select(nuc_foot,
                   speaker,
                   gender,
                   stim,
                   foot_syls,
                   fin_phon,
                   speech_rate) %>%
  mutate(
    fin_phon = factor(fin_phon, levels = unique(fin_phon)),
    foot_syls = factor(foot_syls,
                       levels = c(1, 2, 3, 4))
  )

# set colours and themes
theme_set(theme_minimal(base_size = 14))

p_color <- x ~ style(color = if_else(x < 0.05,
                                     "green",
                                     "red"))


```


## **NUCs** as fn of **foot size**
```{r echo=FALSE, warning=FALSE}
# Run GLME model statistical cur_model.
cur_model <- glmer(
  fin_phon ~ foot_syls + (1 | speaker),
  data = nuc_foot,
  family = binomial(link = "logit"),
  # change optimizer to avoid convergence errors
  control = glmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

null_model <- glmer(
  fin_phon ~ 1 + (1 | speaker),
  data = nuc_foot,
  family = binomial(link = "logit"),
  # change optimizer to avoid convergence errors
  control = glmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

```

### Anova comparison of current model with null equivalent.

```{r echo=FALSE, warning=FALSE}
formattable(tidy(anova(cur_model, null_model, test="Chisq")))
formattable(r.squaredGLMM(cur_model))

tidy_model <- tidy(cur_model) %>%
  filter(term != "sd_(Intercept).speaker") %>%
   bonferroniAdjust("", 4) %>%
    mutate(
      estimate = round(estimate, 3),
      std.error = round(std.error, 3),
      statistic = round(statistic, 3),
      p.value = round(p.value, 4),
      p.adjusted = round(p.adjusted, 4)
    )

plot_model(
  cur_model,
  axis.lim = c(0.01, max(tidy_model$estimate)*10),
  show.intercept = TRUE,
  show.values = TRUE,
  show.p = FALSE,
  title = "fin_phon ~ foot size + (1 | speaker)",
  vline.color = "red",
  colors = "Black"
) +
  font_size(title = 12)

formattable(tidy_model,
            list(p.adjusted = formatter("span",
                                     style = p_color)))

```

## pairwise comparisons
```{r echo=FALSE, paged.print=FALSE, warning=FALSE}
# Get intercepts and pairwise comparisons for each foot size condition
# by running

# Get number of levels in target treatment variable.
curLevels <- levels(pn_foot$foot_syls)
numLevels <- length(curLevels)
all_models_tidy = tibble()

for (i in 1:(numLevels)) {
  # print current intercept.
  cat(
    c("\n\nStatistical Model with foot_syls[", curLevels[1], "] as intercept"),
    sep = ""
    )
  
  # Run GLMM test on data
  cur_model <- glmer(
    fin_phon ~ foot_syls + (1 | speaker),
    data = nuc_foot,
    family = binomial(link = "logit"),
    # change optimizer to avoid convergence errors
    control = glmerControl(
      optimizer = "optimx",
      calc.derivs = FALSE,
      optCtrl = list(
        method = "nlminb",
        starttests = FALSE,
        kkt = FALSE
      )
    )
  )

  # Convert the model output into a more readable format.
  cur_model_tidy <- tidy(cur_model) %>%
   bonferroniAdjust("", 8) %>%
    mutate(
      estimate = round(estimate, 3),
      std.error = round(std.error, 3),
      statistic = round(statistic, 3),
      p.value = round(p.value, 4),
      p.adjusted = round(p.adjusted, 4)
    )
  
  # Output current model
  print(kable(
    cur_model_tidy %>%
      select(-c(group, effect)) %>%
      mutate(
        z_value = statistic,
        .before = p.value,
        .keep = "unused"
      )
  ))
  
  # Create visualization of model the first time the loop runs
  print(
    plot_model(
      axis.lim = c(0.01, 500),
      cur_model,
      show.intercept = TRUE,
      show.values = TRUE,
      show.p = FALSE,
      title = paste("fin_phon ~ foot size + (1 | speaker), intercept = foot_syls", i, sep =
                      ""),
      wrap.title = 150,
      vline.color = "red",
      colors = "Black"
    ) +
      font_size(title = 12)
  )
  
  # Prepare current model for pasting to all models output
  # make pairwise column = intercept
  cur_model_tidy <- cur_model_tidy %>%
    mutate(
      pairwise =
        if_else(
          term == "(Intercept)",
          "intercept",
          if_else(
            term %notin% c(
              "foot_syls1", "foot_syls2", "foot_syls3", "foot_syls4"
              ),
            "N/A",
            paste("foot_syls", i, sep = "")
          )
        ),
      # change term so "intercept" states the target condition name.
      term =
        if_else(term == "(Intercept)",
                paste("foot_syls", i, sep = ""),
                term)
    ) %>%
    # remove random effects detail
    filter(term != "sd__(Intercept)") %>%
    select(-group,-effect) %>%
    # rename statistic column to "z.value"
    rename(z.value = statistic)
  
  
  # make list of pairwise comparisons to keeps
  keep = ""
  for (j in i:4) {
    keep <- c(keep, paste("foot_syls", j, sep = ""))
  }
  # remove pairwise comparisons which have already been done
  cur_model_tidy <- filter(cur_model_tidy, term %in% keep)
  
  # add remaining pairwise comparisons to main tibble.
  all_models_tidy <- bind_rows(all_models_tidy, cur_model_tidy)
  
  # restructure the order of levels for next GLME cur_model.
  curLevels <- c(curLevels[2:numLevels], curLevels[1])
  nuc_foot <- nuc_foot %>%
    mutate(foot_syls = factor(foot_syls,
                              levels = curLevels))
  
}

# arrange tibble according to pairwise move it to first column position
all_models_tidy  <- arrange(all_models_tidy, pairwise) %>%
  relocate(pairwise) %>%
  sigCodesTidy()


b0_footSize  <- filter(all_models_tidy, pairwise == "intercept") %>%
  select(-pairwise) %>%
  rename(intercept = term) %>%
  sigCodesTidy()


b1_footSize  <-
  filter(all_models_tidy, pairwise %notin% c("intercept", "N/A")) %>%
  select(pairwise,
         term,
         estimate,
         std.error,
         z.value,
         p.value,
         p.adjusted) %>%
  rename(intercept = pairwise, slope = term) %>%
  sigCodesTidy()

```


#### Foot size as intercept ($\beta$~0~)
```{r echo=FALSE, warning=FALSE}
formattable(b0_footSize,
            list(p.adjusted = formatter("span",
                                     style = p_color
                                     )
                 )
            )

```


#### Pairwise comparisons ($\beta$~1~)
```{r echo=FALSE, warning=FALSE}
formattable(b1_footSize,
            list(p.adjusted = formatter("span",
                                     style = p_color
                                     )
                 )
            )
```

