---
title: "Chapter 7 - Analysis of Utterance mean f0 and lh_slope of linear regression"
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}

# Load Functions.
source("../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

mode_colours <- c("MWH" = "#e41a1c",
                  "MDC" = "#377eb8",
                  "MYN" = "#4daf4a",
                  "MDQ" = "#984ea3")

pitch_accent_colours <- c("H*"     = brewer.pal(6, "Spectral")[4],
                          "L*H"    = brewer.pal(6, "Spectral")[6],
                          ">H*"    = brewer.pal(6, "Spectral")[5],
                          "^[L*]H" = brewer.pal(6, "Spectral")[3],
                          "L*^[H]" = brewer.pal(6, "Spectral")[2],
                          "^[L*H]" = brewer.pal(6, "Spectral")[1])

p_color <- all_models_tidy ~ style(color =
                                     if_else(as.double(all_models_tidy) < 0.05,
                                             "green",
                                             "red")
                                   )


```

```{r}
# Load Corpus
m_corpus <- get_m_corpus("data/m_corpus.csv")  %>%
  # Consolidate nuc_contour based on observation and types of register shift.
  mutate(
    nuc_contour =
      if_else(
        nuc_contour == "^[L*H %]" | nuc_contour == "^[L*H L%]",
        "^[L*H] %",
        if_else(nuc_contour == "L*^[H L%]", "L*^[H] %", nuc_contour)
      ),
    acc_phon =
      factor(
        str_replace(nuc_contour,
                    "\\s%$|\\sL%$",
                    ""),
        levels = c("H*", "L*H", ">H*", "^[L*]H", "L*^[H]", "^[L*H]")
      ),
    fin_phon = str_replace_all(fin_phon, "L%]|%]", "%")
  ) %>%
  # Select only columns for analysis
  select(
    speaker,
    gender,
    mode,
    nuc_contour,
    acc_phon,
    fin_phon,
    
    utt_mean_f0,
    utt_lh_slope,
    
    lh_mean_f0,
    lh_slope,
    
    utt_mean_f0_z,
    utt_lh_slope_z,

    lh_mean_f0_z,
    lh_slope_z,
    
    l_f0_z,
    h_f0_z

  )

```

Density plot of mode by lh contour mean f0 and lh_slope

```{r, fig.width=4, fig.height=3}
ggplot(m_corpus %>% filter(mode %in% c("MDC", "MDQ")),
       aes(y = lh_mean_f0_z, x = lh_slope, color = mode)) +
  geom_point() +
  geom_density_2d() +
  scale_color_manual(values = mode_colours) +
  xlim(-20, 100) +
  ylim(-3, 3)

ggplot(
  m_corpus %>% filter(mode %in% c("MDC", "MDQ"), speaker != "F16"),
  aes(y = lh_mean_f0_z, x = lh_slope, color = mode)
) +
  geom_point() +
  geom_density_2d() +
  scale_color_manual(values = mode_colours) +
  xlim(-20, 100) +
  ylim(-3, 3)


```

Density plot of mode by utterance contour

```{r, fig.width=4, fig.height=3}
ggplot(m_corpus %>% filter(mode %in% c("MDC", "MDQ")),
       aes(y = utt_mean_f0_z, x = utt_lh_slope, color = mode)) +
  geom_point() +
  geom_density_2d() +
  scale_color_manual(values = mode_colours) +
  xlim(-20, 20) +
  ylim(-3, 3)

ggplot(
  m_corpus %>% filter(mode %in% c("MDC", "MDQ"), speaker != "F16"),
  aes(y = utt_mean_f0_z, x = utt_lh_slope, color = mode)
) +
  geom_point() +
  geom_density_2d() +
  scale_color_manual(values = mode_colours) +
  xlim(-20, 20) +
  ylim(-3, 3)

```

Density plot of PAs by lh mean f0 and lh_slope

```{r, fig.width=4, fig.height=3}

m <- manova(cbind(lh_mean_f0_z, lh_slope) ~ mode,
            data = m_corpus
            )

print(summary(m))

m <- manova(cbind(lh_mean_f0_z, lh_slope) ~ mode,
            data = m_corpus %>% 
              filter(mode %in% c("MDC", "MDQ")))

print
print(summary(m))

```

