---
title: "Chapter 7 - LME Analysis of Utterance mean f0 - mode and phonology"
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r message=F, warning=T, include=F}
knitr::opts_chunk$set(echo = F,
                      warning = F,
                      message = F)

# Load Functions.
source("../../2_R_Functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "stringr",
    "broomExtra",
    "janitor",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

p_color <- all_models_tidy ~ style(color =
                                     if_else(as.double(all_models_tidy) < 0.05,
                                             "green",
                                             "red"))
```


```{r load corpus, include=F}
# Load Corpus
m_corpus <- get_m_corpus("../../4_data/m_corpus.csv")  %>%
  select(speaker,
         mode,
         utt_mean_f0,
         phr_phon,
         acc_phon,
         fin_phon,
         prompt) %>%
  mutate(h_start =
           if_else(
             !is.na((str_extract(phr_phon, "%H|\\^\\[%H|% H\\*"))),
             "H start",
             "no H start"),
         h_start = factor(h_start, levels = c("H start","no H start")),
         fin_phon = factor(str_replace_all(fin_phon, "\\^|\\[|\\]", ""),
                           levels=c("%", "L%")
           
         ))

```


### LME model analysis using initial model
```{r}
# set current equation
cur_equation  <- formula(
  utt_mean_f0  ~ mode
  + (1 + mode | speaker)
  + (1 | prompt)
  + (1 | h_start)
  + (1 | acc_phon)
  + (1 | fin_phon)
  )

```

```{r fig.height=3, fig.width=9, message = F, tidy = T}
utt_mean_f0_mdl = lmer(
  formula(cur_equation),
  data = m_corpus,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = F,
    optCtrl = list(
      method = "nlminb",
      starttests = F,
      kkt = F
    )
  )
)


summariseLME(utt_mean_f0_mdl, run_step = T,
              write="../output_model_anovas/utt_f0_full_phon_anova.csv")
```

```{r random effect 1, fig.height=4, fig.width=8}
plot_model(utt_mean_f0_mdl,
           type="re",
           vline.color = "red",
           show.values = T)[1]
```
```{r random effect 2, fig.height=4, fig.width=8}
plot_model(utt_mean_f0_mdl,
           type="re",
           vline.color = "red",
           show.values = T)[2]
```

```{r random effect 3, fig.height=2, fig.width=8}
plot_model(utt_mean_f0_mdl,
           type="re",
           vline.color = "red",
           show.values = T)[3:5]
```

```{r fig.height=2.5, fig.width=6, results="asis"}
utt_mean_f0.tidy <- analyseModel(
  utt_mean_f0_mdl,
  write="../output/utt_f0_full_phon"
)
utt_mean_f0.tidy$table
```


```{r slopes}
# Get number of levels in target treatment variable.

charts <- getModelFixedFX(
  my_equation = cur_equation,
  my_data = m_corpus,
  write="../output/utt_f0_full_phon"
)

charts$intercepts
charts$slopes

```
