---
title: "LME Analysis of PNs - alternative models for h_t and h_f0"
author: "Antoin Rodgers"
date: "18.05.2022"
output:
  html_document: default
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = F,
                      message = F,
                      warning = F)

## Get personal functions and install / load necessary packages.
source("../../2_R_Functions/myFunctions.R")

installMissingPackages(
  c(
    ## Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "ggeffects",
    "optimx",
    "MuMIn",
    "dfoptim",

    ## Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",

    ## Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

## Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

## Get  data for analysis

source("../0_get_AH.R")

h_star_type <-  c("L*H", ">H*", "H*")
pn_h_data <- pn %>%

  mutate(stress_clash = factor((foot_syls == 1), levels = c(F, T)))  %>%
  filter(acc_phon %in% h_star_type)

rm(pn, nuc, nuc_foot, pn_lex, pn_ana, pn_foot, corpus, nuc_pre, stress)


```


### H targets and stress clash

#### Analysis of H timing and stress clash

```{r set h_t equation}
h_t_equation = formula(
  h_t ~
  stress_clash
  + acc_phon
  + (1 + stress_clash | speaker)
  + (1 | gender)
  + (1 | pn_str_syl)
)

optimizer = "optimx"
```

```{r run h_t models, fig.height=3, fig.width=9}
pn_h_t_alt_mdl = lmer(
  h_t_equation,
  pn_h_data,
  control = lmerControl(
    optimizer = optimizer,
    calc.derivs = F,
    optCtrl = list(
      method = "nlminb",
      starttests = F,
      kkt = F
    )
  )
)

pn_h_t_alt_mdl <-
  optimizeModel(pn_h_t_alt_mdl, reject_nm = T, verbose = F)

mdl_summary <- summariseLME(pn_h_t_alt_mdl,
                  run_step = F, print_summary = F
                  )

## model needs trimming
pn_h_t_alt.trimmed <-
  pn_h_data %>% filter(abs(scale(resid(pn_h_t_alt_mdl))) <= 2.5)

pn_h_t_alt_mdl.trimmed = update(pn_h_t_alt_mdl, data = pn_h_t_alt.trimmed,
                                control = lmerControl(
                                  optimizer = "nloptwrap",
                                  optCtrl = list(
                                    algorithm = "NLOPT_LN_PRAXIS",
                                    maxfun = 1e9,
                                    maxeval = 1e7,
                                    xtol_abs = 1e-9,
                                    ftol_abs = 1e-9)))
pn_h_t_alt_mdl.trimmed <-
  optimizeModel(pn_h_t_alt_mdl.trimmed, reject_nm = T, verbose = F)
tibble(`Summary of model` = getModelFormula(pn_h_t_alt_mdl.trimmed)) %>%
          formattable(align = "l")

mdl_summary <- summariseLME(pn_h_t_alt_mdl.trimmed,
                  run_step = F,
                  write = "4_pn_output/pn_h_t_alt_anova.csv"
  )

adjustP_posthoc("4_pn_output/",
                p.value,
                suffix_id = "_anova")

read_csv("4_pn_output/pn_h_t_alt_anova.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_h_t_alt_mdl.trimmed)))

pn_h_t_alt_mdl.trimmed %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  select (-group, - effect) %>%
  tidyNumbers() %>%  
  rename(t.value = statistic) %>% 
  formattable()
```

```{r h_t model summary, fig.height=2.5, fig.width=2.823, results="asis"}
mdl_summary$omega2

pn_h_t_alt_mdl.tidy <- analyseModel(
  pn_h_t_alt_mdl,
  write = "4_pn_output/pn_h_t_alt",
  type = "pred",
  y_lab = "time (ms)",
  hjust = 1.5,
  y_lim = c(-100, 350),
  breaks = seq(-100, 350, 100),
  plot_rounding =  0)

pn_h_t_alt_mdl.tidy$table %>% tidyStatNumbers()
```

```{r do h_t pairwise analysis, results = "asis"}
printTidyPredictions(pn_h_t_alt_mdl.trimmed)
charts <- getModelFixedFX(pn_h_t_alt_mdl.trimmed)
charts$slopes %>% tidyStatNumbers() %>% 
  mutate(across(
          any_of(c("estimate", "conf.low", "conf.high")),
          ~ round(as.numeric(.),0)))
```

#### Analysis of H F0 and stress clash

```{r set h_f0 equation}
h_f0_equation = formula(
  h_f0 ~
  stress_clash
  + (1 + stress_clash | speaker)
  + (1 | gender)
  + (1 | pn_str_syl)
)

optimizer = "optimx"
```

```{r run h_f0 models, fig.height=3, fig.width=9}
pn_h_f0_alt_mdl = lmer(
  h_f0_equation,
  pn_h_data,
  control = lmerControl(
    optimizer = optimizer,
    calc.derivs = F,
    optCtrl = list(
      method = "nlminb",
      starttests = F,
      kkt = F
    )
  )
)

pn_h_f0_alt_mdl <-
  optimizeModel(pn_h_f0_alt_mdl, reject_nm = T, verbose = F)


pn_h_f0_alt.trimmed <-
  pn_h_data %>% filter(abs(scale(resid(pn_h_f0_alt_mdl))) <= 2.75)

pn_h_f0_alt_mdl.trimmed = update(pn_h_f0_alt_mdl, data = pn_h_f0_alt.trimmed)

mdl_summary <- summariseLME(run_step = F,
                  pn_h_f0_alt_mdl.trimmed,
                  write = "4_pn_output/pn_h_f0_alt_anova.csv")

adjustP_posthoc("4_pn_output/",
                p.value,
                suffix_id = "_anova")

read_csv("4_pn_output/pn_h_f0_alt_anova.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_h_f0_alt_mdl)))


```

```{r h_f0 model summary, fig.height=2.5, fig.width=2.823, results="asis"}
pn_h_f0_alt_mdl.tidy <- analyseModel(
  pn_h_f0_alt_mdl,
  write = "4_pn_output/pn_h_f0_alt",
  type = "pred",
  y_lab = "f0 (ST re speaker median)",
  hjust = 1.5,
  y_lim = c(-3, 4.5),
  breaks = seq(-3, 4.5, 1),
  plot_rounding =  1
)
pn_h_f0_alt_mdl.tidy$table %>% tidyStatNumbers()


```

```{r do h_f0 pairwise analysis, results = "asis"}
printTidyPredictions(pn_h_f0_alt_mdl)
```

### Analysis of PN peak timing by individual acc_phon

```{r acc_phon by ana_syls}
pn_h_data %>%
  group_by(acc_phon, ana_syls) %>%
  mutate(acc_phon = str_replace_all(acc_phon, "([\\*\\[\\^\\>])", "\\\\\\1")) %>% 
  summarise(acc_count = n(), .groups = "keep") %>%
  pivot_wider(names_from = "acc_phon",
              values_from = acc_count,
              values_fill = 0) %>% 

  formattable(caption = "acc\\_phon by ana\\_syls in pn\\_h_\\t.trimmed")
```

#### Analysis of PN peak timing in L*H only


```{r run h_t_lh models, fig.height=3, fig.width=9}
h_t_equation = formula(
  h_t ~
    ana_syls
  + (1 | speaker)
  + (1 | foot_syls)
  + (1 | gender)
  + (1 | pn_str_syl)
)
optimizer = "optimx"
pn_h_data_lh <- pn_h_data %>%
  filter (acc_phon == "L*H") %>%
  mutate(has_ana = factor(ana_syls != 0, levels = c(F, T)))

pn_h_t_lh_mdl = lmer(
  h_t_equation,
  pn_h_data_lh ,
  control = lmerControl(
    optimizer = optimizer,
    calc.derivs = F,
    optCtrl = list(
      method = "nlminb",
      starttests = F,
      kkt = F
    )
  )
)

pn_h_t_lh_mdl <- optimizeModel(pn_h_t_lh_mdl, reject_nm = T)
mdl_summary <- summariseLME(pn_h_t_lh_mdl,
                  run_step = T, print_summary = F
                  )

## model needs trimming

pn_h_t_lh_mdl.trimmed = update(pn_h_t_lh_mdl, data = pn_h_data_lh %>%
                                 filter(abs(scale(resid(pn_h_t_lh_mdl))) <= 3))
pn_h_t_lh_mdl.trimmed <-  optimizeModel(pn_h_t_lh_mdl.trimmed, reject_nm = T)


tibble(`Summary of model` = getModelFormula(pn_h_t_lh_mdl.trimmed)) %>%
          formattable(align = "l")

mdl_summary <- summariseLME(pn_h_t_lh_mdl.trimmed,
                  run_step = F,
                  write = "4_pn_output/pn_h_t_lh_anova.csv"
  )

adjustP_posthoc("4_pn_output/",
                p.value,
                suffix_id = "_anova")

read_csv("4_pn_output/pn_h_t_lh_anova.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_h_t_lh_mdl.trimmed)))
```


```{r h_t_lh model summary, fig.height=2.5, fig.width=2.823, results="asis"}
mdl_summary$omega2

pn_h_t_lh_mdl.tidy <- analyseModel(
  pn_h_t_lh_mdl.trimmed,
  write="4_pn_output/pn_h_t_lh",
  type = "pred",
  y_lab = "time (ms)",
  y_lim = c(-100, 350),
  breaks = seq(-100, 350, 100),
  plot_rounding = 0,
  hjust = 1,
  caption_prefix = "A. L*H-only: ",
  short_caption = T)

```

```{r do h_t_lh pairwise analysis, fig.height=2.5, fig.width=2.823, results = "asis"}
printTidyPredictions(pn_h_t_lh_mdl.trimmed)

charts <-
  getModelFixedFX(pn_h_t_lh_mdl.trimmed, 
                  write="4_pn_output/pn_h_t_lh"
                  )
charts$slopes %>% tidyStatNumbers() %>% 
  mutate(across(
          any_of(c("estimate", "conf.low", "conf.high")),
          ~ round(as.numeric(.),0)))
```

#### Analysis of PN peak timing in H* only

```{r run h_t_h models, fig.height=3, fig.width=9}
h_t_h_equation = formula(
  h_t ~
    ana_syls
  + (1 | speaker)
  + (1 | gender)
  + (1 | foot_syls)
  + (1 | pn_str_syl)
)
optimizer = "optimx"
pn_h_data_h <- pn_h_data %>%
  filter (acc_phon == "H*") %>%
  mutate(has_ana = factor(ana_syls != 0, levels = c(F, T)))

pn_h_t_h_mdl = lmer(
  h_t_h_equation,
  pn_h_data_h ,
  control = lmerControl(
    optimizer = optimizer,
    calc.derivs = F,
    optCtrl = list(
      method = "nlminb",
      starttests = F,
      kkt = F
    )
  )
)

pn_h_t_h_mdl <- optimizeModel(pn_h_t_h_mdl, reject_nm = T)
mdl_summary <- summariseLME(pn_h_t_h_mdl,
                  run_step = F, print_summary = F
                  )

## model needs trimming

pn_h_t_h_mdl.trimmed = update(pn_h_t_h_mdl, data = pn_h_data_h %>%
                                 filter(abs(scale(resid(pn_h_t_h_mdl))) <= 3))
pn_h_t_h_mdl.trimmed <-  optimizeModel(pn_h_t_h_mdl.trimmed, reject_nm = T)


tibble(`Summary of model` = getModelFormula(pn_h_t_h_mdl.trimmed)) %>%
          formattable(align = "l")

mdl_summary <- summariseLME(pn_h_t_h_mdl.trimmed,
                  run_step = F,
                  write = "4_pn_output/pn_h_t_h_anova.csv"
  )

adjustP_posthoc("4_pn_output/",
                p.value,
                suffix_id = "_anova")

read_csv("4_pn_output/pn_h_t_h_anova.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_h_t_h_mdl.trimmed)))
```


```{r h_t_h model summary, fig.height=2.5, fig.width=2.823, results="asis"}
mdl_summary$omega2

pn_h_t_mdl.tidy <- analyseModel(
  pn_h_t_h_mdl.trimmed,
  write="4_pn_output/pn_h_t_h",
  type = "pred",
  y_lab = "time (ms)",
  y_lim = c(-100, 350),
  breaks = seq(-100, 350, 100),
  plot_rounding = 0,
  hjust = 1,
  caption_prefix = "B. H*-only: ",
  short_caption = T)

```

```{r do h_t_h pairwise analysis, fig.height=2.5, fig.width=2.823, results = "asis"}
printTidyPredictions(pn_h_t_h_mdl.trimmed)

charts <-
  getModelFixedFX(pn_h_t_h_mdl.trimmed, 
                  write="4_pn_output/pn_h_t_h"
                  )
charts$slopes %>% tidyStatNumbers() %>% 
  mutate(across(
          any_of(c("estimate", "conf.low", "conf.high")),
          ~ round(as.numeric(.),0)))
```


#### Analysis of PN Peak timing proportional to foot
```{r  h_t_re_ft_dur, fig.height=3, fig.width=9}
h_t_re_ft_dur_equation = formula(
  `h_t as ratio of foot` ~ 
    foot_syls
  + (1 | speaker)
  + (1 | gender)
  + (1 | ana_syls)
  #+ (1 | pn_new_word)
  + (1 | pn_str_syl)
  + (1 | wrd_end_syl)
)

optimizer = "optimx"

pn_h_data_lh <- pn_h_data %>%
  mutate(`h_t as ratio of foot` = h_t_foot_ratio)  %>% 
  filter(acc_phon == "L*H")

pn_h_t_re_ft_dur_mdl = lmer(
  h_t_re_ft_dur_equation,
  pn_h_data_lh,
  control = lmerControl(
    optimizer = optimizer,
    calc.derivs = F,
    optCtrl = list(
      method = "nlminb",
      starttests = F,
      kkt = F
    )
  )
)
  


pn_h_t_re_ft_dur_mdl <- pn_h_t_re_ft_dur_mdl %>% optimizeModel()
 mdl_summary <- summariseLME(pn_h_t_re_ft_dur_mdl,
             run_step = F,
             print_summary = F
             )


 pn_h_t_re_ft_dur_mdl.trimmed = lmer(
   pn_h_t_re_ft_dur_mdl,
   data = pn_h_data_lh %>%
     filter(abs(scale(
       resid(pn_h_t_re_ft_dur_mdl)
     )) <= 2.5),
   control = lmerControl(
     optimizer = optimizer,
     calc.derivs = F,
     optCtrl = list(
       method = "nlminb",
       starttests = F,
       kkt = F
     )
   )
 )
 pn_h_t_re_ft_dur_mdl.trimmed <- pn_h_t_re_ft_dur_mdl.trimmed %>% optimizeModel()
 
 
 mdl_summary <- summariseLME(pn_h_t_re_ft_dur_mdl.trimmed,
                             run_step = F,
                             write = "4_pn_output/pn_h_t_re_ft_dur_anova.csv")


adjustP_posthoc("4_pn_output/",
                p.value,
                suffix_id = "_anova")

read_csv("4_pn_output/pn_h_t_re_ft_dur_anova.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_h_t_re_ft_dur_mdl.trimmed)))

```

```{r h_t_re_ft_dur model analysis, fig.height=2.5, fig.width=2.823, results="asis"}
mdl_summary$omega2

pn_h_t_re_ft_dur_mdl.tidy <- analyseModel(pn_h_t_re_ft_dur_mdl.trimmed,
                                write="4_pn_output/pn_h_t_re_ft_dur",
                                type = "pred",
                                y_lab = "time (proportion)",
                                y_lim = c(0, 1.2),
                                breaks = seq(0, 1.2, 0.2),
                                plot_rounding = 2,
                                caption_prefix = "letters"
                                )

printTidyPredictions(pn_h_t_re_ft_dur_mdl.trimmed)
charts <- getModelFixedFX(pn_h_t_re_ft_dur_mdl.trimmed,
                          write = "4_pn_output/pn_h_t_re_ft_dur_mdl")
charts$slopes %>% tidyStatNumbers() %>% 
  mutate(across(any_of(c("estimate", "conf.low", "conf.high")),
  ~ round(as.numeric(.), 2)))
```
