---
title: "Chapter 7 - LME analysis of f0_exc ~ acc_phon"
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE
                      #, warning=FALSE
                      #, message=FALSE
                      )

# Load Functions.
source("../../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

```


```{r load corpus}
l_star_h_types = c("L*H", "^[L*]H", "L*^[H]", "^[L*H]")

# Load Corpus
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  # Consolidate nuc_contour based on observation and types of register shift.
  mutate(
    acc_phon =
      factor(
        str_replace(nuc_contour,
                    "\\s%$|\\sL%$",
                    ""),
        levels = c("H*", "L*H", ">H*", "^[L*]H", "L*^[H]", "^[L*H]")
      ),
    fin_phon = factor(fin_phon, levels=unique(fin_phon))
  ) %>%
  # Select only columns for analysis
  select(
    speaker,
    gender,
    mode,
    prompt,
    nuc_contour,
    acc_phon,
    fin_phon,
    f0_exc) %>% 
  filter(acc_phon %in% l_star_h_types)  %>% 
  mutate(acc_phon = factor(acc_phon,
                           levels = l_star_h_types)
         )

```

```{r run initial model,  fig.height=3, fig.width=9, eval=FALSE}
# run model
f0_exc_model <-
    lmer(
        f0_exc ~ acc_phon + (1 | fin_phon) + (1 | gender) +
          (1 + acc_phon | speaker) + (1| prompt),
        data = m_corpus,
        control = lmerControl(
            optimizer = "optimx",
            calc.derivs = FALSE,
            optCtrl = list(
                method = "nlminb",
                starttests = FALSE,
                kkt = FALSE
            )
        )
      )

summariseLME(f0_exc_model, run_step=TRUE) %>% print()
```
-   Convergence and singularity issues (with bobyqa and omptimx).
-   Running model again without (1|prompt).
-   Model only works with random intercepts only model without (1| prompt)

#### `f0_exc ~ acc_phon + (1 | acc_phon) + (1 | speaker) + (1| gender)`

```{r run model w/o gender,  fig.height=3, fig.width=9}
# run model
f0_exc_model <-
    lmer(
        f0_exc ~ acc_phon + (1 | acc_phon) + (1 | speaker),
        data = m_corpus,
        control = lmerControl(
            optimizer = "optimx",
            calc.derivs = FALSE,
            optCtrl = list(
                method = "nlminb",
                starttests = FALSE,
                kkt = FALSE
                )
            )
        )

summariseLME(f0_exc_model, run_step=TRUE,
             write="../output_model_anovas/acc_phon_f0_exc_anova.csv")

```

```{r make tidy model, fig.height=3, fig.width=9, results="asis"}
f0_exc_model.tidy <- analyseModel(f0_exc_model,
                                  write = "../output/acc_phon_f0_exc"
                                  )

f0_exc_model.tidy$r2

```


```{r do pairwise analysis, fig.height=3, fig.width=9}

charts <- getModelFixedFX(
  my_equation = f0_exc ~ acc_phon + (1 | acc_phon) + (1 | speaker) + (1| gender),
  my_data = m_corpus,
  write="../output/acc_phon_f0_exc"
)
charts$intercepts
charts$slopes


```
