---
title: "Chapter 7 - LME analysis of h_t ~ Mode and Nuclear pitch accents: "
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = TRUE)

# Load Functions.
source("../../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

# Load Corpus
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  # Consolidate nuc_contour based on observation and types of register shift.
  mutate(
    nuc_contour =
      if_else(
        nuc_contour == "^[L*H %]" | nuc_contour == "^[L*H L%]",
        "^[L*H] %",
        if_else(nuc_contour == "L*^[H L%]", "L*^[H] %", nuc_contour)
      ),
    acc_phon =
      factor(
        str_replace(nuc_contour,
                    "\\s%$|\\sL%$",
                    ""),
        levels = c("H*", "L*H", ">H*", "^[L*]H", "L*^[H]", "^[L*H]")
      ),
    fin_phon = str_replace_all(fin_phon, "L%]|%]", "%")
  ) %>%
  # Select only columns for analysis
  select(
    speaker,
    gender,
    mode,
    prompt,
    acc_phon,
    fin_phon,
    h_t
  ) %>% 
  # keep only explicitly LH pitch accents.
  filter(acc_phon %notin% c("H*", ">H*")) %>%
  mutate(acc_phon = factor(acc_phon,
                           levels = c("L*H", "^[L*]H", "L*^[H]", "^[L*H]")))
```

The aims of this set of analyses is to see if, once we account for assumed speaker-motivated use of pitch accent, the apparent "paralinguistic" differences in scaling (and possibly time) of phonetic parameters disappear.

```{r run initial model,  fig.height=3, fig.width=9, message = FALSE, tidy = TRUE}

# run model
h_t_model <-
  lmer(h_t ~ mode*acc_phon + fin_phon +
         (1 + mode + acc_phon | speaker) + (1 | prompt),
       data = m_corpus,
        control = lmerControl(
          optimizer = "optimx",
          calc.derivs = FALSE,
          optCtrl = list(
            method = "nlminb",
            starttests = FALSE,
            kkt = FALSE
          )
        )
      )


summarise_lme(h_t_model, run_step=TRUE)

```

-   Singularity error!
-   Step suggests no interactions and intercepts only model.
-   Running Step model

```{r run intercepts only model,  fig.height=3, fig.width=9, message = FALSE, tidy = TRUE}

h_t_model_reduced <-  lmer(h_t ~ mode + acc_phon + fin_phon +
                            (1 | prompt) + (1 | speaker),
       data = m_corpus,
        control = lmerControl(
          optimizer = "optimx",
          calc.derivs = FALSE,
          optCtrl = list(
            method = "nlminb",
            starttests = FALSE,
            kkt = FALSE
          )
        )
      )

summarise_lme(h_t_model_reduced , run_step=TRUE)

```

-   Model works.

-   Intercepts only it is.


```{r make tidy model, fig.height=3, fig.width=9, warning = FALSE, message = FALSE, tidy = TRUE}

h_t_model.tidy <- printTidyModel(h_t_model_reduced,
                                bf_adj = 16,
                                exclude_terms = c("fin_phonL%", "genderM"),
                                write_r2="../output/Mode_PA_h_t"
                                )
h_t_model.tidy$table
h_t_model.tidy$r2

```

```{r do pairwise analysis, fig.height=3, fig.width=9, warning = FALSE, message = FALSE, tidy = TRUE}

charts <- getModelFixedFX(
  my_equation = h_t ~ mode + acc_phon + fin_phon + (1 | speaker) + (1| prompt),
  my_data = m_corpus,
  exclude_terms = c("gender", "fin_phon"),
  bf_adj = 16,
  write="../output/Mode_PA_h_t"
)
charts$intercepts
charts$pairwise


```
