---
title: 'Chapter 07: Analysis of Function'
subtitle: '7.5.3 Comparing the non-register tier analysis and the register tier analysis'
output:
  html_document:
    code_folding: hide
---

```{r setup, include=F}
knitr::opts_chunk$set(message = F, warning=F, tidy = "styler")


# Load Functions and colour variables
source("../../2_R_Functions/myFunctions.R") 
source("../../2_R_Functions/myColours.R")

# Load packages.
installMissingPackages(
  c("tidyverse", "formattable", "janitor", "knitr", "RColorBrewer", "blme")
)


# Get  Data.
m_corpus_is_H_boundary <- get_m_corpus("../../4_data/m_corpus.csv")  %>%
  mutate(
    fin_phon = if_else(
      acc_phon == "L*^[H]",
      paste("H", fin_phon, sep=""),
      paste(fin_phon)),
    # remove register tier
    across(
      c("acc_phon", "fin_phon"),
      ~ str_replace_all(., "\\^|\\[|\\]", "")
    ),
    `H% likelihood` =  str_replace(fin_phon, "HL\\%", "H%"),
    `H% likelihood` = factor(`H% likelihood`=="H%", level = c(F, T))
  ) %>%
  # Select only columns for analysis
  select(speaker,
         gender,
         mode,
         prompt,
          `H% likelihood`)



# Get  Data.
m_corpus_H_reg <- get_m_corpus("../../4_data/m_corpus.csv")  %>%
  mutate(`high register in nucleus` = factor( str_detect(acc_phon, "\\^"),
                          levels = c(F, T))) %>% 
  # Select only columns for analysis
  select(speaker,
         gender,
         prompt,
         mode,
         `high register in nucleus`)


```

## BGLMM Models {.tabset}

### likelihood of H% in non-register tier analysis

```{r H boundary re mode in non-reg tier analysis, results='asis', fig.width = 3.05, fig.height = 2.5,}
fin_phon_model_H_or_not <- bglmer(
  `H% likelihood` ~ mode + (1 | speaker) + (1 | prompt),
  data = m_corpus_is_H_boundary,
  family = binomial(link = "logit"),
  fixef.prior = normal()
)

tidy_summary_non_reg <- analyseModel(fin_phon_model_H_or_not,
                             is_GLM = T,
                             type = "pred",
                             short_caption = T)

tidy_summary_non_reg$table %>% tidyStatNumbers()
```


### Likelihood of high register in register-tier analysis

```{r GLMM Test of high reg re mode in reg tier analysis, results='asis', fig.width = 3.05, fig.height = 2.5}
h_reg_model <- bglmer(
  `high register in nucleus` ~ mode + (1 | speaker) + (1 | prompt),
  data = m_corpus_H_reg,
  family = binomial(link = "logit"),
  fixef.prior = normal()
  )

tidy_summary_reg <- analyseModel(h_reg_model,
                             is_GLM = T,
                             type = "pred",
                             short_caption = T)

tidy_summary_reg$table %>% tidyStatNumbers()
```
