---
title: "Analysis of PNs - Overview of Anacrusis Effects on Alignment"
author: "Antoin Rodgers"
date: "1/19/2020"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


Get packages from library.
```{r message=FALSE, warning=TRUE, include=FALSE}
source('../functions/drawResiduals.R', echo=TRUE)

require("tidyverse")
require("broom")
require("styler")
require("lmerTest")
require("optimx")
require("sjPlot")
require("sjmisc")
require("ggplot2")
require("hablar")
require("ggpubr")
require("MuMIn")
require("mefa4")

library(tidyverse)
library(broom)
library(styler)
library(lmerTest)
library(optimx)
library(sjPlot)
library(sjmisc)
library(ggplot2)
library(hablar)
library(ggpubr)
library(MuMIn)
require(mefa4)
options(ggplot2.palette="Set2")

theme_set(
    theme_minimal(base_size = 10)
)
```


Create data tbls
```{r message=FALSE, warning=TRUE, include=FALSE}

# Get A_corpus data
A_corpus <- read_csv("../data/a_corpus.csv") %>%
    filter(code %notin% c("F15_A1422_1", "M10_A2422_1", "F5_H0422_2")) %>% # remove surplus reps for balance
    filter(
        cur_foot == 1,
        substr(stim, 2, 4) == metre_ID
        ) %>%
    select(
        speaker, gender, stim,
        init_phon, ana_syls, ana_syls, tot_syls,
        acc_phon, wrd_end_syl,
        ana_end_t, phr_end_t,
        wrd_fin_syl_start_t, wrd_end_t, ana_end_t,
        foot_start_t, foot_end_t,
        v_onset_t, l_t, h_t,
        v_sylNormT, l_sylNormT, h_sylNormT,
        l_f0, h_f0, mean_st, lh_slope
  ) %>%
    mutate(
        d_f0 = h_f0 - l_f0,
        d_t = h_t - l_t,
        l_t = l_t - v_onset_t,
        h_t = h_t - v_onset_t,
        l_tNorm = l_sylNormT - v_sylNormT,
        h_tNorm = h_sylNormT - v_sylNormT,
        foot_dur_t = foot_end_t - foot_start_t,
        SR = 1000 * tot_syls / phr_end_t,
        isLH = acc_phon %in% "L*H",#
        isDHorLH = acc_phon %in% c("L*H", ">H*"),
        stim = factor(stim,levels = unique(stim))
        ) %>%
    rename(ana_dur = ana_end_t) %>%
    select(-c("phr_end_t", "tot_syls", "v_onset_t")) %>%
    convert(fct(speaker:wrd_end_syl))


# Get ANAC subset
pn_anac <- filter(A_corpus, stim %in% c("H0422", "A1422", "A2422", "A3422")) %>% 
        mutate(acc_phon = factor(acc_phon,
                              levels = c("(*)", "L*", "H*", ">H*", "L*H")
                              )
           ) %>% 
    mutate(stim = factor(stim, levels = unique(stim)))

pn_anac_distrib <- select(pn_anac, ana_syls, gender, acc_phon) %>%
  group_by(ana_syls, acc_phon, gender) %>%
  summarise(accCount = n()) %>%
  spread(acc_phon, accCount) %>%
  replace(., is.na(.), 0)
  

# get SR data

# get speech rate (SR) data.
SR_meansData <- full_join(
    select(a_frag <- A_corpus %>%
               filter(acc_phon %in% c("L*H", "H*", ">H*", "L*", "(*)")) %>%
               mutate(isLH = acc_phon %in% "L*H") %>%
               select(speaker,
                      gender,
                      acc_phon,
                      ana_syls,
                      ana_syls,
                      ana_dur,
                      SR,
                      isLH
                      ) %>%
               group_by(speaker, gender),
           speaker, gender, acc_phon, ana_syls, ana_dur, SR,isLH
           ) %>%
        group_by(speaker, acc_phon) %>%
        summarise(accCount = n()) %>%
        spread(acc_phon, accCount) %>%
        replace(., is.na(.), 0) %>%
        rename(
            "LH" = "L*H", "H" = "H*", "dH" = ">H*", "L" = "L*", "none" = "(*)"
            ) %>% 
        mutate(
            totalAccs = sum(LH, dH, H, L, none),
            LH_pc = LH / totalAccs,
            H_pc = (H) / totalAccs
            ),
    select(a_frag, speaker, SR) %>%
        group_by(speaker, gender) %>%
        summarise(meanSpRate = mean(SR)),
    by = "speaker")
    rm(a_frag)
    
    
write_tsv(
    pn_anac %>% group_by(acc_phon, ana_syls) %>%
    summarise(accCount = n()) %>%
    spread(acc_phon, accCount, is.na <-(0)),
    "../output/pn_anac_count_actual.txt"
    ) 

```


# Looking at PN distribution by speaker, gender, and ana_syls 

```{r}

plot1 <- ggplot(pn_anac) +
  geom_bar(mapping = aes(x = gender, fill = acc_phon), colour = "black",  
           position = "fill")+
  ggtitle("PNs by gender (anacrusis conditions)") +
    scale_fill_brewer(palette = "Spectral", name = "Pitch Accent") +
    labs(x = "distibution by gender",
         y = "proportion of tokens"
         ) +
    scale_y_continuous(labels = scales::percent)
plot1
ggsave("../figures/PN_anac_dist_gender.png", plot1, height = 4, width = 6)

plot2 <- ggplot(pn_anac) +
  geom_bar(mapping = aes(x = ana_syls, fill = acc_phon),
           colour = "black",
            show.legend = FALSE,
    position = position_dodge2(preserve = "single")) + 
    facet_grid(rows = vars(gender), cols = vars(acc_phon)) +
    ggtitle("PNs by gender and anacrusis") +
    scale_fill_brewer(palette = "Spectral", name = "Pitch Accent") +
    labs(x = "anacrusis size (sylables)",
         y = "tokens (n)"
         ) +
    theme(panel.border = element_rect(fill = NA))
plot2
ggsave("../figures/PN_anac_dist_gender_anac.png", plot2, height = 5.5, width = 12)

plot3 <- ggplot(pn_anac) +
    geom_bar(mapping = aes(x = ana_syls, fill = acc_phon),
             show.legend = FALSE,
             colour = "black",
             position = position_dodge2(preserve = "single")) +
    facet_grid(cols = vars(acc_phon)) +
    theme(panel.border = element_rect(fill = NA)) +
    ggtitle("PNs across anacrusis conditions (syllables)") +
    scale_fill_brewer(palette = "Spectral", name = "Pitch Accent") +
    labs(x = "anacrusis size (syllables)", y = "tokens (n)") +
    theme(panel.border = element_rect(fill = NA))
plot3
ggsave("../figures/PN_anac_distribution.png", plot3, height = 4, width = 12)

```

### Rejigging >H* by gender
```{r echo=FALSE, fig.height=4, fig.width=12}
pn_anac <- 
    mutate(pn_anac,
           genderedDh = factor(
                               ifelse(acc_phon == ">H*" & gender == "F",
                                      "H*",
                                      ifelse(acc_phon == ">H*" & gender == "M",
                                             "L*H",
                                             as.character(acc_phon)
                                             )
                                      ),
                               levels = c("(*)", "L*", "H*", "L*H")
                               )
           )

pn_anac_GDH_summary <- pn_anac %>% group_by(genderedDh, ana_syls) %>%
    summarise(accCount = n()) %>%
    spread(genderedDh, accCount, is.na <-(0))
    
write_tsv(pn_anac_GDH_summary, "../output/pn_anac_count_GDH.txt")
print(pn_anac_GDH_summary)


plot1 <- ggplot(pn_anac) +
  geom_bar(mapping = aes(x = gender, fill = genderedDh), colour = "black",  
           position = "fill")+
  ggtitle("PNs by gender re gendered >H*") +
    labs(x = "distibution by gender",
         y = "proportion of tokens"
         ) +
    scale_fill_brewer(palette = "Spectral", name = "Pitch Accent") +
    scale_y_continuous(labels = scales::percent)

plot1

ggsave("../figures/pn_anac_GDH_dist_gender.png", plot1, height = 4, width = 3)


plot2 <- ggplot(pn_anac) +
  geom_bar(mapping = aes(x = ana_syls, fill = genderedDh),
           colour = "black"
           ) +
    facet_grid(cols = vars(gender)) +
    ggtitle("PNs by gender and anacrusis (gendered >H*)") +
    scale_fill_brewer(palette = "Spectral", name = "Pitch Accent") +
    labs(x = "anacrusis (syllables) and gender",
         y = "tokens (n)"
         ) +
    theme(panel.border = element_rect(fill = NA))

plot2

ggsave("../figures/pn_anac_GDH_dist_gender_anac.png", plot2, height = 5.5, width = 12)


plot3 <- ggplot(pn_anac) +
    geom_bar(mapping = aes(x = ana_syls, fill = genderedDh),
             colour = "black"
             ) +
    theme(panel.border = element_rect(fill = NA)) +
    ggtitle("PNs and anacrusis (gendered >H*)") +
    scale_fill_brewer(palette = "Spectral", name = "Pitch Accent") +
    labs(x = "anacrusis (syllables)", y = "tokens (n)") +
    theme(panel.border = element_rect(fill = NA))

plot3
ggsave("../figures/pn_anac_GDH_distribution.png", plot3, height = 4, width = 6)

plot4 <- ggarrange(plot3, plot2, ncol = 2, common.legend = TRUE, legend = "right", widths = 4:8)
ggsave("../figures/pn_anac_GDH_distribution2.png", plot4, height = 4, width = 12)


```
