---
title: "Chapter 7 - LME analysis of lh_slope ~ Mode and Nuclear pitch accents: "
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,
                      warning=FALSE,
                      message=FALSE)

# Load Functions.
source("../../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

```

```{r load corpus, include=FALSE}
l_star_h_types = c("^[L*]H", "L*H", "L*^[H]", "^[L*H]")

# Load Corpus
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  # Consolidate nuc_contour based on observation and types of register shift.
  mutate(
    nuc_contour =
      if_else(
        nuc_contour == "^[L*H %]" | nuc_contour == "^[L*H L%]",
        "^[L*H] %",
        if_else(nuc_contour == "L*^[H L%]", "L*^[H] %", nuc_contour)
      ),
    acc_phon =
      factor(
        str_replace(nuc_contour,
                    "\\s%$|\\sL%$",
                    ""),
        levels = c("H*", ">H*", "^[L*]H", "L*H", "L*^[H]", "^[L*H]")
      ),
    fin_phon = str_replace_all(fin_phon, "L%]|%]", "%"),
    fin_phon = factor(fin_phon, levels=unique(fin_phon))
  ) %>%
  # Select only columns for analysis
  select(
    speaker,
    gender,
    mode,
    prompt,
    acc_phon,
    fin_phon,
    lh_slope) %>% 
  filter(acc_phon %in% l_star_h_types)  %>% 
  mutate(acc_phon = factor(acc_phon,
                           levels = l_star_h_types)
         )
```


```{r run initial model,  fig.height=3, fig.width=9, eval=FALSE, tidy = TRUE}

# run model
lh_slope_model <-
    lmer(lh_slope ~ mode * acc_phon + fin_phon + gender + 
           (1 + acc_phon + mode | speaker) + (1 | prompt),
        data = m_corpus,
        control = lmerControl(
            optimizer = "optimx",
            calc.derivs = FALSE,
            optCtrl = list(
                method = "nlminb",
                starttests = FALSE,
                kkt = FALSE
            )
        )
      )

summariseLME(lh_slope_model, run_step=TRUE)

```

-   Singularity and convergence  issues.
-   Testing reduced model suggested by step(). Dropping gender

```{r run reduced step() only model, fig.height=3, fig.width=9, eval=FALSE, tidy = TRUE}

lh_slope_model <-
    lmer(lh_slope ~ mode*acc_phon + (1 + acc_phon + mode | speaker) + (1 | prompt),
        data = m_corpus,
        control = lmerControl(
            optimizer = "optimx",
            calc.derivs = FALSE,
            optCtrl = list(
                method = "nlminb",
                starttests = FALSE,
                kkt = FALSE
            )
        )
    )

summariseLME(lh_slope_model , run_step = TRUE)

```

-   Singularity and convergence issues persist.
-   Trying intercepts only mode but reintroducing original factors.
-   This model works.
-   Trimming model for observations with model residual of > 3 standard deviations.

#### `lh_slope ~ mode * acc_phon + fin_phon + gender + (1 | speaker) + (1 | prompt)`
```{r intercepts only model tested, fig.height=3, fig.width=9, tidy = TRUE}

lh_slope_model <-
    lmer(lh_slope ~
           mode * acc_phon + fin_phon + gender + (1 | speaker) + (1 | prompt),
        data = m_corpus,
        control = lmerControl(
            optimizer = "optimx",
            calc.derivs = FALSE,
            optCtrl = list(
                method = "nlminb",
                starttests = FALSE,
                kkt = FALSE
            )
        )
    )

m_corpus.trimmed <- m_corpus %>% filter(abs(scale(resid(lh_slope_model))) <= 3)

lh_slope_model.trimmed <-
    lmer(lh_slope ~
           mode * acc_phon + fin_phon + gender + (1 | speaker) + (1 | prompt),
        data = m_corpus.trimmed,
        control = lmerControl(
            optimizer = "optimx",
            calc.derivs = FALSE,
            optCtrl = list(
                method = "nlminb",
                starttests = FALSE,
                kkt = FALSE
            )
        )
    )

summariseLME(lh_slope_model.trimmed, run_step = TRUE,
              write="../output_model_anovas/Mode_PA_lh_slope_anova.csv")
```

```{r make tidy model, fig.height=3, fig.width=9, ,  warning = FALSE, message = FALSE, tidy = TRUE}

lh_slope_model.tidy <- analyseModel(lh_slope_model.trimmed,
                                write_r2="../output/Mode_PA_lh_slope"
                                )
lh_slope_model.tidy$r2

```

```{r do pairwise analysis, fig.height=3, fig.width=9, warning = FALSE, message = FALSE, tidy = TRUE}

charts <- getModelFixedFX(
  my_equation = lh_slope ~ mode * acc_phon + fin_phon + gender +
    (1 | speaker) + (1 | prompt),
  my_data = m_corpus.trimmed,
  write="../output/Mode_PA_lh_slope"
)
charts$intercepts
charts$pairwise


```
