---
title: "Chapter 7 - LME analysis of l_f0 ~ Mode and Nuclear pitch accents: "
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

# Load Functions.
source("../../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

# Load Corpus
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  # Consolidate nuc_contour based on observation and types of register shift.
  mutate(
    nuc_contour =
      if_else(
        nuc_contour == "^[L*H %]" | nuc_contour == "^[L*H L%]",
        "^[L*H] %",
        if_else(nuc_contour == "L*^[H L%]", "L*^[H] %", nuc_contour)
      ),
    acc_phon =
      factor(
        str_replace(nuc_contour,
                    "\\s%$|\\sL%$",
                    ""),
        levels = c("H*", ">H*", "^[L*]H", "L*H", "L*^[H]", "^[L*H]")
      ),
    fin_phon = str_replace_all(fin_phon, "L%]|%]", "%"),
    fin_phon = factor(fin_phon, levels=unique(fin_phon))
  ) %>%
  # Select only columns for analysis
  select(speaker,
         gender,
         mode,
         prompt,
         acc_phon,
         fin_phon,
         l_f0) %>%
  # keep only explicitly LH pitch accents.
  filter(acc_phon %notin% c("H*", ">H*")) %>%
  mutate(acc_phon = factor(acc_phon,
                           levels = c("^[L*]H", "L*H", "L*^[H]", "^[L*H]")))

```


```{r run initial models,  fig.height=3, fig.width=9, eval=FALSE, tidy = TRUE}
l_f0_model <-
  lmer(l_f0 ~ mode * acc_phon + fin_phon + gender +
         (1 + acc_phon + mode | speaker) + (1 | prompt),
    data = m_corpus,
    control = lmerControl(
      optimizer = "optimx",
      calc.derivs = FALSE,
      optCtrl = list(
        method = "nlminb",
        starttests = FALSE,
        kkt = FALSE
      )
    )
  )
summariseLME(l_f0_model, run_step = TRUE)
```
-    Convergence and singularity issues.
-    Trying model suggested by step()


```{r run step() models,  fig.height=3, fig.width=9, eval=FALSE, tidy = TRUE}
l_f0_model <-
  lmer(
    l_f0 ~ mode*acc_phon + fin_phon + (1 + acc_phon + mode | speaker),
    data = m_corpus,
    control = lmerControl(
      optimizer = "optimx",
      calc.derivs = FALSE,
      optCtrl = list(
        method = "nlminb",
        starttests = FALSE,
        kkt = FALSE
      )
    )
  )
summariseLME(l_f0_model, run_step = TRUE)
```
-    Optimization issue persist.
-    changing to intercepts only model. 

```{r run intercepts only model, fig.height=3, fig.width=9, include=FALSE, tidy = TRUE}
l_f0_model <-
  lmer(
    l_f0 ~ mode * acc_phon + fin_phon + gender + (1 | speaker),
    data = m_corpus,
    control = lmerControl(
      optimizer = "optimx",
      calc.derivs = FALSE,
      optCtrl = list(
        method = "nlminb",
        starttests = FALSE,
        kkt = FALSE
      )
    )
  )
summariseLME(l_f0_model, run_step = TRUE)
```

-   Model works but a few outliers.
-   Trimming data where residual of observation > 3 standard deviations.

```{r trim model, fig.height=3, fig.width=9, tidy = TRUE}
m_corpus.trimmed <- m_corpus %>% filter(abs(scale(resid(l_f0_model))) <= 3)

l_f0_model.trimmed <-
  lmer(
    l_f0 ~ mode * acc_phon + fin_phon + gender + (1 | speaker),
    data = m_corpus.trimmed,
    control = lmerControl(
      optimizer = "optimx",
      calc.derivs = FALSE,
      optCtrl = list(
        method = "nlminb",
        starttests = FALSE,
        kkt = FALSE
      )
    )
  )
summariseLME(l_f0_model.trimmed, run_step = TRUE,
              write="../output_model_anovas/Mode_PA_l_f0_anova.csv")

```


```{r make tidy model, fig.height=3, fig.width=9,  tidy = TRUE}
l_f0_model.tidy <- analyseModel(l_f0_model,
                                write_r2="../output/Mode_PA_l_f0"
                                )
l_f0_model.tidy$r2

```

```{r do pairwise analysis, fig.height=3, fig.width=9, tidy = TRUE}
# Get number of levels in target treatment variable.

charts <- getModelFixedFX(
  my_equation = l_f0 ~ mode * acc_phon + fin_phon + gender + (1 | speaker),
  my_data = m_corpus.trimmed,
  write="../output/Mode_PA_l_f0"
)
charts$intercepts
charts$pairwise


```

