---
title: "Chapter 7 - LME analysis of f0_exc ~ Mode and Nuclear pitch accents: "
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,
                      warning=FALSE,
                      message=FALSE)

# Load Functions.
source("../../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

```

```{r load corpus, include=FALSE}
l_star_h_types = c("L*H", "^[L*]H", "L*^[H]", "^[L*H]")

# Load Corpus
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  # Select only columns for analysis
  select(
    speaker,
    gender,
    mode,
    prompt,
    acc_phon,
    fin_phon,
    f0_exc) %>% 
  filter(acc_phon %in% l_star_h_types)  %>% 
  mutate(acc_phon = factor(acc_phon,
                           levels = l_star_h_types)
         )
```

-  Model works with gender and (1 | prompt) removed
```{r set equation and optimizer}
my_equation = formula(
  f0_exc ~ mode * acc_phon
  + gender
  + fin_phon
  + (1 + mode + acc_phon | speaker)
  + (1 | prompt)
)

# prompt causes singularity. Removing from model.
my_equation = formula(
  f0_exc ~ mode * acc_phon
  #+ gender
  + fin_phon
  + (1 | speaker)
  #+ (1 | prompt)
)
optimizer = "optimx"
```

```{r run initial model,  fig.height=3, fig.width=9, eval=FALSE, tidy = TRUE}

f0_exc_model <- lmer(
  my_equation,
  m_corpus,
  control = lmerControl(
    optimizer = optimizer,
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
  )

summariseLME(f0_exc_model, run_step=TRUE) 
```

-  Convergence and singularity issues in initial model.
-  Using model found by step ( without prompt and gender)

```{r run step model,  fig.height=3, fig.width=9, eval=FALSE, tidy = TRUE}

f0_exc_model <-
  lmer(
    my_equation,
    m_corpus,
    control = lmerControl(
      optimizer = "optimx",
      calc.derivs = FALSE,
      optCtrl = list(
        method = "nlminb",
        starttests = FALSE,
        kkt = FALSE
      )
    )
  )

summariseLME(f0_exc_model, run_step=TRUE) 

```
```{r intercepts-only model,  fig.height=3, fig.width=9, tidy = TRUE}

f0_exc_model <-
  lmer(my_equation,
    m_corpus,
    control = lmerControl(
      optimizer = "optimx",
      calc.derivs = FALSE,
      optCtrl = list(
        method = "nlminb",
        starttests = FALSE,
        kkt = FALSE
      )
    )
  )

m_corpus.trimmed <- m_corpus %>% filter(abs(scale(resid(f0_exc_model))) <= 3)

f0_exc_model <-
  lmer(
    my_equation,
    data = m_corpus.trimmed,
    control = lmerControl(
      optimizer = "optimx",
      calc.derivs = FALSE,
      optCtrl = list(
        method = "nlminb",
        starttests = FALSE,
        kkt = FALSE
      )
    )
  )

summariseLME(f0_exc_model, run_step=TRUE)

```

```{r make tidy model, fig.height=5, fig.width=7, results="asis"}

f0_exc_model.tidy <- analyseModel(f0_exc_model, write = "../output/Mode_PA_f0_exc")
f0_exc_model.tidy$table

```

```{r do pairwise analysis}

charts <- getModelFixedFX(
  my_equation,
  m_corpus.trimmed,
  write="../output/Mode_PA_f0_exc",
  optimizer=optimizer
)
charts$intercepts
charts$slopes


```
