---
title: "Visual Analysis of PN peaks in A-Corpus PNs (H*, >H*, L*H)"
author: "Antoin Rodgers"
date: "18.05.2022"
output:
  html_document: default
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = F, 
                      message = F,
                      warning = F)

## Get personal functions and install / load necessary packages.
source("../2_R_Functions/myFunctions.R")

installMissingPackages(c("tidyverse", "formattable","janitor","mefa4", "knitr",
                         "gridExtra", "RColorBrewer"))

## Set themes and colour schemes.
theme_set(theme_minimal(base_size = 10))
```


```{r get data, include=F}
## Get  data for analysis

source("0_get_AH.R")


h_star_type <-  c("H*", ">H*",  "L*H")

pn_wrd_stims <- c("A0423", "A1422","A2422", "A3422")

pn_wrd_sent <- c("Valerie's is valid.",
                 "The valley's by the river",
                 "There's a valley with a river",
                 "There was a valley with a river")

pn_phr <- c("Valerie's is",
            "valley's by the river",
            "valley with a",
            "valley with a")

pn <- pn %>%
  select(
    sent,
    speaker,
    stim,
    acc_phon,
    wrd_end_syl,
    h_t,
    v_grand_mean_t,
    h_grand_mean_t,
    h_syl,
    h_syl_ratio,
    ana_syls
    ) %>%
  # Get time normalised peaks
    mutate(
      ana_syls = as.character(ana_syls) %>% as.numeric(),
      h_syl_ft = as.integer(h_syl) - ana_syls,
      h_syl_norm_t = h_syl_ft + h_syl_ratio - 1,
      h_grand_mean_t_re_v = h_grand_mean_t - v_grand_mean_t
      ) %>% 
  # remove parameters no longer needed
  select(-c(v_grand_mean_t, h_grand_mean_t))

pn_wrd_data <- pn %>%
  filter(acc_phon %in% h_star_type,
         stim %in% pn_wrd_stims) %>%
  mutate(acc_phon = factor(acc_phon, levels = h_star_type))


pn_wrd_adj <- pn %>% 
  filter(ana_syls %in% c(1,2,3)) %>% 
  balancedData(ana_syls, acc_phon,"", 11, 5) %>%
  pivot_longer(values_to = "acc_phon", cols = 2:last_col()) %>% uncount(acc_phon) %>%
  rename(acc_phon = name)

rm(nuc, nuc_foot, pn_lex, pn_ana, pn_foot, corpus, nuc_pre)


```

```{r check data}
pn %>%
  filter(acc_phon %in% h_star_type) %>%
  mutate(acc_phon = str_replace_all(acc_phon, "([\\*\\>])", "\\\\\\1")) %>% 
  group_by(acc_phon, ana_syls) %>%
  summarise(count = n()) %>% pivot_wider(values_from = count,
                                         names_from = acc_phon,
                                         values_fill = 1) %>%
  arrange(ana_syls)  %>%
  adorn_totals(where = "col") %>%
  adorn_totals(where = "row") %>% 
  formattable(caption = "Distribution of prenuclear PAs with H targets in H-corpus (raw data)")

pn_wrd_data %>%
  filter(acc_phon %in% h_star_type) %>%
  group_by(speaker, ana_syls) %>%
  summarise(count = n()) %>% pivot_wider(values_from = count,
                                         names_from = speaker,
                                         values_fill = 1)  %>% 
  adorn_totals(where = "col") %>%
  adorn_totals("row", fill = "") %>%
  formattable(caption = "L\\*H, \\>H\\*, and H\\*")

```


```{r check data excluding ana_0 condition}
pn_wrd_data <- pn_wrd_data %>%
  filter(acc_phon %in% h_star_type,
         ana_syls != 0) %>% 
  mutate(ana_syls = factor(ana_syls, levels = c(1,2,3)),
    pn_wrds = ana_syls,
    pn_wrds = str_replace(pn_wrds, "1",  "The valley's by the"),
    pn_wrds = str_replace(pn_wrds, "2",  "There's a valley with a"),
    pn_wrds = str_replace(pn_wrds, "3",  "There was a valley with a"))

pn_wrd_data %>%
  filter(acc_phon %in% h_star_type,
         ana_syls != 0) %>% 
  group_by(speaker, ana_syls) %>%
  summarise(count = n()) %>%
  pivot_wider(values_from = count,
              names_from = speaker,
              values_fill = 0)  %>%
  adorn_totals("col") %>%
  adorn_totals("row", fill = "") %>%
  formattable(caption = "ana_syls 1 to 3 only")
```

```{r Get means etc }


pn_wrd_data_sum <- pn_wrd_data %>%
  group_by(speaker, acc_phon, ana_syls) %>%
  summarise(mean_gm_h_t = mean(h_grand_mean_t_re_v)) %>% 
  arrange(ana_syls)
```


```{r adjusted PA distribution, fig.width = 6.1, fig.height = 3}
my_plot <- ggplot(data = pn_wrd_adj %>%
                    filter(acc_phon %in% h_star_type) %>% 
                    mutate(acc_phon = factor(acc_phon, levels = h_star_type),
                           pn_wrds = factor(ana_syls, levels = c(1,2,3))),
  mapping = aes(x = ana_syls, fill = acc_phon)
) +
  geom_bar(stat = "count",
           position = "dodge",
           colour = "black") +
  
  geom_text(aes(
    label = (..count..),
    vjust = -0.5
  ),
  stat = "count",
  position = position_dodge(.9),
  size = 3) +
  
  #facet_wrap(vars(pairing)) +
  scale_fill_manual(
    values = brewer.pal(4, "Dark2"),
    name = NULL
  ) +
  theme(
    legend.position = "bottom",
    legend.key.size = unit(0.4, "cm"),
    panel.grid.major = element_blank()
  ) +
  ylim(0, 60) +
  xlab("prenuclear pitch accent") +
  ylab("count (adjusted)")

png(
  filename =
    paste0("6_corrections_supplemental/PA_peak_by_ana_syls.png"),
  width =  15.25,
  height = 6.5,
  units = "cm",
  res = 300
)
print(my_plot)
dev.off()



print(my_plot)
```


```{r plot SNT acc phon, fig.width = 6, fig.height = 4, include = F}

ggplot(
  data = pn_wrd_data,
  mapping = aes(x = h_syl_norm_t
                , fill = acc_phon
                )
) +
  geom_density(stat = "density", alpha = 0.4) +
  geom_dotplot(dotsize = 0.67, alpha = 0.4) +
  scale_fill_manual(
    values = brewer.pal(6, "Dark2"),
    name = NULL
  ) +
  theme(
    legend.position = "right",
    legend.key.size = unit(0.5, "cm"),
    panel.grid.major.x = element_line(color = "grey",
                                      size = 0.5),
    panel.grid.minor.x = element_blank()) +
    theme_minimal(base_size = 12)+
  xlim(0, 4) +
  xlab("syllable normalised time (from onset of foot)") +
  ylab("density") +
  labs(title = "PN peak timing of L*H, >H*, H*")


ggplot(
  data = pn_wrd_data,
  mapping = aes(x = h_syl_norm_t
                , fill = ana_syls
                )
) +
  geom_density(stat = "density", alpha = 0.4) +
  geom_dotplot(dotsize = 0.75, alpha = 0.4) +
  #facet_wrap(vars(ana_syls)) +
  scale_fill_manual(
    values = brewer.pal(6, "Dark2"),
    name = NULL
  ) +
  theme(
    legend.position = "right",
    legend.key.size = unit(0.5, "cm"),
    panel.grid.major.x = element_line(color = "grey",
                                      size = 0.5),
    panel.grid.minor.x = element_blank()) +
    theme_minimal(base_size = 12)+
  xlim(0, 4) +
  xlab("syllable normalised time (from onset of foot)") +
  ylab("proportion") +
  labs(title = "PN peak timing aggregating by ana_syls")

ggplot(
  data = pn_wrd_data %>% 
    filter(ana_syls != 1),
  mapping = aes(x = h_syl_norm_t)
) +
  geom_density(stat = "density", alpha = 0.4) +
  geom_dotplot(dotsize = 0.6, alpha = 0.4) +
  scale_fill_manual(
    values = brewer.pal(1, "Dark2"),
    name = NULL
  ) +
  theme(
    legend.position = "right",
    legend.key.size = unit(0.5, "cm"),
    panel.grid.major.x = element_line(color = "grey",
                                      size = 0.5),
    panel.grid.minor.x = element_blank()) +
    theme_minimal(base_size = 12)+
  xlim(0, 4) +
  xlab("syllable normalised time (from onset of foot)") +
  ylab("density") +
  labs(title = "PN peak timing ana_syls 2 and 3 only")

```


### Grand mean normalised time
```{r plot GMT acc phon, fig.width = 6, fig.height = 4}

ggplot(
  data = pn_wrd_data,
  mapping = aes(x = h_grand_mean_t_re_v
                , fill = acc_phon
                )
) +
  geom_density(stat = "density", alpha = 0.4) +
  geom_dotplot(dotsize = 0.67, alpha = 0.4) +
  scale_fill_manual(
    values = brewer.pal(6, "Dark2"),
    name = NULL
  ) +
  theme(
    legend.position = "right",
    legend.key.size = unit(0.5, "cm"),
    panel.grid.major.x = element_line(color = "grey",
                                      size = 0.5),
    panel.grid.minor.x = element_blank()) +
    theme_minimal(base_size = 12)+
  ylim(0, 0.025) +
  xlab("grand mean syllable normalised time (from onset of vowel)") +
  ylab("density") +
  labs(title = "PN peak timing of L*H, >H*, H*")

```

```{r plot GMT1, fig.width = 8, fig.height = 4, include = F}

ggplot(
  data = pn_wrd_data,
  mapping = aes(x = h_grand_mean_t_re_v
                , fill = ana_syls
                )
) +
  geom_density(stat = "density", alpha = 0.4) +
  geom_dotplot(dotsize = 2, alpha = 0.4) +
  facet_wrap(vars(ana_syls)) +
  scale_fill_manual(
    values = brewer.pal(6, "Dark2"),
    name = NULL
  ) +
  theme(
    legend.position = "right",
    legend.key.size = unit(0.5, "cm"),
    panel.grid.major.x = element_line(color = "grey",
                                      size = 0.5),
    panel.grid.minor.x = element_blank()) +
    theme_minimal(base_size = 12)+
  ylim(0, 0.0115) +
  xlab("grand mean syllable normalised time (from onset of vowel)") +
  ylab("density") +
  labs(title = "PN peak timing by ana_syls")

```

```{r plot GMT2, fig.width = 6, fig.height = 4}
ggplot(
  data = pn_wrd_data,
  mapping = aes(x = h_grand_mean_t_re_v
                , fill = ana_syls
                )
) +
  geom_density(stat = "density", alpha = 0.4) +
  geom_dotplot(dotsize = 1, alpha = 0.4) +
  #facet_wrap(vars(ana_syls)) +
  scale_fill_manual(
    values = brewer.pal(6, "Dark2"),
    name = NULL
  ) +
  theme(
    legend.position = "right",
    legend.key.size = unit(0.5, "cm"),
    panel.grid.major.x = element_line(color = "grey",
                                      size = 0.5),
    panel.grid.minor.x = element_blank()) +
    theme_minimal(base_size = 12)+
  ylim(0, 0.0115) +
  xlab("grand mean syllable normalised time (from onset of vowel)") +
  ylab("density") +
  labs(title = "PN peak timing by ana_syls")

ggplot(
  data = pn_wrd_data %>% 
    filter(ana_syls != 1),
  mapping = aes(x = h_grand_mean_t_re_v
                
                )
) +
  geom_density(stat = "density", alpha = 0.4) +
  geom_dotplot(dotsize = 1, alpha = 0.4) +
  scale_fill_manual(
    values = brewer.pal(1, "Dark2"),
    name = NULL
  ) +
  theme(
    legend.position = "right",
    legend.key.size = unit(0.5, "cm"),
    panel.grid.major.x = element_line(color = "grey",
                                      size = 0.5),
    panel.grid.minor.x = element_blank()) +
    theme_minimal(base_size = 12)+
  ylim(0, 0.0115) +
  xlab("grand mean syllable normalised time (from onset of vowel)") +
  ylab("density") +
  labs(title = "PN peak timing ana_syls 2 and 3 only")

```

