---
title: "BGLMM Analysis of PN Phonology"
author: "AERodgers"
date: "2/18/2022"
output:
  html_document: default
---

```{r setup, include=F,}
knitr::opts_chunk$set(echo = F,
                      warning = F,
                      message = F)
start <- Sys.time()

# Get personal functions and install / load necessary packages.
source("../2_R_Functions/myFunctions.R")

installMissingPackages(
  c(
    # Include statistical packages.
    "lmerTest",
    "blme",
    "optimx",
    "MuMIn",
    
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "ggeffects",
    "weights",
    
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Get data frames for AH analysis
source("0_get_AH.R")
# Add isLH column


pn <- pn %>%
  select(
    speaker,
    gender,
    ana_syls,
    foot_syls,
    acc_phon,
    wrd_end_syl,
    ana_text,
    pn_str_syl,
    nuc_pre_text,
    pn_new_word,
    acc_phon,
    speech_rate
  ) %>%
  mutate(
    isLH = factor(if_else(acc_phon == "L*H",
                          T,
                          F),
                  levels = c(F, T)),
    isHStar = factor(if_else(acc_phon == "H*",
                             T,
                             F),
                     levels = c(F, T)),
    gender = factor(gender, levels = c("F", "M")),
    foot_syls = factor(foot_syls, levels = 1:4)
  )


rm(nuc, nuc_foot, pn_lex, pn_ana, pn_foot, corpus, nuc_pre)


# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))



```

```{r set isLH equation}
isLH_equation <- formula(isLH ~
                           ana_syls
                         + foot_syls
                         + wrd_end_syl
                         + speech_rate
                         + gender
                         + (1 | speaker)
                         + (1 | ana_text)
                         + (1 | nuc_pre_text)
                         + (1 | pn_str_syl)
                         )

```

#### Run isLH model

```{r run isLH models}
lh_pn_model <- bglmer(
  isLH_equation,
  data = pn,
  fixef.prior = normal(),
  family = binomial(link = "logit"),
  glmerControl(optimizer = "nlminbwrap",
               tol = 2e-5)
)
lh_pn_model <- optimizeModel(lh_pn_model, reject_nm = T)
summary(lh_pn_model)

```

```{r random LH effects 3, 4, fig.height=3, fig.width=3.05}
plot_model(lh_pn_model,
           type="re",
           show.values = T, ci.lvl= 0.95,
           )[[3]]
plot_model(lh_pn_model,
           type="re",
           show.values = T, ci.lvl= 0.95,
           )[[4]]
```


```{r random LH effect 2, fig.height=3, fig.width=6.1}
plot_model(lh_pn_model,
           type="re",
           show.values = T, ci.lvl= 0.95,
           )[[2]]

```

```{r run drop1 as per factor assessment of  modelsLH}
write <- "2_output/lh_model"

model_formula <- getModelFormula(lh_pn_model)

write(paste(str_replace_all(model_formula, "\\`", ""), sep = ""),
      paste(write, "_formula.txt", sep = ""))

x <- drop1(lh_pn_model, test = "Chisq")

  tibble(factor = row.names(x))  %>% 
  cbind(tibble(x)) %>% 
  filter(!is.na(npar)) %>%
  mutate(`p.adj (BH)` = NA, signif. = NA) %>% 
  write_csv(paste(write, "_anova.csv", sep = "")) 

adjustP_posthoc("2_output/",
                `Pr(Chi)`,
                suffix_id = "_anova")

read_csv(paste(write, "_anova.csv", sep = "")) %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Drop 1 ChiSq test of model:", model_formula))

```

```{r model charts and figures, fig.width = 3.051181, fig.height = 2.5, results="asis"}
cat(
  "isSingular(lh_pn_model, tol=1e-5) -->",
  isSingular(lh_pn_model, tol = 1e-5),
  "\n"
)

tidy_summary <- analyseModel(lh_pn_model,
                             write = "2_output/lh_model",
                             is_GLM = T,
                             type = "pred",
                             ci.lvl=0.95,
                             breaks = seq(0, 1, 0.2),
                             panel_prefix = "letters",
                             plot_rounding = 2)


plot_model(lh_pn_model,
           type = "est",
           transform = NULL,
           show.values = T,
           vline = "Red",
           title = "Estimates of model of L*H probability") +
  theme(axis.title.x = element_text(size = 9),
        plot.caption = element_text(hjust = 0, size = 10),
        plot.title = element_text(hjust = 0, size = 10),
        plot.caption.position = "plot")

tidy_summary$table %>% tidyStatNumbers()

printTidyPredictions(lh_pn_model) 
charts <- getModelFixedFX(lh_pn_model, write="2_output/lh_model")
charts$slopes %>% tidyStatNumbers()
```

## Run isHStar model
```{r set isHStar equation}
isHStar_equation <- formula(isHStar ~
                           ana_syls
                         + foot_syls
                         + wrd_end_syl
                         + speech_rate
                         + gender
                         + (1 | speaker)
                         + (1 | ana_text)
                         + (1 | nuc_pre_text)
                         + (1 | pn_str_syl)
                         )

```

```{r}
h_star_model <- bglmer(isHStar_equation,
                       pn,
                       fixef.prior = normal(),
                       family = binomial(link = "logit"),
                       glmerControl(optimizer = "nlminbwrap",
                                    tol = 2e-5))
h_star_model <- optimizeModel(h_star_model, reject_nm = T)
summary(h_star_model)
```



```{r random H effects 3, 4, fig.height=3, fig.width=3.05}
plot_model(h_star_model,
           type="re",
           show.values = T, ci.lvl= 0.95,
           )[[3]]
plot_model(h_star_model,
           type="re",
           show.values = T, ci.lvl= 0.95,
           )[[4]]

plot_model(h_star_model,
           type="re",
           show.values = T, ci.lvl= 0.95,
           )[[2]]

```


```{r run drop1 as per factor assessment of  modelsLHStar}

write <- "2_output/h_star_model"
model_formula <- getModelFormula(h_star_model)

 write(paste(str_replace_all(model_formula, "\\`", ""), sep = ""),
       paste(write, "_formula.txt", sep = ""))

temp <- drop1(h_star_model, test = "Chisq")

tibble(factor = row.names(temp))  %>%
  cbind(tibble(temp)) %>%
  filter(!is.na(npar)) %>%
  mutate(`p.adj (BH)` = NA, signif. = NA) %>%
  write_csv(paste(write, "_anova.csv", sep = "")) 


# p. adjust all phonology models
adjustP_posthoc("2_output/",
                `Pr(Chi)`,
                suffix_id = "_anova")

# read and print adjusted version
read_csv(paste(write, "_anova.csv", sep = "")) %>%
  tidyStatNumbers() %>%
  formattable(caption = paste("Drop1 ChiSq test of formula:", model_formula))



```

```{r fig.width = 3.051181, fig.height = 2.5, results="asis"}
cat(
  "isSingular(h_star_model, tol=1e-5) -->",
  isSingular(h_star_model, tol = 1e-5),
  "\n"
)

tidy_summary <- analyseModel(h_star_model,
                             write = "2_output/h_star_model",
                             is_GLM = T,
                             type = "pred",
                             breaks = seq(0, 1, 0.2),
                             panel_prefix = "letters",
                             plot_rounding = 2)


plot_model(h_star_model,
           type = "est",
           transform = NULL,
           show.values = T,
           vline = "Red",
           title = "Estimates of model of H* probability") +
  theme(axis.title.x=element_text(size = 9),
        plot.caption=element_text(hjust = 0, size = 10),
        plot.title=element_text(hjust = 0, size = 10),
        plot.caption.position= "plot")

printTidyPredictions(h_star_model) 
charts <-  getModelFixedFX(h_star_model, write="2_output/h_star_model")
charts$slopes %>% tidyStatNumbers()
```
