---
title: "Chapter 7 - LME analysis of l_t ~ Mode"
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

# Load Functions.
source("../../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

```

```{r load corpus}
l_star_h_types = c("^[L*]H", "L*H", "L*^[H]", "^[L*H]")

# Load Corpus
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  # Select only columns for analysis
  select(
    speaker,
    gender,
    mode,
    prompt,
    acc_phon,
    fin_phon,
    l_t) %>% 
  filter(acc_phon %in% l_star_h_types)  %>% 
  mutate(acc_phon = factor(acc_phon,
                           levels = l_star_h_types)
         )
```
- Maximal model works well, but ...
- For consistency with h_t, running random intercepts-only model.
- Trimming observation where residual standard deviation > 3.5

### `l_t ~ mode + (1 | speaker) + (1 | fin_phon) + (1 | gender) + (1 | prompt)`

```{r run initial model,  fig.height=3, fig.width=9, tidy = TRUE}

# run model
l_t_model <-
  lmer(
    l_t  ~ mode + (1 | speaker) + (1 | fin_phon) + (1 | gender) + (1 | prompt),
    data = m_corpus,
    control = lmerControl(
      optimizer = "optimx",
      calc.derivs = FALSE,
      optCtrl = list(
        method = "nlminb",
        starttests = FALSE,
        kkt = FALSE
      )
    )
  )

m_corpus.trimmed <- m_corpus %>% filter(abs(scale(resid(l_t_model))) <= 3.5)

l_t_model.trimmed <- lmer(
  l_t ~ mode + (1 | speaker) + (1 | fin_phon) + (1 | gender) + (1 | prompt),
       data = m_corpus.trimmed,
        control = lmerControl(
          optimizer = "optimx",
          calc.derivs = FALSE,
          optCtrl = list(
            method = "nlminb",
            starttests = FALSE,
            kkt = FALSE
          )
        )
      )

summariseLME(l_t_model.trimmed , run_step=TRUE,
              write="../output_model_anovas/Mode_l_t_anova.csv")

```
 
```{r make tidy model, fig.height=3, fig.width=9, result="asis"}

l_t_model.tidy <- analyseModel(l_t_model.trimmed,
                                write="../output/Mode_l_t"
                                )
l_t_model.tidy$table

```

```{r do pairwise analysis, fig.height=3, fig.width=9, warning = FALSE, message = FALSE, tidy = TRUE}

charts <- getModelFixedFX(
  my_equation =
    l_t ~ mode + (1 | speaker) + (1 | fin_phon) + (1 | gender) + (1 | prompt),
  my_data = m_corpus.trimmed,
  write="../output/Mode_l_t"
)
charts$slopes


```
