---
title: "Analysis of PNs - Overview of *Foot* Effects on Alignment"
author: "Antoin Rodgers"
date: "11/02/2020"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


```{r message=FALSE, warning=TRUE, include=FALSE}
# Get packages from library.
require("tidyverse")
require("broom")
require("styler")
require("lmerTest")
require("optimx")
require("sjPlot")
require("sjmisc")
require("ggplot2")
require("hablar")
require("ggpubr")
require("MuMIn")
require("RColorBrewer")
require("mefa4")


library(tidyverse)
library(broom)
library(styler)
library(lmerTest)
library(optimx)
library(sjPlot)
library(sjmisc)
library(ggplot2)
library(hablar)
library(ggpubr)
library(MuMIn)
library(RColorBrewer)
library(mefa4)

## set up graphic defaults
options(ggplot2.palette="Set2")

theme_set(
    theme_minimal(base_size = 10)
)
```


Create data tbls
```{r message=FALSE, warning=TRUE, include=FALSE}
# Get A_corpus data
SR_PN_corpus <- read_csv("../data/a_corpus.csv") %>%
    filter(code %notin% c("F15_A1422_1", "M10_A2422_1", "F5_H0422_2")) %>% # remove surplus reps for balance
    filter(
        stim %in% c("A0131",
                    "A0221",
                    "A0321",
                    "H0422",
                    "A1422",
                    "A2422",
                    "A3422"
                    ),
        cur_foot == 1,
        substr(stim, 2, 4) == metre_ID
        ) %>%
    select(speaker, gender, stim, tot_syls, acc_phon,phr_end_t) %>%
    mutate(
        SR = 1000 * tot_syls / phr_end_t,
        stim = factor(stim,levels = unique(stim)),
        genderedDh = factor(
            ifelse(acc_phon == ">H*" & gender == "F",
                   "H*",
                   ifelse(acc_phon == ">H*" & gender == "M",
                          "L*H",
                          as.character(acc_phon)
                          )
                   ),
            levels = c("(*)", "L*", "H*", "L*H")
            )
        ) %>%
    select(-c("phr_end_t", "tot_syls")) %>%
    convert(fct(speaker:stim)) %>% 
    mutate(acc_phon = factor(acc_phon,
                              levels = c("(*)", "L*", "H*", ">H*", "L*H")
                              )
           ) %>% 
    mutate(stim = factor(stim, levels = unique(stim)))



```


# Speech rate and PNs in Foot conditions

```{r}
# get speech rate (SR) data.
SR_meansData <- full_join(
    select(SR_PN_corpus, speaker, gender, acc_phon) %>%
        group_by(speaker, gender, acc_phon) %>%
        summarise(accCount = n()) %>%
        spread(acc_phon, accCount) %>%
        replace(., is.na(.), 0) %>%
        rename(
            "LH" = "L*H", "dH" = ">H*", "H" = "H*", "L" = "L*", "none" = "(*)"
            ) %>% 
        mutate(
            totalAccs = sum(LH, dH, H, L, none),
            LH_pc = LH / totalAccs,
            H_pc = (H) / totalAccs,
            dH_pc = (dH) / totalAccs
            ),
    select(SR_PN_corpus, speaker, SR) %>%
        group_by(speaker) %>%
        summarise(meanSpRate = mean(SR)),
    by = "speaker")

SR_meansData
```




```{r echo=FALSE, fig.height=4, fig.width=9}
# plot graphs
plot1 <- ggplot(SR_meansData %>% filter(LH >0)) +
  geom_text(mapping = aes(
    x = meanSpRate, y = LH_pc,
    col = gender, label = speaker
  )) +
  geom_smooth(method = "lm", mapping = aes(x = meanSpRate, y = LH_pc)) +
  ggtitle("L*H ~ mean SR in PN data") +
  labs(x = "speech rate (syls/sec)", y = "% occurrence of L*H") +
    coord_cartesian(ylim = c(0, 1), xlim = c(4.75,6.5)) +
    scale_y_continuous(labels = scales::percent)

plot2 <- ggplot(SR_meansData %>% filter(H >0)) +
  geom_text(mapping = aes(
    x = meanSpRate, y = H_pc,
    col = gender, label = speaker
  )) +
  geom_smooth(method = "lm", mapping = aes(x = meanSpRate, y = H_pc)) +
  ggtitle("H* ~ mean SR in PN data") +
  labs(x = "speech rate (syls/sec)", y = "% occurrence of H*") +
    coord_cartesian(ylim = c(0, 1), xlim = c(4.75,6.5)) +
    scale_y_continuous(labels = scales::percent)


plot3 <- ggplot(SR_PN_corpus) +
  geom_boxplot(mapping = aes(x = gender, y = SR, col = gender)) +
  ggtitle("SR per utterance (PNs)") +
  labs(x = "Gender", y = "Speech rate (syls/sec)")

plots = ggarrange(plot1,
                  plot2,
                  ncol = 2,
                  common.legend = TRUE,
                  legend = "right"
                  )
ggsave("../figures/PN_SR.png", plots, height = 5, width = 11)
plots
```

```{r echo=FALSE, fig.height=4, fig.width=5}
plot3


```

LM analysis of gendered >H* and SR
```{r}
p = vector(mode = "numeric", 4)
SR_lm_LH <- lm(meanSpRate~LH_pc, data = SR_meansData[SR_meansData$LH > 0,])
print(summary(SR_lm_LH))
p[1] = summary(SR_lm_LH)$coefficients[2,4]
temp <- SR_meansData[SR_meansData$LH > 0,] 
SR_LH = cor(temp$meanSpRate, temp$LH_pc)
cat("pearson correlation = ", SR_LH, sep = "")


SR_lm_H <- lm(meanSpRate~H_pc, data = SR_meansData[SR_meansData$H > 0,])
print(summary(SR_lm_H))
p[2] = summary(SR_lm_H)$coefficients[2,4]
temp <- SR_meansData[SR_meansData$H > 0,] 
SR_H = cor(temp$meanSpRate, temp$H_pc)
cat("pearson correlation = ", SR_H, sep = "")

```



# Speech rate and PNs in Foot conditions using Gendered >H* hypothesis
```{r}
# get speech rate (SR) data.
SR_meansData_GDH <- full_join(
    select(SR_PN_corpus, speaker, gender, genderedDh) %>%
        group_by(speaker, gender, genderedDh) %>%
        summarise(accCount = n()) %>%
        spread(genderedDh, accCount) %>%
        replace(., is.na(.), 0) %>%
        rename(
            "LH" = "L*H", "H" = "H*", "L" = "L*", "none" = "(*)"
            ) %>% 
        mutate(
            totalAccs = sum(LH, H, L, none),
            LH_pc = LH / totalAccs,
            H_pc = (H) / totalAccs
            ),
    select(SR_PN_corpus, speaker, SR) %>%
        group_by(speaker) %>%
        summarise(meanSpRate = mean(SR)),
    by = "speaker")

SR_meansData_GDH
```



```{r echo=FALSE, fig.height=4, fig.width=9}
# plot graphs
plot1 <- ggplot(SR_meansData_GDH %>% filter(LH >0)) +
  geom_text(mapping = aes(
    x = meanSpRate, y = LH_pc,
    col = gender, label = speaker
  )) +
  geom_smooth(method = "lm", mapping = aes(x = meanSpRate, y = LH_pc)) +
  ggtitle("L*H ~ SR in gendered PN data") +
  labs(x = "speech rate (syls/sec)", y = "% occurrence of L*H") +
    coord_cartesian(ylim = c(0, 1), xlim = c(4.75,6.5)) +
    scale_y_continuous(labels = scales::percent)

plot2 <- ggplot(SR_meansData_GDH %>% filter(H >0)) +
  geom_text(mapping = aes(
    x = meanSpRate, y = H_pc,
    col = gender, label = speaker
  )) +
  geom_smooth(method = "lm", mapping = aes(x = meanSpRate, y = H_pc)) +
  ggtitle("H* ~ SR in gendered PN data") +
  labs(x = "speech rate (syls/sec)", y = "% occurrence of H*") +
    coord_cartesian(ylim = c(0, 1), xlim = c(4.75, 6.5)) +
    scale_y_continuous(labels = scales::percent)

plots = ggarrange(plot1, plot2, ncol = 2, common.legend = TRUE, legend = "right")
plots
ggsave("../figures/PN_SR_GDH.png", plots, height = 5, width = 11)

```

LM analysis of gendered >H* and SR
```{r}

SR_lm_LH <- lm(meanSpRate~LH_pc, data = SR_meansData_GDH[SR_meansData_GDH$LH > 0,])
print(summary(SR_lm_LH))
p[3] = summary(SR_lm_LH)$coefficients[2,4]
temp <- SR_meansData_GDH[SR_meansData_GDH$LH > 0,] 
SR_LH_GDH = cor(temp$meanSpRate, temp$LH_pc)
cat("pearson correlation = ", SR_LH_GDH, sep = "")

SR_lm_H <- lm(meanSpRate~H_pc, data = SR_meansData_GDH[SR_meansData_GDH$H > 0,])
print(summary(SR_lm_H))
p[4] = summary(SR_lm_H)$coefficients[2,4]
temp <- SR_meansData_GDH[SR_meansData_GDH$H > 0,] 
SR_H_GDH = cor(temp$meanSpRate, temp$H_pc)
cat("pearson correlation = ", SR_H_GDH, sep = "")

```


```{r}
p.adjust(p, method = "bonferroni")
```

