---
title: "Chapter 7 - LME analysis of lh_mean_f0 ~ Mode"
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,
                      warning=FALSE,
                      message=FALSE)

# Load Functions.
source("../../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4",
    "blme"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

```

```{r load corpus, include=FALSE}
l_star_h_types = c("^[L*]H", "L*H", "L*^[H]", "^[L*H]")

# Load Corpus
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  # Select only columns for analysis
  select(
    speaker,
    gender,
    mode,
    prompt,
    acc_phon,
    fin_phon,
    lh_mean_f0) %>% 
  filter(acc_phon %in% l_star_h_types)  %>% 
  mutate(acc_phon = factor(acc_phon,
                           levels = l_star_h_types)
         )
```

- Intercepts only model without prompt is best for no singularity / convergence issues

#### `lh_mean_f0 ~ mode + (1| speaker) + (1 | gender) + (1 | fin_phon)`
```{r run initial model,  fig.height=3, fig.width=9, tidy = TRUE}

# run model
lh_mean_f0_model <- lmer(
  lh_mean_f0 ~
    mode + (1 | speaker) + (1 | gender) + (1 | fin_phon),
        data = m_corpus,
        control = lmerControl(
            optimizer = "bobyqa",
            calc.derivs = FALSE,
            optCtrl = list(
                method = "nlminb",
                starttests = FALSE,
                kkt = FALSE
            )
        )
      )

summariseLME(lh_mean_f0_model, run_step=TRUE
              #, write="../output_model_anovas/Mode_lh_mean_f0_anova.csv"
             )

```

```{r make tidy model, fig.height=2.5, fig.width=5, results="asis"}

lh_mean_f0_model.tidy <- analyseModel(lh_mean_f0_model
                                #, write="../output/Mode_lh_mean_f0"
                                )
lh_mean_f0_model.tidy$table
```

```{r do pairwise analysis, tidy = TRUE}

charts <- getModelFixedFX(
  my_equation = lh_mean_f0 ~ 
     mode + (1 | speaker) + (1 | gender) + (1 | fin_phon),
  my_data = m_corpus,
  #write="../output/Mode_lh_mean_f0",
  optimizer="bobyqa"
)
charts$slopes


```
