---
title: "Chapter 7 - LME analysis of f0_exc ~ Mode"
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,
                      warning=FALSE,
                      message=FALSE)

# Load Functions.
source("../../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

```


```{r load corpus}
l_star_h_types = c("^[L*]H", "L*H", "L*^[H]", "^[L*H]")

# Load Corpus
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  # Select only columns for analysis
  select(
    speaker,
    gender,
    mode,
    prompt,
    acc_phon,
    fin_phon,
    f0_exc) %>% 
  filter(acc_phon %in% l_star_h_types)  %>% 
  mutate(acc_phon = factor(acc_phon,
                           levels = l_star_h_types)
         )
```

### `f0_exc ~ mode + (1 + mode | speaker) + (1 | fin_phon)`

* model works without  `+ (1 | gender) + (1 | prompt)` and bobyqa optimizer

```{r run model w/o gender,  fig.height=3, fig.width=9, tidy = TRUE}

# run model
f0_exc_model <- lmer(
  f0_exc ~
    mode + (1 + mode | speaker) + (1 | fin_phon),
        data = m_corpus,
        control = lmerControl(
            optimizer = "bobyqa",
            calc.derivs = FALSE,
            optCtrl = list(
                method = "nlminb",
                starttests = FALSE,
                kkt = FALSE
                )
            )
        )


summariseLME(f0_exc_model, run_step=TRUE
             #, write="../output_model_anovas/Mode_f0_exc_anova.csv"
             )

```

```{r make tidy model, fig.height=2.5, fig.width=5,  results="asis"}

f0_exc_model.tidy <- analyseModel(f0_exc_model
                                  #, write="../output/Mode_f0_exc"
                                )

f0_exc_model.tidy$table
```

```{r do pairwise analysis, warning = FALSE, message = FALSE, tidy = TRUE}

charts <- getModelFixedFX(
  my_equation = f0_exc ~
   mode + (1 + mode | speaker) + (1 | fin_phon),
  my_data = m_corpus,
  optimizer = "bobyqa"
  #, write="../output/Mode_f0_exc"
)
charts$slopes


```
