---
title: "LME Analysis of PN and Metrical Lexical boundaries"
author: "Antoin Rodgers"
date: "18.05.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

# Get personal functions and install / load necessary packages.
source("../functions/myFunctions.R")

installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "ggeffects",
    "optimx",
    "MuMIn",
    "dfoptim",

    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    "weights",

    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

# Get  data for analysis

source("6_0_get_AH.R")

h_star_type <-  c("L*H", ">H*", "H*")
l_star_type <-  c("L*H", "L*")

pn_lex <- select(pn_lex,
                 # human factors
                 speaker, gender,
                 # phonological factors
                 acc_phon, ana_syls, foot_syls, wrd_end_syl,
                 # phonetic factors
                 wrd_end_t, speech_rate,
                 # responses
                 l_t, l_f0, h_t, h_f0, f0_exc, lh_slope) %>% 
  mutate(
    wrd_end_t_n = normalize(wrd_end_t),
    speech_rate_n = normalize(speech_rate),
    log_lh_slope = log(lh_slope)
    )

pn_lex_lh_data <- pn_lex %>%
  filter(acc_phon %in% l_star_type) %>%
  mutate(acc_phon = factor(acc_phon, levels = l_star_type))

pn_lex_h_data <- pn_lex %>%
  filter(acc_phon %in% h_star_type) %>%
  mutate(acc_phon = factor(acc_phon, levels = h_star_type)) %>%
  select(-c(l_t, l_f0))

```

```{r check levels in factors, results="asis", eval=FALSE}

star_found = F
cat("Factors for pn_lex_lh_data\n")
for (i in colnames(pn_lex_lh_data)) {
  if(length(unique(pn_lex_lh_data[[i]])) == 1){
    star =" *"
  star_found = T
  }
  else{
    star = ""
    }
  if (is.factor(pn_lex_lh_data[[eval(i)]])) {
    cat("\n", i, star,"  \tunique = ", length(unique(pn_lex_lh_data[[i]])),
        "  \tlevels = ", length(levels(pn_lex_lh_data[[i]])), sep = "")
  }
  else {
    cat("\n", i, sep = "")
    }
}
cat("\n")
if(star_found){
  cat("\n* Factor only has one level in the actual data.\n")
}
cat("\nacc_phon counts\n")
summary(pn_lex_lh_data$acc_phon)
star_found = F
cat("\n\nFactors for pn_lex_h_data\n")
for (i in colnames(pn_lex_h_data)) {
  if(length(unique(pn_lex_h_data[[i]])) == 1){
    star = " *"
  star_found = T
  }
  else{
    star = ""
    }

  if (is.factor(pn_lex_h_data[[eval(i)]])) {
    cat("\n", i, star, "  \tunique = ", length(unique(pn_lex_h_data[[i]])),
        "  \tlevels = ", length(levels(pn_lex_h_data[[i]])), sep = "")
  }
    else {
    cat("\n", i, sep = "")
    }
}
cat("\n")
if(star_found){
  cat("\n* Factor only has one level in the actual data.\n")
}
cat("\nacc_phon counts\n")
summary(pn_lex_h_data$acc_phon)

```

```{r Remove unwanted objects from environment}
rm(pn, nuc, nuc_foot, pn_lex, pn_lex, pn_ana, pn_foot, corpus, nuc_pre)
rm(stress, l_star_type, h_star_type)
```

### h\_t

```{r pn_lex_h_t Get best model, fig.height=3, fig.width=9}
pn_lex_h_t_formula = formula(
  h_t ~
    acc_phon
  + ana_syls
  + foot_syls
  + wrd_end_syl
  + gender
  + (1
     + ana_syls
     + foot_syls
     + wrd_end_syl
     | speaker)
  + (1 | speech_rate)
  + (1 | wrd_end_t)
  )   

pn_lex_h_t_mdl = lmer(
  pn_lex_h_t_formula,
  pn_lex_h_data,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

# Check optimization and update model to most optimal
pn_lex_h_t_mdl <- optLme4Mdl(pn_lex_h_t_mdl, reject_nl = T)

if(!modelIsOK(pn_lex_h_t_mdl)){
  step_result <- step(pn_lex_h_t_mdl)
  cat("Model found by step():", getModelFormula(get_model(step_result)), "\n")
}

cat("Updating formula.\n", sep ="")
pn_lex_h_t_formula = formula(
  h_t ~
    acc_phon
  + ana_syls
  + foot_syls
  + wrd_end_syl
  + gender
  + (1
  #   + ana_syls
  #   + foot_syls
  #   + wrd_end_syl
     | speaker)
  #+ (1 | speech_rate)
  #+ (1 | wrd_end_t)
  )    

pn_lex_h_t_mdl <- update(pn_lex_h_t_mdl, formula = pn_lex_h_t_formula)
# Check optimization and update model to most optimal
pn_lex_h_t_mdl <- optLme4Mdl(pn_lex_h_t_mdl)


#first <- summariseLME(pn_lex_h_t_mdl, print_summary = F)

tibble(`Summary of model` = getModelFormula(pn_lex_h_t_mdl)) %>%
        formattable(align = "l")

anova <- summariseLME(
  pn_lex_h_t_mdl
 , write = "6_4_output/pn_lex_h_t_anova.csv"
  )

adjustP_posthoc("6_4_output/",
                p.value,
                suffix_id = "_anova")

read_csv("6_4_output/pn_lex_h_t_anova.csv") %>%
  tidyStatNumbers() %>%
  formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_lex_h_t_mdl)))


```
```{r pn_lex_h_t analyse model, fig.height=2.5, fig.width=3.01, results = "asis"}
pn_lex_h_t_mdl.tidy <- analyseModel(
  pn_lex_h_t_mdl
  , write="6_4_output/pn_lex_h_t"
  , type = "est"
  , factor_matrix = TRUE
  )
```
```{r pn_lex_h_t pairwise comparison, fig.height=2.5, fig.width=3.01}
charts <- getModelFixedFX(pn_lex_h_t_mdl, write="6_4_output/pn_lex_h_t")

adjustP_posthoc("6_4_output/", p.value, suffix_id = "_b0")
adjustP_posthoc("6_4_output/", p.value, suffix_id = "_b1")

read_csv("6_4_output/pn_lex_h_t_b0.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Intercepts of model:",
                            getModelFormula(pn_lex_h_t_mdl)))

read_csv("6_4_output/pn_lex_h_t_b1.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Slopes of model:",
                            getModelFormula(pn_lex_h_t_mdl)))



```

### h\_f0

```{r pn_lex_h_f0 Get best model, fig.height=3, fig.width=9}
pn_lex_h_f0_formula = formula(
  h_f0 ~
    acc_phon
  + ana_syls
  + foot_syls
  + wrd_end_syl
  + gender
  + (1
     + ana_syls
     + foot_syls
     + wrd_end_syl
     | speaker)
  + (1 | speech_rate)
  + (1 | wrd_end_t)
  )                        

pn_lex_h_f0_mdl = lmer(
  pn_lex_h_f0_formula,
  pn_lex_h_data,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

# Check optimization and update model to most optimal
pn_lex_h_f0_mdl <- optLme4Mdl(pn_lex_h_f0_mdl, reject_nl = T)


if(!modelIsOK(pn_lex_h_f0_mdl)){
  step_result <- step(pn_lex_h_f0_mdl)
  cat("Model found by step():", getModelFormula(get_model(step_result)), "\n")
}

cat("Updating formula.\n", sep ="")
pn_lex_h_f0_formula = formula(
  h_f0 ~
    acc_phon
  + ana_syls
  + foot_syls
  + wrd_end_syl
  + gender
  + (1
     + ana_syls
     + foot_syls
     + wrd_end_syl
     | speaker)
 # + (1 | speech_rate)
 # + (1 | wrd_end_t)
  )  
pn_lex_h_f0_mdl <- update(pn_lex_h_f0_mdl, formula = pn_lex_h_f0_formula)
pn_lex_h_f0_mdl <- optLme4Mdl(pn_lex_h_f0_mdl, reject_nl = T)

#first <- summariseLME(pn_lex_h_f0_mdl, print_summary = F)

anova <- summariseLME(
  pn_lex_h_f0_mdl
 , write = "6_4_output/pn_lex_h_f0_anova.csv"
  )

adjustP_posthoc("6_4_output/",
                p.value,
                suffix_id = "_anova")

read_csv("6_4_output/pn_lex_h_f0_anova.csv") %>%
  tidyStatNumbers() %>%
  formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_lex_h_f0_mdl)))


```
```{r pn_lex_h_f0 analyse model, fig.height=2.5, fig.width=3.01, results = "asis"}
pn_lex_h_f0_mdl.tidy <- analyseModel(
  pn_lex_h_f0_mdl
  , write="6_4_output/pn_lex_h_f0"
  , type = "est"
  , factor_matrix = TRUE
  )
```
```{r pn_lex_h_f0 pairwise comparison, fig.height=2.5, fig.width=3.01}
charts <- getModelFixedFX(pn_lex_h_f0_mdl, write="6_4_output/pn_lex_h_f0")

adjustP_posthoc("6_4_output/", p.value, suffix_id = "_b0")
adjustP_posthoc("6_4_output/", p.value, suffix_id = "_b1")

read_csv("6_4_output/pn_lex_h_f0_b0.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Intercepts of model:",
                            getModelFormula(pn_lex_h_f0_mdl)))

read_csv("6_4_output/pn_lex_h_f0_b1.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Slopes of model:",
                            getModelFormula(pn_lex_h_f0_mdl)))

```

### f0\_exc

```{r pn_lex_f0_exc Get best model, fig.height=3, fig.width=9}
pn_lex_f0_exc_formula = formula(
  f0_exc ~ 
    ana_syls
  + foot_syls
  + wrd_end_syl
  + gender
  + (1
     + ana_syls
     + foot_syls
     + wrd_end_syl
     | speaker)
  + (1 | speech_rate)
  + (1 | wrd_end_t)
  )

pn_lex_f0_exc_mdl = lmer(
  pn_lex_f0_exc_formula,
  pn_lex_lh_data,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

# Check optimization and update model to most optimal
pn_lex_f0_exc_mdl <- optLme4Mdl(pn_lex_f0_exc_mdl, reject_nl = T)

if(!modelIsOK(pn_lex_f0_exc_mdl)){
  step_result <- step(pn_lex_f0_exc_mdl)
  cat("Model found by step():", getModelFormula(get_model(step_result)), "\n")
}


cat("Updating formula.\n", sep ="")
pn_lex_f0_exc_formula = formula(
  f0_exc ~ 
    ana_syls
  + foot_syls
  + wrd_end_syl
  + gender
  + (1
 #   + ana_syls
 #   + foot_syls
     + wrd_end_syl
     | speaker)
  #+ (1 | speech_rate)
 # + (1 | wrd_end_t)
  )
pn_lex_f0_exc_mdl <- update(pn_lex_f0_exc_mdl,
                             formula = pn_lex_f0_exc_formula)

pn_lex_f0_exc_mdl <- optLme4Mdl(pn_lex_f0_exc_mdl, reject_nl = T)

# updating model with new lmercontrol()
pn_lex_f0_exc_mdl <- update(pn_lex_f0_exc_mdl,
                            control = lmerControl(
                              optimizer = "nloptwrap",
                              optCtrl = list(
                                algorithm = "NLOPT_LN_COBYLA",
                                maxfun = 1e9,
                                maxeval = 1e7,
                                xtol_abs = 1e-9,
                                ftol_abs = 1e-9
                              )
                            ))

first <- summariseLME(pn_lex_f0_exc_mdl, print_summary = F)

# model needs trimming
sd_threshold = 9
cat("\nTrimming data with residual sd > ", sd_threshold, ".\n", sep ="")
pn_lex_f0_exc_data.trimmed <-
  pn_lex_lh_data %>%
  filter(abs(scale(resid(pn_lex_f0_exc_mdl))) <= sd_threshold)

pn_lex_f0_exc_mdl.trimmed <- update(pn_lex_f0_exc_mdl,
                             data = pn_lex_f0_exc_data.trimmed)

pn_lex_f0_exc_mdl.trimmed <- optLme4Mdl(pn_lex_f0_exc_mdl.trimmed, reject_nl = T)

tibble(`Summary of model` = getModelFormula(pn_lex_f0_exc_mdl)) %>%
        formattable(align = "l")

anova <- summariseLME(
  pn_lex_f0_exc_mdl.trimmed,
  run_step = F
  , write = "6_4_output/pn_lex_f0_exc_anova.csv"
  )

adjustP_posthoc("6_4_output/",
                p.value,
                suffix_id = "_anova")

read_csv("6_4_output/pn_lex_f0_exc_anova.csv") %>%
  tidyStatNumbers() %>%
  formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_lex_f0_exc_mdl.trimmed)))


```
```{r pn_lex_f0_exc analyse model, fig.height=2.5, fig.width=3.01, results = "asis"}
pn_lex_f0_exc_mdl.tidy <- analyseModel(
  pn_lex_f0_exc_mdl.trimmed
  , write="6_4_output/pn_lex_f0_exc"
  , type = "est"
  , factor_matrix = TRUE
  )
```
```{r pn_lex_f0_exc pairwise comparison, fig.height=2.5, fig.width=3.01}
charts <- getModelFixedFX(pn_lex_f0_exc_mdl.trimmed,
                          write="6_4_output/pn_lex_f0_exc")

adjustP_posthoc("6_4_output/", p.value, suffix_id = "_b0")
adjustP_posthoc("6_4_output/", p.value, suffix_id = "_b1")

read_csv("6_4_output/pn_lex_f0_exc_b0.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Intercepts of model:",
                            getModelFormula(pn_lex_f0_exc_mdl.trimmed)))

read_csv("6_4_output/pn_lex_f0_exc_b1.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Slopes of model:",
                            getModelFormula(pn_lex_f0_exc_mdl.trimmed)))
```

### lh\_slope

```{r pn_lex_lh_slope Get best model, fig.height=3, fig.width=9}
pn_lex_lh_slope_formula = formula(
  log_lh_slope ~ 
    ana_syls
  + foot_syls
  + wrd_end_syl
  + gender
  + (1
     + ana_syls
     + foot_syls
     + wrd_end_syl
     | speaker)
  + (1 | speech_rate)
  + (1 | wrd_end_t)
  )   

pn_lex_lh_slope_mdl = lmer(
  pn_lex_lh_slope_formula,
  pn_lex_lh_data,
  control = lmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

# Check optimization and update model to most optimal
pn_lex_lh_slope_mdl <- optLme4Mdl(pn_lex_lh_slope_mdl, reject_nl = T)

step_result <- step(pn_lex_lh_slope_mdl)
cat("Model found by step():", getModelFormula(get_model(step_result)), "\n")

cat("Updating formula.\n", sep ="")
pn_lex_lh_slope_formula = formula(
  log_lh_slope ~ 
    ana_syls
  + foot_syls
  + wrd_end_syl
  + gender
  + (1
     + ana_syls
     + foot_syls
     + wrd_end_syl
     | speaker)
  #+ (1 | speech_rate)
  #+ (1 | wrd_end_t)
  )  

pn_lex_lh_slope_mdl <- update(pn_lex_lh_slope_mdl,
                              formula = pn_lex_lh_slope_formula)
pn_lex_lh_slope_mdl <- optLme4Mdl(pn_lex_lh_slope_mdl, reject_nl = T)

first <- summariseLME(pn_lex_lh_slope_mdl, print_summary = F)

# model needs trimming
sd_threshold = 2.5
cat("\nTrimming data with residual sd > ", sd_threshold, ".\n", sep ="")
pn_lex_lh_slope_data.trimmed <-
  pn_lex_lh_data %>%
  filter(abs(scale(resid(pn_lex_lh_slope_mdl))) <= sd_threshold)



pn_lex_lh_slope_mdl.trimmed <- update(pn_lex_lh_slope_mdl,
                              data = pn_lex_lh_slope_data.trimmed)

pn_lex_lh_slope_mdl.trimmed <- optLme4Mdl(pn_lex_lh_slope_mdl.trimmed)

tibble(`Summary of model` = getModelFormula(pn_lex_lh_slope_mdl.trimmed)) %>%
        formattable(align = "l")

anova <- summariseLME(pn_lex_lh_slope_mdl.trimmed,
                      write ="6_4_output/pn_lex_lh_slope_anova.csv")

adjustP_posthoc("6_4_output/",
                p.value,
                suffix_id = "_anova")

read_csv("6_4_output/pn_lex_lh_slope_anova.csv") %>%
  tidyStatNumbers() %>%
  formattable(caption = paste("ANOVA of model:",
                            getModelFormula(pn_lex_lh_slope_mdl.trimmed)))


```
```{r pn_lex_lh_slope analyse model, fig.height=2.5, fig.width=3.01, results = "asis"}
pn_lex_lh_slope_mdl.tidy <- analyseModel(
  pn_lex_lh_slope_mdl.trimmed
  , write="6_4_output/pn_lex_lh_slope"
  , type = "est"
  , factor_matrix = TRUE
  )
```
```{r pn_lex_lh_slope pairwise comparison, fig.height=2.5, fig.width=3.01}
charts <- getModelFixedFX(pn_lex_lh_slope_mdl.trimmed, write="6_4_output/pn_lex_lh_slope")


adjustP_posthoc("6_4_output/", p.value, suffix_id = "_b0")
adjustP_posthoc("6_4_output/", p.value, suffix_id = "_b1")

read_csv("6_4_output/pn_lex_lh_slope_b0.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Intercepts of model:",
                            getModelFormula(pn_lex_lh_slope_mdl.trimmed)))

read_csv("6_4_output/pn_lex_lh_slope_b1.csv") %>%
  tidyStatNumbers() %>%
formattable(caption = paste("Slopes of model:",
                            getModelFormula(pn_lex_lh_slope_mdl.trimmed)))


```

