---
title: 'Chapter 6. Analysis of Form: Lexical and Metrical Effects'
author: "Antoin Eoin Rodgers"
date: '2022-07-05'
output:
  html_document: default
subtitle: 'Appendix: Posthoc ANOVA p value adjustment'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

source("../functions/myFunctions.R") 

installMissingPackages(c("tidyverse", "weights"))

```

Adjust all p values using false discovery rate (FDR). $\beta_0$, $\beta_1$, and model ANOVAs are processed separately.

c.f. Benjamini, Y., and Hochberg, Y. (1995). Controlling the false discovery rate: a practical and powerful approach to multiple testing. Journal of the *Royal Statistical Society Series B, **57***, 289--300. <doi:10.1111/j.2517-6161.1995.tb02031.x>. <https://www.jstor.org/stable/2346101>.

\newpage

## 1. Phonology Models
```{r Phonology models b0, results="asis"}

#### a. $\beta_0$
# adjustP_posthoc("6_2_output/",
#                 p.value,
#                 method = "none",
#                 significance = F,
#                 print = T,
#                 marginal = F,
#                 suffix_id = "_b0",)
```


```{r Phonology models b1, results="asis"}
#### b. $\beta_1$
# adjustP_posthoc("6_2_output/",
#                 p.value,
#                 method = "none",
#                 significance = F,
#                 print = T,
#                 marginal = F,
#                 suffix_id = "_b1")
```


```{r phonology model ANOVAs, results="asis"}
### c. ANOVAs
adjustP_posthoc("6_2_output/",
                `Pr(Chi)`,
                suffix_id = "_anova",
                print = TRUE)
```

\newpage

## 2. PN Phonetic Models

```{r pn phonetic models b0, results="asis"}

#### a. $\beta_0$
# adjustP_posthoc("6_4_subset_output/",
#                 p.value,
#                 method = "none",
#                 significance = F,
#                 print = T,
#                 marginal = F,
#                 suffix_id = "_b0")
```


```{r pn phonetics models b1, results="asis"}
#### b. $\beta_1$
# adjustP_posthoc("6_4_subset_output/",
#                 p.value,
#                 method = "none",
#                 significance = F,
#                 print = T,
#                 marginal = F,
#                 suffix_id = "_b1")
```


```{r pn phonetic ANOVAs, results="asis"}
### c. ANOVAs
adjustP_posthoc("6_4_subset_output/",
                p.value,
                suffix_id = "_anova",
                print = TRUE)
```

\newpage

## 3. NUC Phonetic Models


```{r nuc phonetic models b0, results="asis"}
#### a. $\beta_0$
# adjustP_posthoc("nuc_phonetic_models/",
#                 p.value,
#                 method = "none",
#                 significance = F,
#                 print = T,
#                 marginal = F,
#                 suffix_id = "_b0")
```


```{r nuc phonetics models b1, results="asis"}
#### b. $\beta_1$
# adjustP_posthoc("nuc_phonetic_models/",
#                 p.value,
#                 method = "none",
#                 significance = F,
#                 print = T,
#                 marginal = F,
#                 suffix_id = "_b1")
```


```{r nuc phonetic ANOVAs, results="asis"}
### c. ANOVAs
adjustP_posthoc("nuc_anovas/",
                p.value,
                suffix_id = "_anova",
                print = TRUE)
```


