---
title: "Visual Analysis of word boundaries in H-Corpus PNs"
author: "Antoin Rodgers"
date: "18.05.2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE,
                      warning = FALSE)

# Get personal functions and install / load necessary packages.
source("../functions/myFunctions.R")

installMissingPackages(c("tidyverse", "formattable","janitor","mefa4", "knitr"))

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 10))
```


```{r get data, include=FALSE}
# Get  data for analysis

source("Ch_06_0_get_AH_corpora.R")

syl_edges = read_csv("data/h_corpus_syl_edges.csv") %>% 
  pivot_longer(names_to = "target", cols = 1:last_col()) %>% 
  mutate(target = str_replace(target, "A0321",  "val's is in-"),
         target = str_replace(target, "H0322",  "lally's is"),
         target = str_replace(target, "H0422",  "lally's is in-"),
         target = str_replace(target, "A0423",  "valerie's is"),
         target = str_replace(target, "H1321",  "elaine was a"),
         target = str_replace(target, "H1322",  "elaina's a"))
         
         

h_star_type <-  c("H*", ">H*",  "L*H")

pn_wrd_stims <- c("A0321", "H0322",
                  "H0422", "A0423",
                  "H1321", "H1322"
                  )

pn_wrd_sent <- c(
  "val's is invalid", "lally's is valid",
  "lally's is invalid","valerie's is valid",
  "elaine was a nanny", "elaina's a nanny"
  )

pn_phr <- c(
  "val's is in-", "lally's is",
  "lally's is in-","valerie's is",
  "elaine was a", "elaina's a")

pn <- pn %>%
  select(
    sent,
    speaker,
    stim,
    acc_phon,
    wrd_end_syl,
    h_t,
    h_grand_mean_t,
    h_syl,
    h_syl_ratio,
    ana_syls
    ) %>%
    mutate(
      ana_syls = as.character(ana_syls) %>% as.numeric(),
      h_syl_ft = as.integer(h_syl) - ana_syls,
      h_syl_norm_t = h_syl_ft + h_syl_ratio - 1,
      pn_wrds = sent,
      pn_wrds = str_replace(pn_wrds, "val's is invalid", "val's is in-"),
      pn_wrds = str_replace(pn_wrds, "lally's is valid", "lally's is"),
      pn_wrds = str_replace(pn_wrds, "lally's is invalid", "lally's is in-"),
      pn_wrds = str_replace(pn_wrds, "valerie's is valid", "valerie's is"),
      pn_wrds = str_replace(pn_wrds, "elaine was a nanny", "elaine was a"),
      pn_wrds = str_replace(pn_wrds, "elaina's a nanny", "elaina's a"),
      pairing = pn_wrds,
      pairing = str_replace(pairing,
                            "^lally's is in-|^valerie's is",
                            "2. Lally's is in- | Valerie's is"),      
      pairing = str_replace(pairing,
                            "^val's is in-|^lally's is",
                            "1. Val's is in- | Lally's is"),
      pairing = str_replace(pairing,
                            "^elaine was a|^elaina's a",
                            "3. Elaine was a | Elaina's a"),
      pn_wrds = factor(pn_wrds, levels = pn_phr)
    ) 

pn_wrd_data <- pn %>%
  filter(acc_phon %in% h_star_type,
         stim %in% pn_wrd_stims) %>%
  mutate(acc_phon = factor(acc_phon, levels = h_star_type)) %>%
  arrange(pn_wrds)


pn_wrd_adj <- pn %>% 
  filter(stim %in% pn_wrd_stims) %>% 
  balancedData(stim, acc_phon,"", 11, 5) %>%
  pivot_longer(values_to = "acc_phon", cols = 2:last_col()) %>% uncount(acc_phon) %>%
  rename(acc_phon = name) %>% 
  mutate(
    pn_wrds = stim,
    pn_wrds = str_replace(pn_wrds, "A0321",  "val's is in-"),
    pn_wrds = str_replace(pn_wrds, "H0322",  "lally's is"),
    pn_wrds = str_replace(pn_wrds, "H0422",  "lally's is in-"),
    pn_wrds = str_replace(pn_wrds, "A0423",  "valerie's is"),
    pn_wrds = str_replace(pn_wrds, "H1321",  "elaine was a"),
    pn_wrds = str_replace(pn_wrds, "H1322",  "elaina's a"),
    pairing = pn_wrds,
      pairing = str_replace(pairing,
                            "^lally's is in-|^valerie's is",
                            "2. Lally's is in- | Valerie's is"),      
      pairing = str_replace(pairing,
                            "^val's is in-|^lally's is",
                            "1. Val's is in- | Lally's is"),
      pairing = str_replace(pairing,
                            "^elaine was a|^elaina's a",
                            "3. Elaine was a | Elaina's a"),
      pn_wrds = factor(pn_wrds, levels = pn_phr)
    
  )

rm(nuc, nuc_foot, pn_lex, pn_ana, pn_foot, corpus, nuc_pre)

pairing_levels <- c("1. Val's is in- | Lally's is",
                    "2. Lally's is in- | Valerie's is",
                    "3. Elaine was a | Elaina's a")

```

```{r check data}
pn %>%
  filter(pn_wrds %in% pn_phr) %>%
  mutate(acc_phon = str_replace_all(acc_phon, "([\\*\\>])", "\\\\\\1")) %>% 
  group_by(acc_phon, pn_wrds) %>%
  summarise(count = n()) %>% pivot_wider(values_from = count,
                                         names_from = acc_phon,
                                         values_fill = 1) %>%
  arrange(pn_wrds)  %>%
  adorn_totals(where = "col") %>%
  adorn_totals(where = "row") %>% 
  formattable(caption = "Distrubition of prenuclear PAs in H-corpus (raw data)")

pn_wrd_data %>%
  filter(pn_wrds %in% pn_phr) %>%
  group_by(speaker, pn_wrds) %>%
  summarise(count = n()) %>% pivot_wider(values_from = count,
                                         names_from = speaker,
                                         values_fill = 1)  %>% 
    mutate(
      pairing = pn_wrds, .after = pn_wrds) %>% 
  mutate(
      pairing = str_replace(pairing,
                            "^lally's is in-|^valerie's is",
                            "2"),      
      pairing = str_replace(pairing,
                            "^val's is in-|^lally's is",
                            "1"),
      pairing = str_replace(pairing,
                            "^elaine was a|^elaina's a",
                            "3")
  ) %>% 
  mutate(wrd_end = pn_wrds, .after = pairing) %>% 
  mutate(
      wrd_end = str_replace(wrd_end, "lally's is in-", "early"),      
      wrd_end = str_replace(wrd_end, "valerie's is", "late"),      
      wrd_end = str_replace(wrd_end, "val's is in-", "early"),
      wrd_end = str_replace(wrd_end, "lally's is", "late"),
      wrd_end = str_replace(wrd_end, "elaine was a", "early"),
      wrd_end = str_replace(wrd_end, "elaina's a", "late")
    ) %>% 
  adorn_totals(where = "col") %>%
  adorn_totals("row", fill = "") %>%
  rename(`PN phrase` = pn_wrds,
         `word boundary` = wrd_end) %>% 
  formattable(caption = "L\\*H, \\>H\\*, and H\\*")

uneven_raw <- c("lally's is in-", "valerie's is")
```


```{r check data L*H}
pn_wrd_data %>%
  filter(pn_wrds %in% pn_phr,
         acc_phon == "L*H") %>%
  group_by(speaker, pn_wrds) %>%
  summarise(count = n()) %>%
  pivot_wider(values_from = count,
              names_from = speaker,
              values_fill = 0)  %>%
  mutate(pairing = pn_wrds, .after = pn_wrds) %>%
  mutate(
    pairing = str_replace(pairing,
                          "^lally's is in-|^valerie's is",
                          "2"),
    pairing = str_replace(pairing,
                          "^val's is in-|^lally's is",
                          "1"),
    pairing = str_replace(pairing,
                          "^elaine was a|^elaina's a",
                          "3")
  ) %>%
  mutate(wrd_end = pn_wrds, .after = pairing) %>%
  mutate(
    wrd_end = str_replace(wrd_end, "lally's is in-", "early"),
    wrd_end = str_replace(wrd_end, "valerie's is", "late"),
    wrd_end = str_replace(wrd_end, "val's is in-", "early"),
    wrd_end = str_replace(wrd_end, "lally's is", "late"),
    wrd_end = str_replace(wrd_end, "elaine was a", "early"),
    wrd_end = str_replace(wrd_end, "elaina's a", "late")
  ) %>%
  adorn_totals("col") %>%
  adorn_totals("row", fill = "") %>%
  rename(`PN phrase` = pn_wrds,
         `word boundary` = wrd_end) %>%
  formattable(caption = "L\\*H only")
```

```{r Get means etc }

pn_phr <- c(
  "elaine was a",
  "lally's is in-",
  "val's is in-",
  "elaina's a",
  "valerie's is",
  "lally's is")


pn_wrd_data_sum <- pn_wrd_data %>%
  group_by(speaker, acc_phon, pn_wrds) %>%
  summarise(mean_gm_h_t = mean(h_grand_mean_t)) %>% 
  mutate(pn_wrds = factor(pn_wrds, levels = pn_phr),
      pairing = pn_wrds,
      pairing = str_replace(pairing,
                            "^lally's is in-|^valerie's is",
                            "2. Lally's is in- | Valerie's is"),      
      pairing = str_replace(pairing,
                            "^val's is in-|^lally's is",
                            "1. Val's is in- | Lally's is"),
      pairing = str_replace(pairing,
                            "^elaine was a|^elaina's a",
                            "3. Elaine was a | Elaina's a"),
      wrd_end = pn_wrds,
      wrd_end = str_replace(wrd_end, "lally's is in-", "early"),      
      wrd_end = str_replace(wrd_end, "valerie's is", "late"),      
      wrd_end = str_replace(wrd_end, "val's is in-", "early"),
      wrd_end = str_replace(wrd_end, "lally's is", "late"),
      wrd_end = str_replace(wrd_end, "elaine was a", "early"),
      wrd_end = str_replace(wrd_end, "elaina's a", "late")
      ) %>% 
  arrange(pn_wrds)

```


```{r adjusted PA distribution, fig.width = 6.1, fig.height = 3}
ggplot(data = pn_wrd_adj %>%
         mutate(pn_wrds = factor(
           pn_wrds,
           levels = c(
             "val's is in-",
             "lally's is",
             "lally's is in-",
             "valerie's is",
             "elaine was a",
             "elaina's a"
           )
         ),
         acc_phon = factor(acc_phon, levels = c("(*)", "L*", "H*", ">H*",  "L*H")),
         pairing = factor(pairing,
                          levels = pairing_levels)
         ),
  mapping = aes(x = acc_phon, fill = pn_wrds)
) +
  geom_bar(stat = "count",
           position = "dodge",
           colour = "black") +
  
  geom_text(aes(
    label = (..count..),
    vjust = -0.5
  ),
  stat = "count",
  position = position_dodge(.9),
  size = 3) +
  
  facet_wrap(vars(pairing)) +
  scale_fill_manual(
    values = c(
      brewer.pal(6, "Dark2")[2],
      brewer.pal(6, "Set2")[6],
      brewer.pal(6, "Dark2")[3],
      brewer.pal(6, "Set2")[4],
      brewer.pal(6, "Dark2")[1],
      brewer.pal(6, "Set2")[5]
    ),
    name = NULL
  ) +
  theme(
    legend.position = "bottom",
    legend.key.size = unit(0.4, "cm"),
    panel.grid.major = element_blank()
  ) +
  ylim(0, 60) +
  xlab("prenuclear pitch accent") +
  ylab("count (adjusted)") +
  labs(caption = "pitch accents per target phrase in H-corpus (adjusted)")

```


## Syllable normalised time


#### Individual Speakers (L*H only)



```{r dot plot all LsH peaks, fig.width = 6, fig.height = 8}

pn_phr_cut <- c(
  "elaine was a", "elaina's a",
  "val's is in-", "lally's is"
  )


ggplot(
  data = pn_wrd_data
  %>% filter(acc_phon == "L*H"),
  mapping = aes(x = h_syl_norm_t, fill = pn_wrds)
) +
  geom_dotplot(stat = "density", dotsize = 1.825, alpha = 0.75) +
  facet_grid(rows =  vars(speaker), cols = vars(pairing)) +
  scale_fill_manual(
    values = c(
      brewer.pal(6, "Dark2")[2],
      brewer.pal(6, "Pastel2")[6],
      brewer.pal(6, "Dark2")[3],
      brewer.pal(6, "Pastel2")[4],
      brewer.pal(6, "Dark2")[1],
      brewer.pal(6, "Pastel2")[5]
    ),
  #  breaks = pn_phr[6:1],
    name = NULL
  ) +
  theme(
    panel.border = element_rect(fill = NA, color = "grey"),
    axis.text.y=element_blank(),
    axis.title.y=element_blank(),
    legend.position = "bottom",
    legend.key.size = unit(0.75, "cm"),
    panel.grid.major.x = element_line(color = "grey",
                                      size = 0.5),
    panel.grid.minor.x = element_blank(),
  panel.grid.minor.y = element_blank(),
  panel.grid.major.y = element_blank()
  ) +
  xlim(0.2, 3.8) +
  xlab("syllable normalised time (from onset of foot)")

```

#### Individual Speakers (H* and >H*)


```{r dot plot all Hs peaks, fig.width = 6, fig.height = 8}

pn_phr_cut <- c(
  "elaine was a", "elaina's a",
  "val's is in-", "lally's is"
  )


ggplot(
  data = pn_wrd_data
  %>% filter(acc_phon %in% c("H*", ">H*")),
  mapping = aes(x = h_syl_norm_t, fill = pn_wrds)
) +
  geom_dotplot(stat = "density", dotsize = 1.825, alpha = 0.75) +
  facet_grid(rows =  vars(speaker), cols = vars(pairing)) +
  scale_fill_manual(
    values = c(
      brewer.pal(6, "Dark2")[2],
      brewer.pal(6, "Pastel2")[6],
      brewer.pal(6, "Dark2")[3],
      brewer.pal(6, "Pastel2")[4],
      brewer.pal(6, "Dark2")[1],
      brewer.pal(6, "Pastel2")[5]
    ),
  #  breaks = pn_phr[6:1],
    name = NULL
  ) +
  theme(
    panel.border = element_rect(fill = NA, color = "grey"),
    axis.text.y=element_blank(),
    axis.title.y=element_blank(),
    legend.position = "bottom",
    legend.key.size = unit(0.75, "cm"),
    panel.grid.major.x = element_line(color = "grey",
                                      size = 0.5),
    panel.grid.minor.x = element_blank(),
  panel.grid.minor.y = element_blank(),
  panel.grid.major.y = element_blank()
  ) +
  xlim(0.2, 3.8) +
  xlab("syllable normalised time (from onset of foot)")

```

#### Aggregated Times


```{r plot all PN types density, fig.width = 5, fig.height = 2.5}

pn_phr_cut <- c(
  "elaine was a", "elaina's a",
  "val's is in-", "lally's is"
  )


ggplot(
  data = pn_wrd_data %>%
        filter(pn_wrds %in% pn_phr_cut) %>%
    mutate(
      pn_wrds = factor(pn_wrds, levels = pn_phr_cut)),
  mapping = aes(x = h_syl_norm_t, fill = pn_wrds)
) +
  geom_density(stat = "density", alpha = 0.8) +
  facet_wrap(vars(pairing)) +
  scale_fill_manual(
    values = c(
      brewer.pal(6, "Dark2")[2],
      brewer.pal(6, "Set2")[6],
      brewer.pal(6, "Dark2")[3],
      brewer.pal(6, "Set2")[4],
      brewer.pal(6, "Dark2")[1],
      brewer.pal(6, "Set2")[5]
    ),
  #  breaks = pn_phr[6:1],
    name = NULL
  ) +
  theme(
    legend.position = "right",
    legend.key.size = unit(0.4, "cm"),
    panel.grid.major.x = element_line(color = "grey",
                                      size = 0.5),
    panel.grid.minor.x = element_blank()
  ) +
  xlim(0, 3) +
  xlab("syllable normalised time (from onset of foot)") +
  labs(caption = "(all utterances, syllable-normalised time)",
       title = "PN peak timing of L*H, >H*, and H* (raw data)")
```

```{r plot L star H PN density all utterances, fig.width = 3.5, fig.height = 2.5}
ggplot(
  data = pn_wrd_data %>%
        filter(pn_wrds %in% pn_phr_cut[1:2],
        acc_phon == "L*H"
        ) %>% 
    mutate(
      pn_wrds = factor(pn_wrds, levels = pn_phr_cut)),
  mapping = aes(x = h_syl_norm_t, fill = pn_wrds)
) +
  geom_density(stat = "density", alpha = 0.8) +
 # facet_wrap(vars(pairing)) +
  scale_fill_manual(
    values = c(
      brewer.pal(6, "Dark2")[2],
      brewer.pal(6, "Set2")[6],
      brewer.pal(6, "Dark2")[3],
      brewer.pal(6, "Set2")[4],
      brewer.pal(6, "Dark2")[1],
      brewer.pal(6, "Set2")[5]
    ),
  #  breaks = pn_phr[6:1],
    name = NULL
  ) +
  theme(
    legend.position = "right",
    legend.key.size = unit(0.4, "cm"),
    panel.grid.major.x = element_line(color = "grey",
                                      size = 0.5),
    panel.grid.minor.x = element_blank()
  ) +
  xlim(0, 3) +
  xlab("syllable normalised time (from onset of foot)") +
  labs(caption = "(all utterances, not balanced)",
       title = "PN peak timing of L*H (raw data)")
```

## Grand mean time

```{r plot peak LsH PN density 1 gmt, fig.width = 3.5, fig.height = 2.2}

pn_wrd_data %>%
  filter(pn_wrds %in% pn_phr_cut[3:4],
         acc_phon == "L*H") %>%
  
  group_by(speaker, pn_wrds) %>%
  summarise(count = n()) %>%
  pivot_wider(values_from = count,
              names_from = speaker,
              values_fill = 0) %>%
  formattable(caption = "Due to unequal distribition, only using tokens from speakers with at least 4 tokens for each utterance.")



ggplot(
  data = pn_wrd_data %>%
    filter(
      pn_wrds %in% pn_phr_cut[3],
      speaker %in% c("F5", "F6", "F12", "F15", "F16", "F17", "M10"),
      acc_phon == "L*H"
    ) %>%
    mutate(pn_wrds = factor(pn_wrds, levels = pn_phr_cut)),
  mapping = aes(x = h_grand_mean_t, fill = pn_wrds)
) +
  geom_dotplot(stat = "density",
               fill = brewer.pal(3, "Dark2")[2]) +
  geom_density(stat = "density",
               fill = brewer.pal(3, "Set2")[2],
               alpha = 0.7) +
  geom_vline(xintercept = 0, size = 0.5) +
  geom_vline(xintercept = 338, size = 0.5) +
  geom_vline(xintercept = 338 + 128, size = 0.5) +
  geom_vline(xintercept = 338 + 128 + 114, size = 0.5) +
  
  annotate(
    "rect",
    xmin = 0,
    xmax = 338,
    ymin = 0,
    ymax = 0.04,
    fill = brewer.pal(3, "Pastel2")[2],
    alpha = 0.25
  ) +
  
  annotate(
    "text",
    x = c(338 / 2,
          338 + 128 / 2,
          338 + 128 + 114 / 2),
    y =  0.04 * 0.94,
    
    label = c("Val's", "is", "in")
  ) +
  
  theme(
    legend.position = "right",
    legend.key.size = unit(0.4, "cm"),
    panel.grid.major.x = element_line(color = "grey", size = 0.5)
  ) +
  xlim(0, 550) +
  ylim(0, 0.04) +
  xlab("grand mean syllable-normalised time (ms)") +
  ylab("density")# +
 # labs(caption = "Peak time of L*H in \"Val's is in-\" (excl. M4, M5, M8, M9)" )




ggplot(
  data = pn_wrd_data %>%
    filter(
      pn_wrds %in% pn_phr_cut[3],
      speaker %in% c("F6", "F12", "F15", "F16", "F17", "M5", "M8", "M10"),
      acc_phon == "L*H"
    ) %>%
    mutate(pn_wrds = factor(pn_wrds, levels = pn_phr_cut)),
  mapping = aes(x = h_grand_mean_t, fill = pn_wrds)
) +
  geom_dotplot(stat = "density",
               fill = brewer.pal(6, "Dark2")[6]) +
  geom_density(stat = "density",
               fill = brewer.pal(6, "Set2")[6],
               alpha = 0.5) +
  
  geom_vline(xintercept = 0, size = 0.5) +
  geom_vline(xintercept = 218, size = 0.5) +
  geom_vline(xintercept = 218 + 176, size = 0.5) +
  geom_vline(xintercept = 218 + 176 + 120, size = 0.5) +
  
  annotate(
    "rect",
    xmin = 0,
    xmax = 218,
    ymin = 0,
    ymax = 0.04,
    fill = brewer.pal(6, "Pastel2")[6],
    alpha = 0.25
  ) +
  
  annotate(
    "text",
    x = c(218 / 2,
          218 + 176 / 2,
          218 + 176 + 120 / 2),
    y =  0.04 * 0.94,
    
    label = c("Lall-", "y's", "is")
  ) +
  
  theme(
    legend.position = "right",
    legend.key.size = unit(0.4, "cm"),
    panel.grid.major.x = element_line(color = "grey", size = 0.5)
  ) +
  xlim(0, 550) +
  ylim(0, 0.04) +
  xlab("grand mean syllable-normalised time (ms)") +
  ylab("density")# +
 # labs(caption = "Peak time of L*H in \"Lally's is-\" (excl. M4, M5, M9)", )


```

```{r plot peak LsH PN density 2 gmt, fig.width = 3.5, fig.height = 2.2}
pn_phr <- c(
  "lally's is in-",
  "valerie's is")

pn_wrd_data %>%
    filter(pn_wrds %in% pn_phr[1:2],
           acc_phon == "L*H"
    ) %>% 

  group_by(speaker, pn_wrds) %>% 
  summarise(count = n()) %>% 
  pivot_wider(values_from = count,
              names_from = speaker,
              values_fill = 0) %>% 
  formattable(caption = "Due to unequal distribition, results below not reliable.")

ggplot(
  data = pn_wrd_data %>%
        filter(pn_wrds %in% pn_phr[1],
           speaker %notin% c("F5", "M9"),
           acc_phon == "L*H"
    ) %>% 
    mutate(
      pn_wrds = factor(pn_wrds, levels = pn_phr)),
  mapping = aes(x = h_grand_mean_t, fill = pn_wrds)
) +
  geom_dotplot(stat = "density",
               fill = brewer.pal(3, "Dark2")[3]) +
    geom_density(stat = "density",
               fill = brewer.pal(3, "Set2")[3], alpha = 0.5) +
  geom_vline(xintercept = 0, size = 0.5) +
  geom_vline(xintercept = 214, size = 0.5) +
  geom_vline(xintercept = 214+176, size = 0.5) +
  geom_vline(xintercept = 214+176+127, size = 0.5) +
  geom_vline(xintercept = 214+176+127+121, size = 0.5) +
  
    annotate("rect", xmin = 0, xmax = 218, ymin = 0, ymax = 0.016,
           fill = brewer.pal(3, "Pastel2")[3],
           alpha = 0.25) +
  
    annotate("text",
           x = c(214/2,
                 214 + 176 / 2,
                 214 + 176 + 127 / 2,
                 214+  176 + 127 + 121 / 2),
           y =  0.016 * 0.94,
           
           label = c("Lall-", "y's", "is", "in-")) +
  
  
  theme(
    legend.position = "right",
    legend.key.size = unit(0.4, "cm"),
    panel.grid.major.x = element_line(color = "grey", size = 0.5)
  ) +
  xlim(0, 600) +
  ylim(0, 0.016) +
  xlab("grand mean syllable-normalised time (ms)") +
  ylab("density")# +
 # labs(caption = "Peak time in \"Lally's is in-\" (excl. F5, M9)")



ggplot(
  data = pn_wrd_data %>%
        filter(pn_wrds %in% pn_phr[2],
           speaker %in% c("F6", "F15", "F16", "M5", "M10"),
           acc_phon == "L*H") %>% 
    mutate(
      pn_wrds = factor(pn_wrds, levels = pn_phr)),
  mapping = aes(x = h_grand_mean_t, fill = pn_wrds)
) +
  geom_dotplot(stat = "density",
               fill = brewer.pal(6, "Dark2")[4]) +
    geom_density(stat = "density",
               fill = brewer.pal(6, "Set2")[4], alpha = 0.5) +
  geom_vline(xintercept = 0, size = 0.5) +
  geom_vline(xintercept = 210, size = 0.5) +
  geom_vline(xintercept = 210+47, size = 0.5) +
  geom_vline(xintercept = 210+47+208, size = 0.5) +
  geom_vline(xintercept = 210+47+208+122, size = 0.5) +
  
      annotate("rect", xmin = 0, xmax = 208, ymin = 0, ymax = 0.016,
           fill = brewer.pal(6, "Pastel2")[4],
           alpha = 0.25) +
  
    annotate("text",
           x = c(210/2,
                 210 + 47 / 2,
                 210 + 47 + 208 / 2,
                 210+  47 + 208 + 122 / 2),
           y =  0.016 * 0.94,
           
           label = c("Val-", "e-", "rie's", "is")) +
  
  theme(
    legend.position = "right",
    legend.key.size = unit(0.4, "cm"),
    panel.grid.major.x = element_line(color = "grey", size = 0.5)
  ) +
  xlim(0, 600) +
  ylim(0, 0.016) +
  xlab("grand mean syllable-normalised time (ms)") +
  ylab("density")# +
 # labs(caption = "peak time in \"Valerie's is\" (F6, F15, F16, M5, M10)")


```

```{r plot peak LsH PN density 3 gmt, fig.width = 3.5, fig.height = 2.2}
pn_wrd_data %>%
  filter(pn_wrds %in% pn_phr_cut[1:2],
         acc_phon == "L*H") %>%
  
  group_by(speaker, pn_wrds) %>%
  summarise(count = n()) %>%
  pivot_wider(values_from = count,
              names_from = speaker,
              values_fill = 0) %>%
  formattable(caption = "Due to unequal distribition, only speakers with at least 4 tokens of each utterances will be included in the density plot.")


ggplot(
  data = pn_wrd_data %>%
    filter(
      pn_wrds %in% pn_phr_cut[1],
      speaker %in% c("F6", "F12", "F15", "F16", "M5", "M10"),
      acc_phon == "L*H"
    ) %>%
    mutate(pn_wrds = factor(pn_wrds, levels = pn_phr_cut)),
  mapping = aes(x = h_grand_mean_t, fill = pn_wrds)
) +
  geom_dotplot(stat = "density",
               fill = brewer.pal(3, "Dark2")[1]) +
    geom_density(stat = "density",
               fill = brewer.pal(3, "Set2")[1], alpha = 0.5) +
  geom_vline(xintercept = 0, size = 0.5) +
  geom_vline(xintercept = 67, size = 0.5) +
  geom_vline(xintercept = 67 + 254, size = 0.5) +
  geom_vline(xintercept = 67 + 254 + 139, size = 0.5) +
  geom_vline(xintercept = 67 + 254 + 139 + 55, size = 0.5) +
  
  annotate(
    "rect",
    xmin = 67,
    xmax = 67 + 254,
    ymin = 0,
    ymax = 0.01,
    fill = brewer.pal(3, "Pastel2")[1],
    alpha = 0.5
  ) +
  
  annotate(
    "text",
    x = c(67 / 2,
          67 + 254 / 2,
          67 + 254 + 139 / 2,
          67 +  254  + 139 + 55 / 2),
    y = 0.01 * 0.94,
    
    label = c("E-", "-laine", "was", "a")
  ) +
  
  theme(
    legend.position = "right",
    legend.key.size = unit(0.4, "cm"),
    panel.grid.major.x = element_line(color = "grey", size = 0.5)
  ) +

  
  xlim(0, 550) +
  ylim(0, 0.01) +
  xlab("grand mean syllable-normalised time (ms)") +
  ylab("density") # +
 # labs(caption = "Peak time of L*H in \"Elaine was a-\" (F6, F12, F15, F16, M5, M10)")

ggplot(
  data = pn_wrd_data %>%
    filter(
      pn_wrds %in% pn_phr_cut[2],
      speaker != "M9",
      acc_phon == "L*H"
    ) %>%
    mutate(pn_wrds = factor(pn_wrds, levels = pn_phr_cut)),
  mapping = aes(x = h_grand_mean_t, fill = pn_wrds)
) +
  geom_dotplot(stat = "density",
               fill = brewer.pal(6, "Dark2")[5]) +
    geom_density(stat = "density",
               fill = brewer.pal(6, "Set2")[5], alpha = 0.5) +
  geom_vline(xintercept = 0, size = 0.5) +
  geom_vline(xintercept = 68, size = 0.5) +
  geom_vline(xintercept = 68 + 211, size = 0.5) +
  geom_vline(xintercept = 68 + 211 + 157, size = 0.5) +
  geom_vline(xintercept = 68 + 211 + 157 + 55, size = 0.5) +
  
  annotate(
    "rect",
    xmin = 68,
    xmax = 68 + 211,
    ymin = 0,
    ymax = 0.01,
    fill = brewer.pal(6, "Pastel2")[5],
    alpha = 0.5
  ) +
  
  annotate(
    "text",
    x = c(68 / 2,
          68 + 211 / 2,
          68 + 211 + 157 / 2,
          68 +  211 + 157 + 55 / 2),
    y =  0.01 * 0.94,
    
    label = c("E-", "-lain-", "a's", "a")
  ) +
  theme(
    legend.position = "right",
    legend.key.size = unit(0.4, "cm"),
    panel.grid.major.x = element_line(color = "grey", size = 0.5)
  ) +
  xlim(0, 550) +
  ylim(0, 0.01) +
  xlab("grand mean syllable-normalised time (ms)") +
  ylab("density")# +
 # labs(caption = "Peak time of L*H in \"Elaina's a-\" (excl. M9)") 

```

