---
title: "Is PN Foot-Size a Good Predictor of L*H?"
author: "AERodgers"
date: "2/18/2020"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r message=FALSE, warning=FALSE, include=FALSE}
# Get personal functions and install / load necessary packages.
source("../functions/myFunctions.R")

installMissingPackages(
  c(
    # Include statistical packages.
    "lme4",
    "optimx",
    "MuMIn",
    
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Get data frames for AH analysis
source("scripts/get_AH_corpora.R")
# Add isLH column
pn_foot <- select(
  pn_foot, speaker, gender, stim, foot_syls, acc_phon, speech_rate) %>%
  mutate(isLH =
           if_else(acc_phon == "L*H",
                   TRUE,
                   FALSE))

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

p_color <- all_models_tidy ~ style(color = if_else(
  as.double(all_models_tidy) < 0.001,
  "green",
  if_else(
    as.double(all_models_tidy) < 0.01,
    "green",
    if_else(
      as.double(all_models_tidy)< 0.05,
      "green",
      "red")
    )
  )
)

```


## **L\*H PN** as fn of **foot size**
```{r echo=FALSE, warning=FALSE}
# Run GLME model statistical cur_model.
cur_model <- glmer(
  isLH ~ foot_syls + (1 | speaker),
  data = pn_foot,
  family = binomial(link = "logit"),
  # change optimizer to avoid convergence errors
  control = glmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)

null_model <- glmer(
  isLH ~ 1 + (1 | speaker),
  data = pn_foot,
  family = binomial(link = "logit"),
  # change optimizer to avoid convergence errors
  control = glmerControl(
    optimizer = "optimx",
    calc.derivs = FALSE,
    optCtrl = list(
      method = "nlminb",
      starttests = FALSE,
      kkt = FALSE
    )
  )
)
```

### Anova comparison of current model with null equivalent.

```{r echo=FALSE, warning=FALSE, fig.width=15.5/2.54, fig.height=15.5/16*9/2.54}

anova(cur_model, null_model, test="Chisq")
formattable(r.squaredGLMM(cur_model))

cur_model_tidy <- tidy(cur_model) %>%
    filter(term != "sd__(Intercept)") %>%
    AdjustPToBonferroni("", 4) %>%
    mutate(
      estimate = round(estimate, 3),
      std.error = round(std.error, 3),
      statistic = round(statistic, 3),
      p.value = round(p.value, 8),
      p.adjusted = round(p.adjusted, 8)
    ) %>%
  select(-c(group, effect)) %>%
  rename(z.value = statistic)


plot_model(
  cur_model,
  transform=NULL,
  show.intercept = TRUE,
  show.values = TRUE,
  show.p = FALSE,
  title = "isLH ~ foot size + (1 | speaker)",
  vline.color = "red",
  colors = "Black"
) +
  font_size(title = 12)

cur_model_tidy  %>%
  formattable(list(p.adjusted = formatter("span", style = p_color)))%>% mutate(
  p.value = if_else(p.value < 0.001,
                    as.character(scientific(p.value)),
                    as.character(round(p.value, 3))),
  p.adjusted = if_else(
    p.adjusted < 0.001,
    as.character(scientific(p.adjusted)),
    as.character(round(p.adjusted, 3))
  )
)

print(summary(cur_model))

```

## pairwise comparisons
```{r echo=FALSE, paged.print=FALSE}
# Get intercepts and pairwise comparisons for each foot size condition.

# Get number of levels in target treatment variable.
curLevels <- levels(pn_foot$foot_syls)
numLevels <- length(curLevels)
all_models_tidy = tibble()

for (i in 1:(numLevels)) {
  # Test GLMM model on data.
  cur_model <- glmer(
    isLH ~ foot_syls + (1 | speaker),
    data = pn_foot,
    family = binomial(link = "logit"),
    # Change optimizer to avoid convergence errors/
    control = glmerControl(
      optimizer = "optimx",
      calc.derivs = FALSE,
      optCtrl = list(
        method = "nlminb",
        starttests = FALSE,
        kkt = FALSE
      )
    )
  )
  
  # Convert the model output into a more readable format.
  cur_model_tidy <- tidy(cur_model) %>%
    AdjustPToBonferroni("", 4) %>%
    mutate(
      estimate = round(estimate, 3),
      std.error = round(std.error, 3),
      statistic = round(statistic, 3),
      p.value = round(p.value, 8),
      p.adjusted = round(p.adjusted, 8)
    )
  
  # Prepare current model for pasting to all models output.
  # Make 'pairwise' column = intercept.
  cur_model_tidy <- cur_model_tidy %>%
    mutate(
      pairwise =
        if_else(
          term == "(Intercept)",
          "intercept",
          if_else(
            term %notin% c(
              "foot_syls1",
              "foot_syls2",
              "foot_syls3",
              "foot_syls4"),
            "N/A",
            paste("foot_syls", i, sep = "")
          )
        ),
      # change 'term' so "intercept" states the target condition name.
      term =
        if_else(term == "(Intercept)",
                paste("foot_syls", i, sep = ""),
                term)
    ) %>%
    # remove random effects detail
    filter(term != "sd__(Intercept)") %>%
    select(-group,-effect) %>%
    # rename statistic column to "z.value"
    rename(z.value = statistic)
  
  
  # make list of pairwise comparisons to keeps
  keep = ""
  for (j in i:4) {
    keep <- c(keep, paste("foot_syls", j, sep = ""))
  }
  # remove pairwise comparisons which have already been done
  cur_model_tidy <- filter(cur_model_tidy, term %in% keep)
  
  # add remaining pairwise comparisons to main tibble.
  all_models_tidy <- bind_rows(all_models_tidy, cur_model_tidy)
  
  # restructure the order of levels for next GLME cur_model.
  curLevels <- c(curLevels[2:numLevels], curLevels[1])
  pn_foot <- pn_foot %>%
    mutate(foot_syls = factor(foot_syls,
                              levels = curLevels))
  
}

# arrange tibble according to pairwise move it to first column position
all_models_tidy  <- arrange(all_models_tidy, pairwise) %>%
  relocate(pairwise) %>%
  sigCodesTidy()


b0_footSize  <- filter(all_models_tidy, pairwise == "intercept") %>%
  select(-pairwise) %>%
  rename(intercept = term) %>%
  sigCodesTidy()


b1_footSize  <-
  filter(all_models_tidy, pairwise %notin% c("intercept", "N/A")) %>%
  select(pairwise,
         term,
         estimate,
         std.error,
         z.value,
         p.value,
         p.adjusted) %>%
  rename(intercept = pairwise, slope = term) %>%
  sigCodesTidy()

```


#### Foot size as intercept ($\beta$~0~)
```{r echo=FALSE, warning=FALSE}
b0_footSize %>%
  formattable(list(p.adjusted = formatter("span",
                                          style = p_color))) %>%
  mutate(
    p.value = if_else(
      p.value < 0.001,
      as.character(scientific(p.value)),
      as.character(round(p.value, 3))
    ),
    p.adjusted = if_else(
      p.adjusted < 0.001,
      as.character(scientific(p.adjusted)),
      as.character(round(p.adjusted, 3))
    )
  ) 
```


#### Pairwise comparisons ($\beta$~1~)
```{r echo=FALSE, warning=FALSE}
b1_footSize %>%
  formattable(list(p.adjusted = formatter("span",
                                          style = p_color))) %>%
  mutate(
    p.value = if_else(
      p.value < 0.001,
      as.character(scientific(p.value)),
      as.character(round(p.value, 3))
    ),
    p.adjusted = if_else(
      p.adjusted < 0.001,
      as.character(scientific(p.adjusted)),
      as.character(round(p.adjusted, 3))
    )
  ) 
```

