---
title: "LMM Analysis of PNs"
author: "Antoin Rodgers"
date: "18.05.2022"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r message=FALSE, warning=FALSE, include=FALSE}
# Get personal functions and install / load necessary packages.
source("../functions/myFunctions.R")

installMissingPackages(
  c(
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Get data frames for AH analysis
source("get_AH_corpora.R")

# keep only grand mean values
nuc_foot <- nuc_foot %>% 
  mutate(l_t = l_grand_mean_t,
         h_t = h_grand_mean_t,
         e_t = e_grand_mean_t) %>% 
  select(-c(v_grand_mean_t, l_grand_mean_t, h_grand_mean_t, e_grand_mean_t)) 

nuc_pre <- nuc_pre %>% 
  mutate(l_t = l_grand_mean_t,
         h_t = h_grand_mean_t,
         e_t = e_grand_mean_t) %>% 
  select(-c(v_grand_mean_t, l_grand_mean_t, h_grand_mean_t, e_grand_mean_t))

pn_foot <- pn_foot %>% 
  mutate(l_t = l_grand_mean_t,
         h_t = h_grand_mean_t,
         s_t = s_grand_mean_t) %>% 
  select(-c(v_grand_mean_t, l_grand_mean_t, h_grand_mean_t, s_grand_mean_t)) 

pn_ana <- pn_ana %>% 
  mutate(l_t = l_grand_mean_t,
         h_t = h_grand_mean_t,
         s_t = s_grand_mean_t) %>% 
  select(-c(v_grand_mean_t, l_grand_mean_t, h_grand_mean_t, s_grand_mean_t)) 


# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

rm(pn, corpus, nuc)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
# Summarise continuous PN data: parameter means per speaker per condition.
pn_foot_param_sum <- param_summary(pn_foot, foot_syls, acc_phon) %>%
  mutate(foot_syls = factor(foot_syls, levels = c(1, 2, 3, 4)),
         acc_phon =  factor(acc_phon, levels = c("(*)", "L*", "H*", ">H*", "L*H"))
         ) 
pn_ana_param_sum <- param_summary(pn_ana, ana_syls, acc_phon) %>% 
   mutate(ana_syls = factor(ana_syls, levels = c(0, 1, 2, 3)),
         acc_phon =  factor(acc_phon, levels = c("H*", ">H*", "L*H"))
         )  
nuc_foot_param_sum <- param_summary(nuc_foot, foot_syls, nuc_contour, is_nucleus = TRUE) %>%
  mutate(foot_syls = factor(foot_syls, levels = c(1, 2, 3, 4)))

nuc_pre_param_sum <- param_summary(nuc_pre, pre_syls, nuc_contour, is_nucleus = TRUE) %>%
  mutate(pre_syls = factor(pre_syls, levels = c(1, 2, 3, 4)))
```


Testing visuals in R using GG plot 2 as alternative to Excel. Would be nice to be able to show good error bars / IQRs etc.
```{r}
ggplot(data = nuc_foot_param_sum) +
  geom_violin(
    aes(x=foot_syls, y=h_t, fill=nuc_contour),
       # trim=FALSE,
    draw_quantiles = c(0.25, 0.5, 0.75)
    ) +
  geom_jitter(
        aes(x=foot_syls, y=h_t, fill=nuc_contour),
      #  trim=FALSE,
    height = 0, width = 0.1
    ) +
  geom_violin(
    aes(x=foot_syls, y=l_t, fill=nuc_contour),
      #  trim=FALSE,
    draw_quantiles = c(0.25, 0.5, 0.75)
    ) +
  geom_jitter(
        aes(x=foot_syls, y=l_t, fill=nuc_contour),
     #   trim=FALSE,
    height = 0, width = 0.1
    )



ggplot(data = nuc_foot_param_sum %>% filter(nuc_contour %in% c("L*H %"))) +
  geom_smooth(
    aes(x=h_t, y=h_f0_z, fill=nuc_contour)
    ) + 
    geom_point(
    aes(x=h_t, y=h_f0_z, fill=nuc_contour)
    )

ggplot() +
  geom_smooth(data = pn_foot_param_sum %>% filter(acc_phon %in% c("L*H")),
    aes(x=h_t, y=h_f0_z, fill=acc_phon)
    ) + 
    geom_point(data = pn_foot_param_sum %>% filter(acc_phon %in% c("L*H")),
    aes(x=h_t, y=h_f0_z, fill=acc_phon)
    )
```











```{r message=FALSE, warning=FALSE, include=FALSE}
# PROCESS PN DATA
# 
#get summary of each target parameter per pa per pre_syl condition
param_means(pn_foot_param_sum, l_t, foot_syls, acc_phon) %>%
  write_csv("../output/pn_foot_l_t_means.csv")
param_means(pn_foot_param_sum, h_t, foot_syls, acc_phon) %>%
  write_csv("../output/pn_foot_h_t_means.csv")
param_means(pn_foot_param_sum, l_f0_z, foot_syls, acc_phon) %>%
  write_csv("../output/pn_foot_l_f0_means.csv")
param_means(pn_foot_param_sum, h_f0_z, foot_syls, acc_phon) %>%
  write_csv("../output/pn_foot_h_f0_means.csv")
param_means(pn_foot_param_sum, lh_dur, foot_syls, acc_phon) %>%
  write_csv("../output/pn_foot_lh_dur_means.csv")
param_means(pn_foot_param_sum, f0_exc_z, foot_syls, acc_phon) %>%
  write_csv("../output/pn_foot_exc_f0_means.csv")
param_means(pn_foot_param_sum, lh_slope, foot_syls, acc_phon) %>%
  write_csv("../output/pn_foot_lh_slope_means.csv")

#get summary of each target parameter per pa per pre_syl condition
param_means(pn_ana_param_sum, l_t, ana_syls, acc_phon) %>%
  write_csv("../output/pn_ana_l_t_means.csv")
param_means(pn_ana_param_sum, h_t, ana_syls, acc_phon) %>%
  write_csv("../output/pn_ana_h_t_means.csv")
param_means(pn_ana_param_sum, l_f0_z, ana_syls, acc_phon) %>%
  write_csv("../output/pn_ana_l_f0_means.csv")
param_means(pn_ana_param_sum, h_f0_z, ana_syls, acc_phon) %>%
  write_csv("../output/pn_ana_h_f0_means.csv")
param_means(pn_ana_param_sum, lh_dur, ana_syls, acc_phon) %>%
  write_csv("../output/pn_ana_lh_dur_means.csv")
param_means(pn_ana_param_sum, f0_exc_z, ana_syls, acc_phon) %>%
  write_csv("../output/pn_ana_exc_f0_means.csv")
param_means(pn_ana_param_sum, lh_slope, ana_syls, acc_phon) %>%
  write_csv("../output/pn_ana_lh_slope_means.csv")
```


```{r message=FALSE, warning=FALSE, include=FALSE}
# PROCESS NUCLEAR DATA
# 
# Get summary of each target parameter per pa per pre_syl condition
param_means(nuc_foot_param_sum, l_t, foot_syls, nuc_contour) %>%
  write_csv("../output/nuc_foot_l_t_means.csv")
param_means(nuc_foot_param_sum, h_t, foot_syls, nuc_contour) %>%
  write_csv("../output/nuc_foot_h_t_means.csv")
param_means(nuc_foot_param_sum, e_t, foot_syls, nuc_contour) %>%
  write_csv("../output/nuc_foot_e_t_means.csv")
param_means(nuc_foot_param_sum, he_dur, foot_syls, nuc_contour) %>%
  write_csv("../output/nuc_foot_he_dur_means.csv")
param_means(nuc_foot_param_sum, l_f0_z, foot_syls, nuc_contour) %>%
  write_csv("../output/nuc_foot_l_f0_means.csv")
param_means(nuc_foot_param_sum, h_f0_z, foot_syls, nuc_contour) %>%
  write_csv("../output/nuc_foot_h_f0_means.csv")
param_means(nuc_foot_param_sum, e_f0_z, foot_syls, nuc_contour) %>%
  write_csv("../output/nuc_foot_e_f0_means.csv")
param_means(nuc_foot_param_sum, e_f0_exc_z, foot_syls, nuc_contour) %>%
  write_csv("../output/nuc_foot_e_exc_f0_means.csv")
param_means(nuc_foot_param_sum, lh_dur, foot_syls, nuc_contour) %>%
  write_csv("../output/nuc_foot_lh_dur_means.csv")
param_means(nuc_foot_param_sum, he_dur, foot_syls, nuc_contour) %>%
  write_csv("../output/nuc_foot_he_dur_means.csv")
param_means(nuc_foot_param_sum, f0_exc_z, foot_syls, nuc_contour) %>%
  write_csv("../output/nuc_foot_exc_f0_means.csv")
param_means(nuc_foot_param_sum, lh_slope, foot_syls, nuc_contour) %>%
  write_csv("../output/nuc_foot_lh_slope_means.csv")



# Get summary of each target parameter per pa per pre_syl condition
param_means(nuc_pre_param_sum, l_t, pre_syls, nuc_contour) %>%
  write_csv("../output/nuc_pre_l_t_means.csv")
param_means(nuc_pre_param_sum, h_t, pre_syls, nuc_contour) %>%
  write_csv("../output/nuc_pre_h_t_means.csv")
param_means(nuc_pre_param_sum, e_t, pre_syls, nuc_contour) %>%
  write_csv("../output/nuc_pre_e_t_means.csv")
param_means(nuc_pre_param_sum, he_dur, pre_syls, nuc_contour) %>%
  write_csv("../output/nuc_pre_he_dur_means.csv")
param_means(nuc_pre_param_sum, l_f0_z, pre_syls, nuc_contour) %>%
  write_csv("../output/nuc_pre_l_f0_means.csv")
param_means(nuc_pre_param_sum, h_f0_z, pre_syls, nuc_contour) %>%
  write_csv("../output/nuc_pre_h_f0_means.csv")
param_means(nuc_pre_param_sum, e_f0_z, pre_syls, nuc_contour) %>%
  write_csv("../output/nuc_pre_e_f0_means.csv")
param_means(nuc_pre_param_sum, e_f0_exc_z, pre_syls, nuc_contour) %>%
  write_csv("../output/nuc_pre_e_exc_f0_means.csv")
param_means(nuc_pre_param_sum, lh_dur, pre_syls, nuc_contour) %>%
  write_csv("../output/nuc_pre_lh_dur_means.csv")
param_means(nuc_pre_param_sum, he_dur, pre_syls, nuc_contour) %>%
  write_csv("../output/nuc_pre_he_dur_means.csv")
param_means(nuc_pre_param_sum, f0_exc_z, pre_syls, nuc_contour) %>%
  write_csv("../output/nuc_pre_exc_f0_means.csv")
param_means(nuc_pre_param_sum, lh_slope, pre_syls, nuc_contour) %>%
  write_csv("../output/nuc_pre_lh_slope_means.csv")
```
