---
title: "Is PN Foot-Size a Good Predictor of L*H?"
author: "AERodgers"
date: "2/18/2022"
output:
  html_document: default
---

```{r setup, include=FALSE,}
knitr::opts_chunk$set(echo = FALSE,
                      warning = F,
                      message = F)

```


```{r message=FALSE}
# Get personal functions and install / load necessary packages.
source("../functions/myFunctions.R")

installMissingPackages(
  c(
    # Include statistical packages.
    "lmerTest",
    "blme",
    "optimx",
    "MuMIn",
    
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Get data frames for AH analysis
source("get_AH_corpora.R")
# Add isLH column
pn_foot <- select(pn_foot,
                  speaker,
                  gender,
                  foot_syls,
                  acc_phon,
                  speech_rate,
                  foot_dur) %>%
  mutate(isLH = factor(
           if_else(acc_phon == "L*H",
                   TRUE,
                   FALSE),
           levels = c(F, T)),
         isHStar = factor(
           if_else(acc_phon == "H*",
                   TRUE,
                   FALSE),
           levels = c(F, T)),
         foot_dur = foot_dur / 100,
         gender = factor(gender, levels = c("F", "M"))

         ) %>% 
  select(-acc_phon)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

p_color <- . ~ style(color =
                       if_else(. < 0.05,
                               "green",
                               if_else(. < 0.01,
                                       "orange",
                                       "red")))

rm(nuc_foot, nuc_pre, pn_lex, pn_ana, corpus, nuc, pn)


```


```{r}
# Run GLME model statistical lh_pn_re_ft_size_model.
lh_pn_re_ft_size_model <- bglmer(
  isLH ~ foot_syls + gender + (1 | speech_rate) + (1 | speaker),
  data = pn_foot,
  fixef.prior = normal(),
  family = binomial(link = "logit")
)

null_model <- bglmer(
  isLH ~ 1 + gender + (1 | speech_rate) + (1 | speaker),
  data = pn_foot,

  family = binomial(link = "logit")
)

summary(lh_pn_re_ft_size_model)
```


```{r random effect of prompt, fig.height=4, fig.width=5}
plot_model(lh_pn_re_ft_size_model,
           type="re",
           show.values = T,
           title = "random speaker intercepts")[2]
```

```{r model charts and figures, fig.width = 5.5, fig.height = 2.5, results="asis"}
cat(
  "isSingular(lh_pn_re_ft_size_model, tol=1e-5) -->",
  isSingular(lh_pn_re_ft_size_model, tol = 1e-5),
  "\n"
)



# get, save, and print ANOVA of model
anova(lh_pn_re_ft_size_model, null_model, test="Chisq") %>%
  outputChiSqResults(
    lh_pn_re_ft_size_model,
    write="output/lh_pn_re_ft_size",
    post_hoc_method = "BH"
  )

tidy_summary <- analyseModel(lh_pn_re_ft_size_model,
                             write = "output/lh_pn_re_ft_size",
                             is_GLM = TRUE,
                             type = "pred",
                             factor_matrix=TRUE)

tidy_summary$table

charts <- getModelFixedFX(
  isLH ~ foot_syls + gender + (1 | speech_rate) + (1 | speaker),
  pn_foot,
  write="output/lh_pn_re_ft_size",
  is_GLM=TRUE,
  is_separation = T
)

charts$intercepts
charts$slopes
```

```{r}
h_star_pn_re_ft_size_model <- bglmer(
  isHStar ~ foot_syls + gender + (1 | speech_rate) + (1 | speaker),
  data = pn_foot,
  fixef.prior = normal(),
  family = binomial(link = "logit")
)

summary(h_star_pn_re_ft_size_model)
```


```{r fig.height=4, fig.width=5}
plot_model(h_star_pn_re_ft_size_model,
           type="re",
           show.values = T,
           title = "random speaker intercepts")[2]
```

```{r fig.width = 5.5, fig.height = 2.5, results="asis"}
cat(
  "isSingular(h_star_pn_re_ft_size_model, tol=1e-5) -->",
  isSingular(h_star_pn_re_ft_size_model, tol = 1e-5),
  "\n"
)



# get, save, and print ANOVA of model
anova(h_star_pn_re_ft_size_model, null_model, test="Chisq") %>%
  outputChiSqResults(
    lh_pn_re_ft_size_model,
    write="output/h_star_pn_re_ft_size",
    post_hoc_method = "BH"
  )

tidy_summary <- analyseModel(h_star_pn_re_ft_size_model,
                             write = "output/h_star_pn_re_ft_size",
                             is_GLM = TRUE,
                             type = "pred",
                             factor_matrix=TRUE)

tidy_summary$table

charts <- getModelFixedFX(
  isHStar ~ foot_syls + gender + (1 | speech_rate) + (1 | speaker),
  pn_foot,
  write="output/h_star_pn_re_ft_size",
  is_GLM=TRUE,
  is_separation = T
)

charts$intercepts
charts$slopes
```
