---
title: "LMM Analysis of PNs"
author: "Antoin Rodgers"
date: "18.05.2022"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r message=FALSE, warning=FALSE, include=FALSE}
# Get personal functions and install / load necessary packages.
source("../functions/myFunctions.R")

installMissingPackages(
  c(
    # Include statistical packages.
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",

    
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "sjPlot",
    "formattable",
    "knitr",
    
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Get data frames for AH analysis
source("get_AH_corpora.R")
# Add isLH column
pn_foot <- select(pn_foot,
                  speaker,
                  gender,
                  stim,
                  init_phon,
                  foot_syls,
                  acc_phon,
                  foot_start_t,
                  foot_end_t,
                  v_onset_t,
                  l_t,
                  h_t,
                  l_f0,
                  h_f0,
                  slope_st
                  ) %>%
  mutate(excursion = h_f0 - l_f0,
         duration = h_t - l_t,
         l_t = l_t - v_onset_t,
         h_t = h_t - v_onset_t,
         foot_dur = foot_end_t - foot_start_t
         ) %>%
  select(-c(v_onset_t,
            foot_end_t,
            foot_start_t
            ))

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 14))

p_color <- all_models_tidy ~ style(color =
                                     if_else(as.double(all_models_tidy) < 0.05,
                                             "green",
                                             "red")
                                   )

rm(nuc_foot, nuc_pre, pn_lex, pn_ana, pn, corpus, nuc)
```


h_t  as a function of foot_syls in L*H
```{r fig.height=4, fig.width=12}
temp_mdl = lmer(h_t ~ foot_syls +(1 + foot_syls | speaker),
              data = pn_foot %>% 
    filter(acc_phon == "L*H") %>%  select(-acc_phon),
              control = lmerControl(
                                    optimizer = "optimx",
                                    calc.derivs = FALSE,
                                    optCtrl = list(
                                                   method = "nlminb",
                                                   starttests = FALSE,
                                                   kkt = FALSE
                                                   )
                                    )
              )




#step(temp_mdl)
drawResiduals(temp_mdl)
plot_model(temp_mdl)
tidy(anova(temp_mdl)) %>%
  mutate(p.value = round(p.value, 6),
         statistic = round(statistic, 3)) %>% 
  rename("F value" = statistic)
summary(temp_mdl)
anova(temp_mdl)
  

```

```{r echo=FALSE, fig.height=4, fig.width=6, message=TRUE, warning=TRUE}
plot_model(temp_mdl,
  title = "h_t ~ foot_syls + acc_phon + gender + (1 + foot_syls | speaker)",
  show.intercept = TRUE,
  show.values = TRUE,
  vline.color = "red",
  colors = "Black"
)

summary(temp_mdl)
anova(temp_mdl)
r.squaredGLMM(temp_mdl)
```

h_t re acc_phon
I am interpreting the mean estimates output in the foot_syl slopes by this model as essentially representing the timing of H targets once acc_phon, gender, and speaker have been taken into accout
```{r fig.height=4, fig.width=12}
temp_mdl = lmer(h_t ~ foot_syls + acc_phon + gender + (1 + foot_syls | speaker),
              data = pn_foot %>% 
                     filter(acc_phon %in% c("H*", ">H*", "L*H")) %>% 
                     mutate(acc_phon = factor(acc_phon,
                                              levels = c("H*", ">H*", "L*H"))
                                              ),
              control = lmerControl(
                                    optimizer = "optimx",
                                    calc.derivs = FALSE,
                                    optCtrl = list(
                                                   method = "nlminb",
                                                   starttests = FALSE,
                                                   kkt = FALSE
                                                   )
                                    )
              )




#step(temp_mdl)
drawResiduals(temp_mdl)
plot_model(temp_mdl)
tidy(anova(temp_mdl)) %>%
  mutate(p.value = round(p.value, 6),
         statistic = round(statistic, 3)) %>% 
  rename("F value" = statistic)
summary(temp_mdl)
anova(temp_mdl)
  

```


```{r echo=FALSE, fig.height=4, fig.width=6, message=TRUE, warning=TRUE}
plot_model(temp_mdl,
  title = "h_t ~ foot_syls + acc_phon + gender + (1 + foot_syls | speaker)",
  show.intercept = TRUE,
  show.values = TRUE,
  vline.color = "red",
  colors = "Black"
)

summary(temp_mdl)
anova(temp_mdl)
r.squaredGLMM(temp_mdl)
```
