---
title: "Chapter 7 - Analysis of Utterance Mean f0 and slope: Summary graphs and manova mean z_scores per speaker per stimulus"
author: "Antoin Rodgers"
date: "5.6.2022"
output:
  html_document: default
---

```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE)

# Load Functions.
source("../../functions/myFunctions.R") 

# Load packages.
installMissingPackages(
  c(
    # Include statistical packages.
    "performance",
    "lmerTest",
    "lme4",
    "optimx",
    "MuMIn",
    # Include packages for tidy output.
    "tidyverse",
    "broomExtra",
    "janitor",
    "sjPlot",
    "formattable",
    "knitr",
    "RColorBrewer",
    # Include packages for %in% %notin% syntactic notation
    "mefa4"
  )
)

# Set themes and colour schemes.
theme_set(theme_minimal(base_size = 11))

## set colours
mode_colours <- c("MDC" = brewer.pal(4, "Dark2")[3],
                  "MWH" = brewer.pal(4, "Dark2")[2],
                  "MYN" = brewer.pal(4, "Dark2")[1],
                  "MDQ" = brewer.pal(4, "Dark2")[4])


mode_shapes <- c("MDC" = 18,
                 "MWH" = 17,
                 "MYN" = 15,
                 "MDQ" = 16)

mode_sizes <- c("MDC" = 0.7,
                "MWH" = 0.4,
                "MYN" = 0.5,
                "MDQ" = 0.4)

pitch_accent_colours <- c("H*"     = brewer.pal(6, "Spectral")[4],
                          "L*H"    = brewer.pal(6, "Spectral")[6],
                          ">H*"    = brewer.pal(6, "Spectral")[5],
                          "^[L*]H" = brewer.pal(6, "Spectral")[3],
                          "L*^[H]" = brewer.pal(6, "Spectral")[2],
                          "^[L*H]" = brewer.pal(6, "Spectral")[1])

p_color <- all_models_tidy ~ style(color =
                                     if_else(as.double(all_models_tidy) < 0.05,
                                             "green",
                                             "red")
                                   )

# Load Corpus
m_corpus <- get_m_corpus("../data/m_corpus.csv")  %>%
  # Consolidate nuc_contour based on observation and types of register shift.
  mutate(
    nuc_contour =
      if_else(
        nuc_contour == "^[L*H %]" | nuc_contour == "^[L*H L%]",
        "^[L*H] %",
        if_else(nuc_contour == "L*^[H L%]", "L*^[H] %", nuc_contour)
      ),
    acc_phon =
      factor(
        str_replace(nuc_contour,
                    "\\s%$|\\sL%$",
                    ""),
        levels = c("H*", "L*H", ">H*", "^[L*]H", "L*^[H]", "^[L*H]")
      ),
    fin_phon = str_replace_all(fin_phon, "L%]|%]", "%")
  ) %>%
  # Select only columns for analysis
  select(
    speaker,
    gender,
    stim,
    mode,
    prompt,
    phr_phon,
    utt_slope,
    utt_mean_f0,
    utt_slope_z,
    utt_mean_f0_z
  )

# Get mean slope and f0_z per speaker per stimulus.
m_corpus_summary <- m_corpus %>%
  group_by(speaker, stim) %>%
  summarise(
    mean_slope_z = round(mean(utt_slope_z), 3),
    mean_f0_z = round(mean(utt_mean_f0_z), 3),
    .groups = "keep"
  ) %>%
  rename(mode = stim) %>%
  mutate(mode = substr(mode, 1, 3),
         mode = factor(mode, levels = c("MDC", "MWH", "MYN", "MDQ"))) %>%
  ungroup()

# Add extra data point for missing M9 data using mean values for M9 MDQ params.
# (Aim: balance data)
m_corpus_summary <-  m_corpus_summary %>%
  add_row(
    m_corpus_summary %>%
      filter(mode == "MDQ", speaker == "M9") %>%
      adorn_totals(name ="mean") %>%
      mutate(
        across(where(is.numeric),
               ~ replace(., n(), .[n()] / n())),
        speaker = "M9",
        mode = "MDQ"
      ) %>%
      filter(row_number() == 3)
  ) %>%
  mutate(speaker = factor(speaker, levels = unique(speaker)),
         mode = factor(mode, levels = c("MDC", "MWH", "MYN", "MDQ"))) %>%
  arrange(mode)

```

## Density plot of mode by utterance contour

### All parameters
```{r, fig.width=5.5, fig.height=4}
compare <- c("MDC","MWH", "MYN", "MDQ")

ggplot(m_corpus_summary %>% filter(mode %in% compare),
       aes(y=mean_f0_z,
           x=mean_slope_z,
           shape=mode,
           color=mode,
           size=mode)) +
  scale_color_manual(values = mode_colours) +
  scale_shape_manual(values = mode_shapes) +
  scale_size_manual(values = mode_sizes) +
  geom_density_2d(alpha=0.5) +
  geom_point(size = 1.5) +
  xlim(-5, 5) +
  ylim(-3, 3) +
  ggtitle(label = "mean F0 and mean slope z-score per speaker per stimulus",
          subtitle = paste("(",paste(compare, collapse=", "),")",sep = "")
          )

manova(cbind(mean_f0_z, mean_slope_z) ~ mode,
       data = m_corpus_summary %>% filter(mode %in% compare)) %>%
  tidy()  %>%
  bonferroniAdjust("", 7) %>%
    mutate(
    df = round(df, 3),
    pillai = round(pillai, 2),
    statistic = round(statistic, 3),
    den.df = round(den.df),
    
    p.adjusted = round(p.adjusted, 4)
  ) %>% 
  rename(`approx F` = statistic) %>% 
  formattable(caption = paste("Manova: (mean_f0_z, mean_slope_z) ~ mode, where mode = ",paste(compare, collapse=", "), sep = ""),
              list(p.adjusted = formatter("span", style = p_color))) %>%
  mutate(
    p.value = if_else(
      p.value < 0.001,
      as.character(scientific(p.value)),
      as.character(round(p.value, 4))
    ),
    p.adjusted = if_else(
      p.adjusted < 0.001,
      as.character(scientific(p.adjusted, digits=2)),
      as.character(round(p.adjusted, 4)),
    )
  ) %>%
  mutate(across(everything(),  ~  replace(., is.na(.), "")))

```

### Comparing MDC and MDQ

```{r, fig.width=5.5, fig.height=4}
# Density plot of mode by  contour mean f0 and slope
compare <- c("MDC","MDQ")

ggplot(m_corpus_summary %>% filter(mode %in% compare),
       aes(y=mean_f0_z,
           x=mean_slope_z,
           shape=mode,
           color=mode,
           size=mode)) +
  scale_color_manual(values = mode_colours) +
  scale_shape_manual(values = mode_shapes) +
  scale_size_manual(values = mode_sizes) +
  geom_density_2d(alpha=0.5) +
  geom_point(size = 1.5) +
  xlim(-5, 5) +
  ylim(-3, 3) +
  ggtitle(label = "mean F0 and mean slope z-score per speaker per stimulus",
          subtitle = paste("(",paste(compare, collapse=", "),")",sep = "")
          )

manova(cbind(mean_f0_z, mean_slope_z) ~ mode,
       data = m_corpus_summary %>% filter(mode %in% compare)) %>%
  tidy()  %>%
  bonferroniAdjust("", 7) %>%
    mutate(
    df = round(df, 3),
    pillai = round(pillai, 2),
    statistic = round(statistic, 3),
    den.df = round(den.df),
    
    p.adjusted = round(p.adjusted, 4)
  ) %>% 
  rename(`approx F` = statistic) %>% 
  formattable(caption = paste("Manova: (mean_f0_z, mean_slope_z) ~ mode, where mode = ",paste(compare, collapse=", "), sep = ""),
              list(p.adjusted = formatter("span", style = p_color))) %>%
  mutate(
    p.value = if_else(
      p.value < 0.001,
      as.character(scientific(p.value)),
      as.character(round(p.value, 4))
    ),
    p.adjusted = if_else(
      p.adjusted < 0.001,
      as.character(scientific(p.adjusted, digits=2)),
      as.character(round(p.adjusted, 4)),
    )
  ) %>%
  mutate(across(everything(),  ~  replace(., is.na(.), "")))

```


### Comparing MDC and MYN
```{r, fig.width=5.5, fig.height=4}
compare <- c("MDC", "MYN")

ggplot(m_corpus_summary %>% filter(mode %in% compare),
       aes(y=mean_f0_z,
           x=mean_slope_z,
           shape=mode,
           color=mode,
           size=mode)) +
  scale_color_manual(values = mode_colours) +
  scale_shape_manual(values = mode_shapes) +
  scale_size_manual(values = mode_sizes) +
  geom_density_2d(alpha=0.5) +
  geom_point(size = 1.5) +
  xlim(-5, 5) +
  ylim(-3, 3) +
  ggtitle(label = "mean F0 and mean slope z-score per speaker per stimulus",
          subtitle = paste("(",paste(compare, collapse=", "),")",sep = "")
          )

manova(cbind(mean_f0_z, mean_slope_z) ~ mode,
       data = m_corpus_summary %>% filter(mode %in% compare)) %>%
  tidy()  %>%
  bonferroniAdjust("", 7) %>%
    mutate(
    df = round(df, 3),
    pillai = round(pillai, 2),
    statistic = round(statistic, 3),
    den.df = round(den.df),
    
    p.adjusted = round(p.adjusted, 4)
  ) %>% 
  rename(`approx F` = statistic) %>% 
  formattable(caption = paste("Manova: (mean_f0_z, mean_slope_z) ~ mode, where mode = ",paste(compare, collapse=", "), sep = ""),
              list(p.adjusted = formatter("span", style = p_color))) %>%
  mutate(
    p.value = if_else(
      p.value < 0.001,
      as.character(scientific(p.value)),
      as.character(round(p.value, 4))
    ),
    p.adjusted = if_else(
      p.adjusted < 0.001,
      as.character(scientific(p.adjusted, digits=2)),
      as.character(round(p.adjusted, 4)),
    )
  ) %>%
  mutate(across(everything(),  ~  replace(., is.na(.), "")))

```

### Comparing MDC and MWH
```{r, fig.width=5.5, fig.height=4}
compare <- c("MDC","MWH")


ggplot(m_corpus_summary %>% filter(mode %in% compare),
       aes(y=mean_f0_z,
           x=mean_slope_z,
           shape=mode,
           color=mode,
           size=mode)) +
  scale_color_manual(values = mode_colours) +
  scale_shape_manual(values = mode_shapes) +
  scale_size_manual(values = mode_sizes) +
  geom_density_2d(alpha=0.5) +
  geom_point(size = 1.5) +
  xlim(-5, 5) +
  ylim(-3, 3) +
  ggtitle(label = "mean F0 and mean slope z-score per speaker per stimulus",
          subtitle = paste("(",paste(compare, collapse=", "),")",sep = "")
          )

manova(cbind(mean_f0_z, mean_slope_z) ~ mode,
       data = m_corpus_summary %>% filter(mode %in% compare)) %>%
  tidy()  %>%
  bonferroniAdjust("", 7) %>%
    mutate(
    df = round(df, 3),
    pillai = round(pillai, 2),
    statistic = round(statistic, 3),
    den.df = round(den.df),
    
    p.adjusted = round(p.adjusted, 4)
  ) %>% 
  rename(`approx F` = statistic) %>% 
  formattable(caption = paste("Manova: (mean_f0_z, mean_slope_z) ~ mode, where mode = ",paste(compare, collapse=", "), sep = ""),
              list(p.adjusted = formatter("span", style = p_color))) %>%
  mutate(
    p.value = if_else(
      p.value < 0.001,
      as.character(scientific(p.value)),
      as.character(round(p.value, 4))
    ),
    p.adjusted = if_else(
      p.adjusted < 0.001,
      as.character(scientific(p.adjusted, digits=2)),
      as.character(round(p.adjusted, 4)),
    )
  ) %>%
  mutate(across(everything(),  ~  replace(., is.na(.), "")))

```

### Comparing MWH and MYN
```{r, fig.width=5.5, fig.height=4}
compare <- c("MWH", "MYN")

ggplot(m_corpus_summary %>% filter(mode %in% compare),
       aes(y=mean_f0_z,
           x=mean_slope_z,
           shape=mode,
           color=mode,
           size=mode)) +
  scale_color_manual(values = mode_colours) +
  scale_shape_manual(values = mode_shapes) +
  scale_size_manual(values = mode_sizes) +
  geom_density_2d(alpha=0.5) +
  geom_point(size = 1.5) +
  xlim(-5, 5) +
  ylim(-3, 3) +
  ggtitle(label = "mean F0 and mean slope z-score per speaker per stimulus",
          subtitle = paste("(",paste(compare, collapse=", "),")",sep = "")
          )

manova(cbind(mean_f0_z, mean_slope_z) ~ mode,
       data = m_corpus_summary %>% filter(mode %in% compare)) %>%
  tidy()  %>%
  bonferroniAdjust("", 7) %>%
    mutate(
    df = round(df, 3),
    pillai = round(pillai, 2),
    statistic = round(statistic, 3),
    den.df = round(den.df),
    
    p.adjusted = round(p.adjusted, 4)
  ) %>% 
  rename(`approx F` = statistic) %>% 
  formattable(caption = paste("Manova: (mean_f0_z, mean_slope_z) ~ mode, where mode = ",paste(compare, collapse=", "), sep = ""),
              list(p.adjusted = formatter("span", style = p_color))) %>%
  mutate(
    p.value = if_else(
      p.value < 0.001,
      as.character(scientific(p.value)),
      as.character(round(p.value, 4))
    ),
    p.adjusted = if_else(
      p.adjusted < 0.001,
      as.character(scientific(p.adjusted, digits=2)),
      as.character(round(p.adjusted, 4)),
    )
  ) %>%
  mutate(across(everything(),  ~  replace(., is.na(.), "")))

```

### Comparing MWH and MDQ
```{r, fig.width=5.5, fig.height=4}
compare <- c("MWH", "MDQ")

ggplot(m_corpus_summary %>% filter(mode %in% compare),
       aes(y=mean_f0_z,
           x=mean_slope_z,
           shape=mode,
           color=mode,
           size=mode)) +
  scale_color_manual(values = mode_colours) +
  scale_shape_manual(values = mode_shapes) +
  scale_size_manual(values = mode_sizes) +
  geom_density_2d(alpha=0.5) +
  geom_point(size = 1.5) +
  xlim(-5, 5) +
  ylim(-3, 3) +
  ggtitle(label = "mean F0 and mean slope z-score per speaker per stimulus",
          subtitle = paste("(",paste(compare, collapse=", "),")",sep = "")
          )

manova(cbind(mean_f0_z, mean_slope_z) ~ mode,
       data = m_corpus_summary %>% filter(mode %in% compare)) %>%
  tidy()  %>%
  bonferroniAdjust("", 7) %>%
    mutate(
    df = round(df, 3),
    pillai = round(pillai, 2),
    statistic = round(statistic, 3),
    den.df = round(den.df),
    
    p.adjusted = round(p.adjusted, 4)
  ) %>% 
  rename(`approx F` = statistic) %>% 
  formattable(caption = paste("Manova: (mean_f0_z, mean_slope_z) ~ mode, where mode = ",paste(compare, collapse=", "), sep = ""),
              list(p.adjusted = formatter("span", style = p_color))) %>%
  mutate(
    p.value = if_else(
      p.value < 0.001,
      as.character(scientific(p.value)),
      as.character(round(p.value, 4))
    ),
    p.adjusted = if_else(
      p.adjusted < 0.001,
      as.character(scientific(p.adjusted, digits=2)),
      as.character(round(p.adjusted, 4)),
    )
  ) %>%
  mutate(across(everything(),  ~  replace(., is.na(.), "")))

```

### Comparing MYN and MDQ
```{r, fig.width=5.5, fig.height=4}
compare <- c("MYN", "MDQ")

ggplot(m_corpus_summary %>% filter(mode %in% compare),
       aes(y=mean_f0_z,
           x=mean_slope_z,
           shape=mode,
           color=mode,
           size=mode)) +
  scale_color_manual(values = mode_colours) +
  scale_shape_manual(values = mode_shapes) +
  scale_size_manual(values = mode_sizes) +
  geom_density_2d(alpha=0.5) +
  geom_point(size = 1.5) +
  xlim(-5, 5) +
  ylim(-3, 3) +
  ggtitle(label = "mean F0 and mean slope z-score per speaker per stimulus",
          subtitle = paste("(",paste(compare, collapse=", "),")",sep = "")
          )

manova(cbind(mean_f0_z, mean_slope_z) ~ mode,
       data = m_corpus_summary %>% filter(mode %in% compare)) %>%
  tidy()  %>%
  bonferroniAdjust("", 7) %>%
    mutate(
    df = round(df, 3),
    pillai = round(pillai, 2),
    statistic = round(statistic, 3),
    den.df = round(den.df),
    
    p.adjusted = round(p.adjusted, 4)
  ) %>% 
  rename(`approx F` = statistic) %>% 
  formattable(caption = paste("Manova: (mean_f0_z, mean_slope_z) ~ mode, where mode = ",paste(compare, collapse=", "), sep = ""),
              list(p.adjusted = formatter("span", style = p_color))) %>%
  mutate(
    p.value = if_else(
      p.value < 0.001,
      as.character(scientific(p.value)),
      as.character(round(p.value, 4))
    ),
    p.adjusted = if_else(
      p.adjusted < 0.001,
      as.character(scientific(p.adjusted, digits=2)),
      as.character(round(p.adjusted, 4)),
    )
  ) %>%
  mutate(across(everything(),  ~  replace(., is.na(.), "")))

```

